// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"

	"github.com/oleg-tkachuk/paladin/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCategoryService creates a new instance of MockCategoryService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCategoryService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCategoryService {
	mock := &MockCategoryService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCategoryService is an autogenerated mock type for the CategoryService type
type MockCategoryService struct {
	mock.Mock
}

type MockCategoryService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCategoryService) EXPECT() *MockCategoryService_Expecter {
	return &MockCategoryService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockCategoryService
func (_mock *MockCategoryService) Create(ctx context.Context, tenantID string, slug string, name string, description *string) (*domain.Category, error) {
	ret := _mock.Called(ctx, tenantID, slug, name, description)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *domain.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *string) (*domain.Category, error)); ok {
		return returnFunc(ctx, tenantID, slug, name, description)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, *string) *domain.Category); ok {
		r0 = returnFunc(ctx, tenantID, slug, name, description)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, *string) error); ok {
		r1 = returnFunc(ctx, tenantID, slug, name, description)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockCategoryService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - slug string
//   - name string
//   - description *string
func (_e *MockCategoryService_Expecter) Create(ctx interface{}, tenantID interface{}, slug interface{}, name interface{}, description interface{}) *MockCategoryService_Create_Call {
	return &MockCategoryService_Create_Call{Call: _e.mock.On("Create", ctx, tenantID, slug, name, description)}
}

func (_c *MockCategoryService_Create_Call) Run(run func(ctx context.Context, tenantID string, slug string, name string, description *string)) *MockCategoryService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 *string
		if args[4] != nil {
			arg4 = args[4].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockCategoryService_Create_Call) Return(category *domain.Category, err error) *MockCategoryService_Create_Call {
	_c.Call.Return(category, err)
	return _c
}

func (_c *MockCategoryService_Create_Call) RunAndReturn(run func(ctx context.Context, tenantID string, slug string, name string, description *string) (*domain.Category, error)) *MockCategoryService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockCategoryService
func (_mock *MockCategoryService) Delete(ctx context.Context, tenantID string, slug string) error {
	ret := _mock.Called(ctx, tenantID, slug)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, tenantID, slug)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCategoryService_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockCategoryService_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - slug string
func (_e *MockCategoryService_Expecter) Delete(ctx interface{}, tenantID interface{}, slug interface{}) *MockCategoryService_Delete_Call {
	return &MockCategoryService_Delete_Call{Call: _e.mock.On("Delete", ctx, tenantID, slug)}
}

func (_c *MockCategoryService_Delete_Call) Run(run func(ctx context.Context, tenantID string, slug string)) *MockCategoryService_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCategoryService_Delete_Call) Return(err error) *MockCategoryService_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCategoryService_Delete_Call) RunAndReturn(run func(ctx context.Context, tenantID string, slug string) error) *MockCategoryService_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockCategoryService
func (_mock *MockCategoryService) Get(ctx context.Context, tenantID string, slug string) (*domain.Category, error) {
	ret := _mock.Called(ctx, tenantID, slug)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Category
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*domain.Category, error)); ok {
		return returnFunc(ctx, tenantID, slug)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *domain.Category); ok {
		r0 = returnFunc(ctx, tenantID, slug)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, tenantID, slug)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCategoryService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockCategoryService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - slug string
func (_e *MockCategoryService_Expecter) Get(ctx interface{}, tenantID interface{}, slug interface{}) *MockCategoryService_Get_Call {
	return &MockCategoryService_Get_Call{Call: _e.mock.On("Get", ctx, tenantID, slug)}
}

func (_c *MockCategoryService_Get_Call) Run(run func(ctx context.Context, tenantID string, slug string)) *MockCategoryService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCategoryService_Get_Call) Return(category *domain.Category, err error) *MockCategoryService_Get_Call {
	_c.Call.Return(category, err)
	return _c
}

func (_c *MockCategoryService_Get_Call) RunAndReturn(run func(ctx context.Context, tenantID string, slug string) (*domain.Category, error)) *MockCategoryService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockCategoryService
func (_mock *MockCategoryService) List(ctx context.Context, tenantID string, limit int, cursor string) ([]domain.Category, string, error) {
	ret := _mock.Called(ctx, tenantID, limit, cursor)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []domain.Category
	var r1 string
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, string) ([]domain.Category, string, error)); ok {
		return returnFunc(ctx, tenantID, limit, cursor)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, int, string) []domain.Category); ok {
		r0 = returnFunc(ctx, tenantID, limit, cursor)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Category)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, int, string) string); ok {
		r1 = returnFunc(ctx, tenantID, limit, cursor)
	} else {
		r1 = ret.Get(1).(string)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string, int, string) error); ok {
		r2 = returnFunc(ctx, tenantID, limit, cursor)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockCategoryService_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockCategoryService_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - tenantID string
//   - limit int
//   - cursor string
func (_e *MockCategoryService_Expecter) List(ctx interface{}, tenantID interface{}, limit interface{}, cursor interface{}) *MockCategoryService_List_Call {
	return &MockCategoryService_List_Call{Call: _e.mock.On("List", ctx, tenantID, limit, cursor)}
}

func (_c *MockCategoryService_List_Call) Run(run func(ctx context.Context, tenantID string, limit int, cursor string)) *MockCategoryService_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockCategoryService_List_Call) Return(categorys []domain.Category, s string, err error) *MockCategoryService_List_Call {
	_c.Call.Return(categorys, s, err)
	return _c
}

func (_c *MockCategoryService_List_Call) RunAndReturn(run func(ctx context.Context, tenantID string, limit int, cursor string) ([]domain.Category, string, error)) *MockCategoryService_List_Call {
	_c.Call.Return(run)
	return _c
}
