// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package domain

import (
	"context"
	"time"

	"github.com/oleg-tkachuk/paladin/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockStorageClient creates a new instance of MockStorageClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStorageClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStorageClient {
	mock := &MockStorageClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockStorageClient is an autogenerated mock type for the StorageClient type
type MockStorageClient struct {
	mock.Mock
}

type MockStorageClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStorageClient) EXPECT() *MockStorageClient_Expecter {
	return &MockStorageClient_Expecter{mock: &_m.Mock}
}

// AbortMultipartUpload provides a mock function for the type MockStorageClient
func (_mock *MockStorageClient) AbortMultipartUpload(ctx context.Context, key string, uploadID string) error {
	ret := _mock.Called(ctx, key, uploadID)

	if len(ret) == 0 {
		panic("no return value specified for AbortMultipartUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, key, uploadID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorageClient_AbortMultipartUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AbortMultipartUpload'
type MockStorageClient_AbortMultipartUpload_Call struct {
	*mock.Call
}

// AbortMultipartUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - uploadID string
func (_e *MockStorageClient_Expecter) AbortMultipartUpload(ctx interface{}, key interface{}, uploadID interface{}) *MockStorageClient_AbortMultipartUpload_Call {
	return &MockStorageClient_AbortMultipartUpload_Call{Call: _e.mock.On("AbortMultipartUpload", ctx, key, uploadID)}
}

func (_c *MockStorageClient_AbortMultipartUpload_Call) Run(run func(ctx context.Context, key string, uploadID string)) *MockStorageClient_AbortMultipartUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorageClient_AbortMultipartUpload_Call) Return(err error) *MockStorageClient_AbortMultipartUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorageClient_AbortMultipartUpload_Call) RunAndReturn(run func(ctx context.Context, key string, uploadID string) error) *MockStorageClient_AbortMultipartUpload_Call {
	_c.Call.Return(run)
	return _c
}

// BucketName provides a mock function for the type MockStorageClient
func (_mock *MockStorageClient) BucketName() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for BucketName")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockStorageClient_BucketName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BucketName'
type MockStorageClient_BucketName_Call struct {
	*mock.Call
}

// BucketName is a helper method to define mock.On call
func (_e *MockStorageClient_Expecter) BucketName() *MockStorageClient_BucketName_Call {
	return &MockStorageClient_BucketName_Call{Call: _e.mock.On("BucketName")}
}

func (_c *MockStorageClient_BucketName_Call) Run(run func()) *MockStorageClient_BucketName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorageClient_BucketName_Call) Return(s string) *MockStorageClient_BucketName_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockStorageClient_BucketName_Call) RunAndReturn(run func() string) *MockStorageClient_BucketName_Call {
	_c.Call.Return(run)
	return _c
}

// CompleteMultipartUpload provides a mock function for the type MockStorageClient
func (_mock *MockStorageClient) CompleteMultipartUpload(ctx context.Context, key string, uploadID string, parts []domain.CompletePart) error {
	ret := _mock.Called(ctx, key, uploadID, parts)

	if len(ret) == 0 {
		panic("no return value specified for CompleteMultipartUpload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, []domain.CompletePart) error); ok {
		r0 = returnFunc(ctx, key, uploadID, parts)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorageClient_CompleteMultipartUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompleteMultipartUpload'
type MockStorageClient_CompleteMultipartUpload_Call struct {
	*mock.Call
}

// CompleteMultipartUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - uploadID string
//   - parts []domain.CompletePart
func (_e *MockStorageClient_Expecter) CompleteMultipartUpload(ctx interface{}, key interface{}, uploadID interface{}, parts interface{}) *MockStorageClient_CompleteMultipartUpload_Call {
	return &MockStorageClient_CompleteMultipartUpload_Call{Call: _e.mock.On("CompleteMultipartUpload", ctx, key, uploadID, parts)}
}

func (_c *MockStorageClient_CompleteMultipartUpload_Call) Run(run func(ctx context.Context, key string, uploadID string, parts []domain.CompletePart)) *MockStorageClient_CompleteMultipartUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 []domain.CompletePart
		if args[3] != nil {
			arg3 = args[3].([]domain.CompletePart)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockStorageClient_CompleteMultipartUpload_Call) Return(err error) *MockStorageClient_CompleteMultipartUpload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorageClient_CompleteMultipartUpload_Call) RunAndReturn(run func(ctx context.Context, key string, uploadID string, parts []domain.CompletePart) error) *MockStorageClient_CompleteMultipartUpload_Call {
	_c.Call.Return(run)
	return _c
}

// CopyObject provides a mock function for the type MockStorageClient
func (_mock *MockStorageClient) CopyObject(ctx context.Context, srcKey string, dstKey string) error {
	ret := _mock.Called(ctx, srcKey, dstKey)

	if len(ret) == 0 {
		panic("no return value specified for CopyObject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, srcKey, dstKey)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorageClient_CopyObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CopyObject'
type MockStorageClient_CopyObject_Call struct {
	*mock.Call
}

// CopyObject is a helper method to define mock.On call
//   - ctx context.Context
//   - srcKey string
//   - dstKey string
func (_e *MockStorageClient_Expecter) CopyObject(ctx interface{}, srcKey interface{}, dstKey interface{}) *MockStorageClient_CopyObject_Call {
	return &MockStorageClient_CopyObject_Call{Call: _e.mock.On("CopyObject", ctx, srcKey, dstKey)}
}

func (_c *MockStorageClient_CopyObject_Call) Run(run func(ctx context.Context, srcKey string, dstKey string)) *MockStorageClient_CopyObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorageClient_CopyObject_Call) Return(err error) *MockStorageClient_CopyObject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorageClient_CopyObject_Call) RunAndReturn(run func(ctx context.Context, srcKey string, dstKey string) error) *MockStorageClient_CopyObject_Call {
	_c.Call.Return(run)
	return _c
}

// CreateMultipartUpload provides a mock function for the type MockStorageClient
func (_mock *MockStorageClient) CreateMultipartUpload(ctx context.Context, key string, contentType string) (domain.MultipartInit, error) {
	ret := _mock.Called(ctx, key, contentType)

	if len(ret) == 0 {
		panic("no return value specified for CreateMultipartUpload")
	}

	var r0 domain.MultipartInit
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (domain.MultipartInit, error)); ok {
		return returnFunc(ctx, key, contentType)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) domain.MultipartInit); ok {
		r0 = returnFunc(ctx, key, contentType)
	} else {
		r0 = ret.Get(0).(domain.MultipartInit)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, key, contentType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageClient_CreateMultipartUpload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateMultipartUpload'
type MockStorageClient_CreateMultipartUpload_Call struct {
	*mock.Call
}

// CreateMultipartUpload is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - contentType string
func (_e *MockStorageClient_Expecter) CreateMultipartUpload(ctx interface{}, key interface{}, contentType interface{}) *MockStorageClient_CreateMultipartUpload_Call {
	return &MockStorageClient_CreateMultipartUpload_Call{Call: _e.mock.On("CreateMultipartUpload", ctx, key, contentType)}
}

func (_c *MockStorageClient_CreateMultipartUpload_Call) Run(run func(ctx context.Context, key string, contentType string)) *MockStorageClient_CreateMultipartUpload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorageClient_CreateMultipartUpload_Call) Return(multipartInit domain.MultipartInit, err error) *MockStorageClient_CreateMultipartUpload_Call {
	_c.Call.Return(multipartInit, err)
	return _c
}

func (_c *MockStorageClient_CreateMultipartUpload_Call) RunAndReturn(run func(ctx context.Context, key string, contentType string) (domain.MultipartInit, error)) *MockStorageClient_CreateMultipartUpload_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteObject provides a mock function for the type MockStorageClient
func (_mock *MockStorageClient) DeleteObject(ctx context.Context, key string) error {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteObject")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockStorageClient_DeleteObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteObject'
type MockStorageClient_DeleteObject_Call struct {
	*mock.Call
}

// DeleteObject is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStorageClient_Expecter) DeleteObject(ctx interface{}, key interface{}) *MockStorageClient_DeleteObject_Call {
	return &MockStorageClient_DeleteObject_Call{Call: _e.mock.On("DeleteObject", ctx, key)}
}

func (_c *MockStorageClient_DeleteObject_Call) Run(run func(ctx context.Context, key string)) *MockStorageClient_DeleteObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageClient_DeleteObject_Call) Return(err error) *MockStorageClient_DeleteObject_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockStorageClient_DeleteObject_Call) RunAndReturn(run func(ctx context.Context, key string) error) *MockStorageClient_DeleteObject_Call {
	_c.Call.Return(run)
	return _c
}

// HeadObject provides a mock function for the type MockStorageClient
func (_mock *MockStorageClient) HeadObject(ctx context.Context, key string) (*domain.HeadRecord, error) {
	ret := _mock.Called(ctx, key)

	if len(ret) == 0 {
		panic("no return value specified for HeadObject")
	}

	var r0 *domain.HeadRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*domain.HeadRecord, error)); ok {
		return returnFunc(ctx, key)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *domain.HeadRecord); ok {
		r0 = returnFunc(ctx, key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.HeadRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageClient_HeadObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HeadObject'
type MockStorageClient_HeadObject_Call struct {
	*mock.Call
}

// HeadObject is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
func (_e *MockStorageClient_Expecter) HeadObject(ctx interface{}, key interface{}) *MockStorageClient_HeadObject_Call {
	return &MockStorageClient_HeadObject_Call{Call: _e.mock.On("HeadObject", ctx, key)}
}

func (_c *MockStorageClient_HeadObject_Call) Run(run func(ctx context.Context, key string)) *MockStorageClient_HeadObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockStorageClient_HeadObject_Call) Return(headRecord *domain.HeadRecord, err error) *MockStorageClient_HeadObject_Call {
	_c.Call.Return(headRecord, err)
	return _c
}

func (_c *MockStorageClient_HeadObject_Call) RunAndReturn(run func(ctx context.Context, key string) (*domain.HeadRecord, error)) *MockStorageClient_HeadObject_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type MockStorageClient
func (_mock *MockStorageClient) Ping(ctx context.Context) (domain.S3PingResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 domain.S3PingResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (domain.S3PingResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) domain.S3PingResult); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(domain.S3PingResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageClient_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type MockStorageClient_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockStorageClient_Expecter) Ping(ctx interface{}) *MockStorageClient_Ping_Call {
	return &MockStorageClient_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *MockStorageClient_Ping_Call) Run(run func(ctx context.Context)) *MockStorageClient_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockStorageClient_Ping_Call) Return(s3PingResult domain.S3PingResult, err error) *MockStorageClient_Ping_Call {
	_c.Call.Return(s3PingResult, err)
	return _c
}

func (_c *MockStorageClient_Ping_Call) RunAndReturn(run func(ctx context.Context) (domain.S3PingResult, error)) *MockStorageClient_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// PresignGetObject provides a mock function for the type MockStorageClient
func (_mock *MockStorageClient) PresignGetObject(ctx context.Context, key string, ttl time.Duration) (domain.Presigned, error) {
	ret := _mock.Called(ctx, key, ttl)

	if len(ret) == 0 {
		panic("no return value specified for PresignGetObject")
	}

	var r0 domain.Presigned
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) (domain.Presigned, error)); ok {
		return returnFunc(ctx, key, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, time.Duration) domain.Presigned); ok {
		r0 = returnFunc(ctx, key, ttl)
	} else {
		r0 = ret.Get(0).(domain.Presigned)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, time.Duration) error); ok {
		r1 = returnFunc(ctx, key, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageClient_PresignGetObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignGetObject'
type MockStorageClient_PresignGetObject_Call struct {
	*mock.Call
}

// PresignGetObject is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - ttl time.Duration
func (_e *MockStorageClient_Expecter) PresignGetObject(ctx interface{}, key interface{}, ttl interface{}) *MockStorageClient_PresignGetObject_Call {
	return &MockStorageClient_PresignGetObject_Call{Call: _e.mock.On("PresignGetObject", ctx, key, ttl)}
}

func (_c *MockStorageClient_PresignGetObject_Call) Run(run func(ctx context.Context, key string, ttl time.Duration)) *MockStorageClient_PresignGetObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 time.Duration
		if args[2] != nil {
			arg2 = args[2].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockStorageClient_PresignGetObject_Call) Return(presigned domain.Presigned, err error) *MockStorageClient_PresignGetObject_Call {
	_c.Call.Return(presigned, err)
	return _c
}

func (_c *MockStorageClient_PresignGetObject_Call) RunAndReturn(run func(ctx context.Context, key string, ttl time.Duration) (domain.Presigned, error)) *MockStorageClient_PresignGetObject_Call {
	_c.Call.Return(run)
	return _c
}

// PresignPutObject provides a mock function for the type MockStorageClient
func (_mock *MockStorageClient) PresignPutObject(ctx context.Context, key string, contentType string, sizeBytes int64, ttl time.Duration) (domain.Presigned, error) {
	ret := _mock.Called(ctx, key, contentType, sizeBytes, ttl)

	if len(ret) == 0 {
		panic("no return value specified for PresignPutObject")
	}

	var r0 domain.Presigned
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64, time.Duration) (domain.Presigned, error)); ok {
		return returnFunc(ctx, key, contentType, sizeBytes, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int64, time.Duration) domain.Presigned); ok {
		r0 = returnFunc(ctx, key, contentType, sizeBytes, ttl)
	} else {
		r0 = ret.Get(0).(domain.Presigned)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int64, time.Duration) error); ok {
		r1 = returnFunc(ctx, key, contentType, sizeBytes, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageClient_PresignPutObject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignPutObject'
type MockStorageClient_PresignPutObject_Call struct {
	*mock.Call
}

// PresignPutObject is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - contentType string
//   - sizeBytes int64
//   - ttl time.Duration
func (_e *MockStorageClient_Expecter) PresignPutObject(ctx interface{}, key interface{}, contentType interface{}, sizeBytes interface{}, ttl interface{}) *MockStorageClient_PresignPutObject_Call {
	return &MockStorageClient_PresignPutObject_Call{Call: _e.mock.On("PresignPutObject", ctx, key, contentType, sizeBytes, ttl)}
}

func (_c *MockStorageClient_PresignPutObject_Call) Run(run func(ctx context.Context, key string, contentType string, sizeBytes int64, ttl time.Duration)) *MockStorageClient_PresignPutObject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int64
		if args[3] != nil {
			arg3 = args[3].(int64)
		}
		var arg4 time.Duration
		if args[4] != nil {
			arg4 = args[4].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockStorageClient_PresignPutObject_Call) Return(presigned domain.Presigned, err error) *MockStorageClient_PresignPutObject_Call {
	_c.Call.Return(presigned, err)
	return _c
}

func (_c *MockStorageClient_PresignPutObject_Call) RunAndReturn(run func(ctx context.Context, key string, contentType string, sizeBytes int64, ttl time.Duration) (domain.Presigned, error)) *MockStorageClient_PresignPutObject_Call {
	_c.Call.Return(run)
	return _c
}

// PresignTTLDuration provides a mock function for the type MockStorageClient
func (_mock *MockStorageClient) PresignTTLDuration() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PresignTTLDuration")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// MockStorageClient_PresignTTLDuration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignTTLDuration'
type MockStorageClient_PresignTTLDuration_Call struct {
	*mock.Call
}

// PresignTTLDuration is a helper method to define mock.On call
func (_e *MockStorageClient_Expecter) PresignTTLDuration() *MockStorageClient_PresignTTLDuration_Call {
	return &MockStorageClient_PresignTTLDuration_Call{Call: _e.mock.On("PresignTTLDuration")}
}

func (_c *MockStorageClient_PresignTTLDuration_Call) Run(run func()) *MockStorageClient_PresignTTLDuration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockStorageClient_PresignTTLDuration_Call) Return(duration time.Duration) *MockStorageClient_PresignTTLDuration_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *MockStorageClient_PresignTTLDuration_Call) RunAndReturn(run func() time.Duration) *MockStorageClient_PresignTTLDuration_Call {
	_c.Call.Return(run)
	return _c
}

// PresignUploadPart provides a mock function for the type MockStorageClient
func (_mock *MockStorageClient) PresignUploadPart(ctx context.Context, key string, uploadID string, partNumber int32, ttl time.Duration) (domain.Presigned, error) {
	ret := _mock.Called(ctx, key, uploadID, partNumber, ttl)

	if len(ret) == 0 {
		panic("no return value specified for PresignUploadPart")
	}

	var r0 domain.Presigned
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int32, time.Duration) (domain.Presigned, error)); ok {
		return returnFunc(ctx, key, uploadID, partNumber, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, int32, time.Duration) domain.Presigned); ok {
		r0 = returnFunc(ctx, key, uploadID, partNumber, ttl)
	} else {
		r0 = ret.Get(0).(domain.Presigned)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, int32, time.Duration) error); ok {
		r1 = returnFunc(ctx, key, uploadID, partNumber, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockStorageClient_PresignUploadPart_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PresignUploadPart'
type MockStorageClient_PresignUploadPart_Call struct {
	*mock.Call
}

// PresignUploadPart is a helper method to define mock.On call
//   - ctx context.Context
//   - key string
//   - uploadID string
//   - partNumber int32
//   - ttl time.Duration
func (_e *MockStorageClient_Expecter) PresignUploadPart(ctx interface{}, key interface{}, uploadID interface{}, partNumber interface{}, ttl interface{}) *MockStorageClient_PresignUploadPart_Call {
	return &MockStorageClient_PresignUploadPart_Call{Call: _e.mock.On("PresignUploadPart", ctx, key, uploadID, partNumber, ttl)}
}

func (_c *MockStorageClient_PresignUploadPart_Call) Run(run func(ctx context.Context, key string, uploadID string, partNumber int32, ttl time.Duration)) *MockStorageClient_PresignUploadPart_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 int32
		if args[3] != nil {
			arg3 = args[3].(int32)
		}
		var arg4 time.Duration
		if args[4] != nil {
			arg4 = args[4].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockStorageClient_PresignUploadPart_Call) Return(presigned domain.Presigned, err error) *MockStorageClient_PresignUploadPart_Call {
	_c.Call.Return(presigned, err)
	return _c
}

func (_c *MockStorageClient_PresignUploadPart_Call) RunAndReturn(run func(ctx context.Context, key string, uploadID string, partNumber int32, ttl time.Duration) (domain.Presigned, error)) *MockStorageClient_PresignUploadPart_Call {
	_c.Call.Return(run)
	return _c
}
