packages:
  paladin/internal/auth:
    config:
      all: true
      dir: internal/auth/mocks
      filename: "{{.InterfaceName | snakecase}}.go"
  paladin/internal/service:
    config:
      all: true
      dir: internal/service/mocks
      filename: "{{.InterfaceName | snakecase}}.go"
