# Generated from paladin/data/v1/object_tag_service.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.12.1 with parameter "protobuf=google".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compat import google_protobuf_binary_codec, google_protobuf_codecs
from connectrpc.compression.gzip import GzipCompression
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.protocol import ProtocolType
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, DEFAULT_READ_MAX_BYTES, Endpoint, EndpointSync
from pyqwest import Client, SyncClient

from .object_tag_service_pb2 import DeleteObjectTagsRequest, DeleteObjectTagsResponse, GetObjectTagsRequest, GetObjectTagsResponse, ListDistinctTagsRequest, ListDistinctTagsResponse, PutObjectTagsRequest, PutObjectTagsResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext



_DEFAULT_CODECS = google_protobuf_codecs()
_PROTO_BINARY_CODEC = google_protobuf_binary_codec()
_GZIP_COMPRESSION = GzipCompression()

class ObjectTagService(Protocol):
    """
    ObjectTagService isolates the tag-only path so callers can be granted
    "TagObject" without "UpdateObject" — common pattern for downstream
    classification systems.
    """
    async def get_object_tags(self, request: GetObjectTagsRequest, ctx: RequestContext[GetObjectTagsRequest, GetObjectTagsResponse], /) -> GetObjectTagsResponse:
        """
        GetObjectTags returns the object's tag map.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def put_object_tags(self, request: PutObjectTagsRequest, ctx: RequestContext[PutObjectTagsRequest, PutObjectTagsResponse], /) -> PutObjectTagsResponse:
        """
        PutObjectTags merges the supplied keys into the object's tags; keys absent
        from the request are left alone. resource_version is required.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def delete_object_tags(self, request: DeleteObjectTagsRequest, ctx: RequestContext[DeleteObjectTagsRequest, DeleteObjectTagsResponse], /) -> DeleteObjectTagsResponse:
        """
        DeleteObjectTags removes the named keys. Deleting a key that is not set is
        not an error. resource_version is required.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_distinct_tags(self, request: ListDistinctTagsRequest, ctx: RequestContext[ListDistinctTagsRequest, ListDistinctTagsResponse], /) -> ListDistinctTagsResponse:
        """
        ListDistinctTags enumerates the distinct tag key→values present across an
        Collection's live objects, so a UI can populate a tag-facet filter from the
        whole tenant scope rather than only the objects on the current page.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class ObjectTagServiceASGIApplication(ConnectASGIApplication[ObjectTagService]):
    def __init__(
        self,
        service: ObjectTagService | AsyncGenerator[ObjectTagService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/paladin.data.v1.ObjectTagService/GetObjectTags": Endpoint.unary(
                    method=MethodInfo(
                        name="GetObjectTags",
                        service_name="paladin.data.v1.ObjectTagService",
                        input=GetObjectTagsRequest,
                        output=GetObjectTagsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_object_tags,
                ),
                "/paladin.data.v1.ObjectTagService/PutObjectTags": Endpoint.unary(
                    method=MethodInfo(
                        name="PutObjectTags",
                        service_name="paladin.data.v1.ObjectTagService",
                        input=PutObjectTagsRequest,
                        output=PutObjectTagsResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.put_object_tags,
                ),
                "/paladin.data.v1.ObjectTagService/DeleteObjectTags": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteObjectTags",
                        service_name="paladin.data.v1.ObjectTagService",
                        input=DeleteObjectTagsRequest,
                        output=DeleteObjectTagsResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.delete_object_tags,
                ),
                "/paladin.data.v1.ObjectTagService/ListDistinctTags": Endpoint.unary(
                    method=MethodInfo(
                        name="ListDistinctTags",
                        service_name="paladin.data.v1.ObjectTagService",
                        input=ListDistinctTagsRequest,
                        output=ListDistinctTagsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_distinct_tags,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/paladin.data.v1.ObjectTagService"


class ObjectTagServiceClient(ConnectClient):
    """
    ObjectTagService isolates the tag-only path so callers can be granted
    "TagObject" without "UpdateObject" — common pattern for downstream
    classification systems.
    """
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    async def get_object_tags(
        self,
        request: GetObjectTagsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetObjectTagsResponse:
        """
        GetObjectTags returns the object's tag map.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetObjectTags",
                service_name="paladin.data.v1.ObjectTagService",
                input=GetObjectTagsRequest,
                output=GetObjectTagsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def put_object_tags(
        self,
        request: PutObjectTagsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> PutObjectTagsResponse:
        """
        PutObjectTags merges the supplied keys into the object's tags; keys absent
        from the request are left alone. resource_version is required.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PutObjectTags",
                service_name="paladin.data.v1.ObjectTagService",
                input=PutObjectTagsRequest,
                output=PutObjectTagsResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_object_tags(
        self,
        request: DeleteObjectTagsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> DeleteObjectTagsResponse:
        """
        DeleteObjectTags removes the named keys. Deleting a key that is not set is
        not an error. resource_version is required.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteObjectTags",
                service_name="paladin.data.v1.ObjectTagService",
                input=DeleteObjectTagsRequest,
                output=DeleteObjectTagsResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_distinct_tags(
        self,
        request: ListDistinctTagsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListDistinctTagsResponse:
        """
        ListDistinctTags enumerates the distinct tag key→values present across an
        Collection's live objects, so a UI can populate a tag-facet filter from the
        whole tenant scope rather than only the objects on the current page.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListDistinctTags",
                service_name="paladin.data.v1.ObjectTagService",
                input=ListDistinctTagsRequest,
                output=ListDistinctTagsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

class ObjectTagServiceSync(Protocol):
    """
    ObjectTagService isolates the tag-only path so callers can be granted
    "TagObject" without "UpdateObject" — common pattern for downstream
    classification systems.
    """
    def get_object_tags(self, request: GetObjectTagsRequest, ctx: RequestContext[GetObjectTagsRequest, GetObjectTagsResponse], /) -> GetObjectTagsResponse:
        """
        GetObjectTags returns the object's tag map.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def put_object_tags(self, request: PutObjectTagsRequest, ctx: RequestContext[PutObjectTagsRequest, PutObjectTagsResponse], /) -> PutObjectTagsResponse:
        """
        PutObjectTags merges the supplied keys into the object's tags; keys absent
        from the request are left alone. resource_version is required.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def delete_object_tags(self, request: DeleteObjectTagsRequest, ctx: RequestContext[DeleteObjectTagsRequest, DeleteObjectTagsResponse], /) -> DeleteObjectTagsResponse:
        """
        DeleteObjectTags removes the named keys. Deleting a key that is not set is
        not an error. resource_version is required.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_distinct_tags(self, request: ListDistinctTagsRequest, ctx: RequestContext[ListDistinctTagsRequest, ListDistinctTagsResponse], /) -> ListDistinctTagsResponse:
        """
        ListDistinctTags enumerates the distinct tag key→values present across an
        Collection's live objects, so a UI can populate a tag-facet filter from the
        whole tenant scope rather than only the objects on the current page.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class ObjectTagServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: ObjectTagServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            endpoints={
                "/paladin.data.v1.ObjectTagService/GetObjectTags": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetObjectTags",
                        service_name="paladin.data.v1.ObjectTagService",
                        input=GetObjectTagsRequest,
                        output=GetObjectTagsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_object_tags,
                ),
                "/paladin.data.v1.ObjectTagService/PutObjectTags": EndpointSync.unary(
                    method=MethodInfo(
                        name="PutObjectTags",
                        service_name="paladin.data.v1.ObjectTagService",
                        input=PutObjectTagsRequest,
                        output=PutObjectTagsResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.put_object_tags,
                ),
                "/paladin.data.v1.ObjectTagService/DeleteObjectTags": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteObjectTags",
                        service_name="paladin.data.v1.ObjectTagService",
                        input=DeleteObjectTagsRequest,
                        output=DeleteObjectTagsResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.delete_object_tags,
                ),
                "/paladin.data.v1.ObjectTagService/ListDistinctTags": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListDistinctTags",
                        service_name="paladin.data.v1.ObjectTagService",
                        input=ListDistinctTagsRequest,
                        output=ListDistinctTagsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_distinct_tags,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/paladin.data.v1.ObjectTagService"


class ObjectTagServiceClientSync(ConnectClientSync):
    """
    ObjectTagService isolates the tag-only path so callers can be granted
    "TagObject" without "UpdateObject" — common pattern for downstream
    classification systems.
    """
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[InterceptorSync] = (),
        http_client: SyncClient | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    def get_object_tags(
        self,
        request: GetObjectTagsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetObjectTagsResponse:
        """
        GetObjectTags returns the object's tag map.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetObjectTags",
                service_name="paladin.data.v1.ObjectTagService",
                input=GetObjectTagsRequest,
                output=GetObjectTagsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def put_object_tags(
        self,
        request: PutObjectTagsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> PutObjectTagsResponse:
        """
        PutObjectTags merges the supplied keys into the object's tags; keys absent
        from the request are left alone. resource_version is required.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="PutObjectTags",
                service_name="paladin.data.v1.ObjectTagService",
                input=PutObjectTagsRequest,
                output=PutObjectTagsResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def delete_object_tags(
        self,
        request: DeleteObjectTagsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> DeleteObjectTagsResponse:
        """
        DeleteObjectTags removes the named keys. Deleting a key that is not set is
        not an error. resource_version is required.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteObjectTags",
                service_name="paladin.data.v1.ObjectTagService",
                input=DeleteObjectTagsRequest,
                output=DeleteObjectTagsResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_distinct_tags(
        self,
        request: ListDistinctTagsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListDistinctTagsResponse:
        """
        ListDistinctTags enumerates the distinct tag key→values present across an
        Collection's live objects, so a UI can populate a tag-facet filter from the
        whole tenant scope rather than only the objects on the current page.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListDistinctTags",
                service_name="paladin.data.v1.ObjectTagService",
                input=ListDistinctTagsRequest,
                output=ListDistinctTagsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
