packages:
  github.com/oleg-tkachuk/paladin/backend/internal/auth:
    config:
      all: true
      dir: internal/auth/mocks
      filename: "{{.InterfaceName | snakecase}}.go"
  github.com/oleg-tkachuk/paladin/backend/internal/service:
    config:
      all: true
      dir: internal/service/mocks
      filename: "{{.InterfaceName | snakecase}}.go"
  github.com/oleg-tkachuk/paladin/backend/internal/domain:
    config:
      all: true
      dir: internal/domain/mocks
      filename: "{{.InterfaceName | snakecase}}.go"
  github.com/oleg-tkachuk/paladin/backend/internal/store/postgres:
    config:
      all: true
      dir: internal/store/postgres/mocks
      filename: "{{.InterfaceName | snakecase}}.go"
