repos:
  - repo: local
    hooks:
      - id: jq-check
        name: check json files with jq
        description: check json files with jq
        entry: ./.pre-commit/scripts/jq_check.sh
        language: script
        types: [json]
        stages: [pre-commit, pre-push, manual]
        exclude: '^vendor/|^crud/vendor|^subscriptions/vendor'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: '^vendor/|^crud/vendor|^subscriptions/vendor'
      - id: end-of-file-fixer
        exclude: '^vendor/|^crud/vendor|^subscriptions/vendor'
      - id: check-yaml
        exclude: '^vendor/|^crud/vendor|^subscriptions/vendor'
  - repo: https://github.com/google/yamlfmt
    rev: v0.20.0
    hooks:
      - id: yamlfmt
        exclude: '^vendor/|^crud/vendor|^subscriptions/vendor'
        #  - repo: https://github.com/golangci/golangci-lint
        #    rev: v2.7.2
        #    hooks:
        #      - id: golangci-lint
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-mod-tidy
