version: "3"

tasks:
  banner:
    internal: true
    cmds:
      - printf ">>> %s\n" "{{.MESSAGE}}"

  tools:check:
    desc: "Verify that all required CLI tools are installed"
    internal: true
    preconditions:
      - sh: command -v minikube >/dev/null
        msg: "[ERROR] minikube is not installed"
      - sh: command -v docker >/dev/null
        msg: "[ERROR] docker is not installed"
      - sh: command -v helm >/dev/null
        msg: "[ERROR] helm is not installed"

  ds:prune:
    desc: "Docker system prune"
    silent: true
    deps:
      - dd:start
    cmds:
      - cmd: |-
          printf "INFO: {{.K8S_DEPLOYMENT_NAME}}: Pruning Docker system...\n"
      - cmd: |-
          docker system prune --volumes --force
      - cmd: |-
          printf "INFO: {{.K8S_DEPLOYMENT_NAME}}: Pruning Minikube Docker system...\n"
      - cmd: |-
          minikube ssh "docker system prune -a --volumes --force" || true

  dd:start:
    desc: "Start Docker Desktop"
    silent: true
    cmds:
      - cmd: |-
          printf "INFO: {{.K8S_DEPLOYMENT_NAME}}: Starting Docker Desktop...\n"
      - cmd: |-
          docker desktop start
