// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: paladin/v1/presign_service.proto

package grpcapiconnect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"
	grpc "github.com/oleg-tkachuk/paladin/internal/api/grpc"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// PresignServiceName is the fully-qualified name of the PresignService service.
	PresignServiceName = "paladin.v1.PresignService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// PresignServiceGenerateUploadUrlProcedure is the fully-qualified name of the PresignService's
	// GenerateUploadUrl RPC.
	PresignServiceGenerateUploadUrlProcedure = "/paladin.v1.PresignService/GenerateUploadUrl"
	// PresignServiceGenerateDownloadUrlProcedure is the fully-qualified name of the PresignService's
	// GenerateDownloadUrl RPC.
	PresignServiceGenerateDownloadUrlProcedure = "/paladin.v1.PresignService/GenerateDownloadUrl"
)

// PresignServiceClient is a client for the paladin.v1.PresignService service.
type PresignServiceClient interface {
	// GenerateUploadUrl creates a presigned URL for uploading content
	// to an existing object that is in PENDING or UPLOADING status.
	GenerateUploadUrl(context.Context, *connect.Request[grpc.GenerateUploadUrlRequest]) (*connect.Response[grpc.GenerateUploadUrlResponse], error)
	// GenerateDownloadUrl creates a presigned URL for downloading content
	// from an existing object that is in AVAILABLE status.
	GenerateDownloadUrl(context.Context, *connect.Request[grpc.GenerateDownloadUrlRequest]) (*connect.Response[grpc.GenerateDownloadUrlResponse], error)
}

// NewPresignServiceClient constructs a client for the paladin.v1.PresignService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewPresignServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) PresignServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	presignServiceMethods := grpc.File_paladin_v1_presign_service_proto.Services().ByName("PresignService").Methods()
	return &presignServiceClient{
		generateUploadUrl: connect.NewClient[grpc.GenerateUploadUrlRequest, grpc.GenerateUploadUrlResponse](
			httpClient,
			baseURL+PresignServiceGenerateUploadUrlProcedure,
			connect.WithSchema(presignServiceMethods.ByName("GenerateUploadUrl")),
			connect.WithClientOptions(opts...),
		),
		generateDownloadUrl: connect.NewClient[grpc.GenerateDownloadUrlRequest, grpc.GenerateDownloadUrlResponse](
			httpClient,
			baseURL+PresignServiceGenerateDownloadUrlProcedure,
			connect.WithSchema(presignServiceMethods.ByName("GenerateDownloadUrl")),
			connect.WithClientOptions(opts...),
		),
	}
}

// presignServiceClient implements PresignServiceClient.
type presignServiceClient struct {
	generateUploadUrl   *connect.Client[grpc.GenerateUploadUrlRequest, grpc.GenerateUploadUrlResponse]
	generateDownloadUrl *connect.Client[grpc.GenerateDownloadUrlRequest, grpc.GenerateDownloadUrlResponse]
}

// GenerateUploadUrl calls paladin.v1.PresignService.GenerateUploadUrl.
func (c *presignServiceClient) GenerateUploadUrl(ctx context.Context, req *connect.Request[grpc.GenerateUploadUrlRequest]) (*connect.Response[grpc.GenerateUploadUrlResponse], error) {
	return c.generateUploadUrl.CallUnary(ctx, req)
}

// GenerateDownloadUrl calls paladin.v1.PresignService.GenerateDownloadUrl.
func (c *presignServiceClient) GenerateDownloadUrl(ctx context.Context, req *connect.Request[grpc.GenerateDownloadUrlRequest]) (*connect.Response[grpc.GenerateDownloadUrlResponse], error) {
	return c.generateDownloadUrl.CallUnary(ctx, req)
}

// PresignServiceHandler is an implementation of the paladin.v1.PresignService service.
type PresignServiceHandler interface {
	// GenerateUploadUrl creates a presigned URL for uploading content
	// to an existing object that is in PENDING or UPLOADING status.
	GenerateUploadUrl(context.Context, *connect.Request[grpc.GenerateUploadUrlRequest]) (*connect.Response[grpc.GenerateUploadUrlResponse], error)
	// GenerateDownloadUrl creates a presigned URL for downloading content
	// from an existing object that is in AVAILABLE status.
	GenerateDownloadUrl(context.Context, *connect.Request[grpc.GenerateDownloadUrlRequest]) (*connect.Response[grpc.GenerateDownloadUrlResponse], error)
}

// NewPresignServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewPresignServiceHandler(svc PresignServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	presignServiceMethods := grpc.File_paladin_v1_presign_service_proto.Services().ByName("PresignService").Methods()
	presignServiceGenerateUploadUrlHandler := connect.NewUnaryHandler(
		PresignServiceGenerateUploadUrlProcedure,
		svc.GenerateUploadUrl,
		connect.WithSchema(presignServiceMethods.ByName("GenerateUploadUrl")),
		connect.WithHandlerOptions(opts...),
	)
	presignServiceGenerateDownloadUrlHandler := connect.NewUnaryHandler(
		PresignServiceGenerateDownloadUrlProcedure,
		svc.GenerateDownloadUrl,
		connect.WithSchema(presignServiceMethods.ByName("GenerateDownloadUrl")),
		connect.WithHandlerOptions(opts...),
	)
	return "/paladin.v1.PresignService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case PresignServiceGenerateUploadUrlProcedure:
			presignServiceGenerateUploadUrlHandler.ServeHTTP(w, r)
		case PresignServiceGenerateDownloadUrlProcedure:
			presignServiceGenerateDownloadUrlHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedPresignServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedPresignServiceHandler struct{}

func (UnimplementedPresignServiceHandler) GenerateUploadUrl(context.Context, *connect.Request[grpc.GenerateUploadUrlRequest]) (*connect.Response[grpc.GenerateUploadUrlResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paladin.v1.PresignService.GenerateUploadUrl is not implemented"))
}

func (UnimplementedPresignServiceHandler) GenerateDownloadUrl(context.Context, *connect.Request[grpc.GenerateDownloadUrlRequest]) (*connect.Response[grpc.GenerateDownloadUrlResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paladin.v1.PresignService.GenerateDownloadUrl is not implemented"))
}
