// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: paladin/admin/v1/billing_service.proto

package paladinadminv1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"
	v1 "github.com/oleg-tkachuk/paladin/backend/internal/api/pb/admin/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BillingServiceName is the fully-qualified name of the BillingService service.
	BillingServiceName = "paladin.admin.v1.BillingService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BillingServiceGetTenantSummaryProcedure is the fully-qualified name of the BillingService's
	// GetTenantSummary RPC.
	BillingServiceGetTenantSummaryProcedure = "/paladin.admin.v1.BillingService/GetTenantSummary"
	// BillingServiceGetTenantTimeSeriesProcedure is the fully-qualified name of the BillingService's
	// GetTenantTimeSeries RPC.
	BillingServiceGetTenantTimeSeriesProcedure = "/paladin.admin.v1.BillingService/GetTenantTimeSeries"
)

// BillingServiceClient is a client for the paladin.admin.v1.BillingService service.
type BillingServiceClient interface {
	// GetTenantSummary returns aggregate spend + top-N breakdowns for
	// the supplied period. Defaults to last 30 days when period_start
	// / period_end are unset.
	GetTenantSummary(context.Context, *connect.Request[v1.GetTenantSummaryRequest]) (*connect.Response[v1.GetTenantSummaryResponse], error)
	// GetTenantTimeSeries returns time-bucketed spend for a chart.
	// granularity ∈ {hour, day, week} — server validates.
	GetTenantTimeSeries(context.Context, *connect.Request[v1.GetTenantTimeSeriesRequest]) (*connect.Response[v1.GetTenantTimeSeriesResponse], error)
}

// NewBillingServiceClient constructs a client for the paladin.admin.v1.BillingService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBillingServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BillingServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	billingServiceMethods := v1.File_paladin_admin_v1_billing_service_proto.Services().ByName("BillingService").Methods()
	return &billingServiceClient{
		getTenantSummary: connect.NewClient[v1.GetTenantSummaryRequest, v1.GetTenantSummaryResponse](
			httpClient,
			baseURL+BillingServiceGetTenantSummaryProcedure,
			connect.WithSchema(billingServiceMethods.ByName("GetTenantSummary")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getTenantTimeSeries: connect.NewClient[v1.GetTenantTimeSeriesRequest, v1.GetTenantTimeSeriesResponse](
			httpClient,
			baseURL+BillingServiceGetTenantTimeSeriesProcedure,
			connect.WithSchema(billingServiceMethods.ByName("GetTenantTimeSeries")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
	}
}

// billingServiceClient implements BillingServiceClient.
type billingServiceClient struct {
	getTenantSummary    *connect.Client[v1.GetTenantSummaryRequest, v1.GetTenantSummaryResponse]
	getTenantTimeSeries *connect.Client[v1.GetTenantTimeSeriesRequest, v1.GetTenantTimeSeriesResponse]
}

// GetTenantSummary calls paladin.admin.v1.BillingService.GetTenantSummary.
func (c *billingServiceClient) GetTenantSummary(ctx context.Context, req *connect.Request[v1.GetTenantSummaryRequest]) (*connect.Response[v1.GetTenantSummaryResponse], error) {
	return c.getTenantSummary.CallUnary(ctx, req)
}

// GetTenantTimeSeries calls paladin.admin.v1.BillingService.GetTenantTimeSeries.
func (c *billingServiceClient) GetTenantTimeSeries(ctx context.Context, req *connect.Request[v1.GetTenantTimeSeriesRequest]) (*connect.Response[v1.GetTenantTimeSeriesResponse], error) {
	return c.getTenantTimeSeries.CallUnary(ctx, req)
}

// BillingServiceHandler is an implementation of the paladin.admin.v1.BillingService service.
type BillingServiceHandler interface {
	// GetTenantSummary returns aggregate spend + top-N breakdowns for
	// the supplied period. Defaults to last 30 days when period_start
	// / period_end are unset.
	GetTenantSummary(context.Context, *connect.Request[v1.GetTenantSummaryRequest]) (*connect.Response[v1.GetTenantSummaryResponse], error)
	// GetTenantTimeSeries returns time-bucketed spend for a chart.
	// granularity ∈ {hour, day, week} — server validates.
	GetTenantTimeSeries(context.Context, *connect.Request[v1.GetTenantTimeSeriesRequest]) (*connect.Response[v1.GetTenantTimeSeriesResponse], error)
}

// NewBillingServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBillingServiceHandler(svc BillingServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	billingServiceMethods := v1.File_paladin_admin_v1_billing_service_proto.Services().ByName("BillingService").Methods()
	billingServiceGetTenantSummaryHandler := connect.NewUnaryHandler(
		BillingServiceGetTenantSummaryProcedure,
		svc.GetTenantSummary,
		connect.WithSchema(billingServiceMethods.ByName("GetTenantSummary")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	billingServiceGetTenantTimeSeriesHandler := connect.NewUnaryHandler(
		BillingServiceGetTenantTimeSeriesProcedure,
		svc.GetTenantTimeSeries,
		connect.WithSchema(billingServiceMethods.ByName("GetTenantTimeSeries")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	return "/paladin.admin.v1.BillingService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BillingServiceGetTenantSummaryProcedure:
			billingServiceGetTenantSummaryHandler.ServeHTTP(w, r)
		case BillingServiceGetTenantTimeSeriesProcedure:
			billingServiceGetTenantTimeSeriesHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBillingServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBillingServiceHandler struct{}

func (UnimplementedBillingServiceHandler) GetTenantSummary(context.Context, *connect.Request[v1.GetTenantSummaryRequest]) (*connect.Response[v1.GetTenantSummaryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paladin.admin.v1.BillingService.GetTenantSummary is not implemented"))
}

func (UnimplementedBillingServiceHandler) GetTenantTimeSeries(context.Context, *connect.Request[v1.GetTenantTimeSeriesRequest]) (*connect.Response[v1.GetTenantTimeSeriesResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paladin.admin.v1.BillingService.GetTenantTimeSeries is not implemented"))
}
