from google.protobuf.internal import enum_type_wrapper as _enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from typing import ClassVar as _ClassVar

DESCRIPTOR: _descriptor.FileDescriptor

class ErrorReason(int, metaclass=_enum_type_wrapper.EnumTypeWrapper):
    __slots__ = ()
    ERROR_REASON_UNSPECIFIED: _ClassVar[ErrorReason]
    ERROR_REASON_NOT_FOUND: _ClassVar[ErrorReason]
    ERROR_REASON_VERSION_CONFLICT: _ClassVar[ErrorReason]
    ERROR_REASON_ALREADY_EXISTS: _ClassVar[ErrorReason]
    ERROR_REASON_INVALID_ARGUMENT: _ClassVar[ErrorReason]
    ERROR_REASON_PERMISSION_DENIED: _ClassVar[ErrorReason]
    ERROR_REASON_FAILED_PRECONDITION: _ClassVar[ErrorReason]
    ERROR_REASON_UNAUTHENTICATED: _ClassVar[ErrorReason]
    ERROR_REASON_SUBJECT_TAKEN: _ClassVar[ErrorReason]
    ERROR_REASON_COLLECTION_NOT_EMPTY: _ClassVar[ErrorReason]
    ERROR_REASON_COLLECTION_EXISTS: _ClassVar[ErrorReason]
    ERROR_REASON_BUCKET_NOT_FOUND: _ClassVar[ErrorReason]
    ERROR_REASON_POLICY_UNPARSEABLE: _ClassVar[ErrorReason]
    ERROR_REASON_SLUG_TAKEN: _ClassVar[ErrorReason]
    ERROR_REASON_TENANT_ID_TAKEN: _ClassVar[ErrorReason]
    ERROR_REASON_DISPLAY_NAME_TAKEN: _ClassVar[ErrorReason]
    ERROR_REASON_TENANT_ALREADY_DELETED: _ClassVar[ErrorReason]
    ERROR_REASON_TENANT_NOT_TRASHED: _ClassVar[ErrorReason]
    ERROR_REASON_DEFAULT_BINDING_BUCKET_MISSING: _ClassVar[ErrorReason]
    ERROR_REASON_TENANT_HAS_CHILDREN: _ClassVar[ErrorReason]
    ERROR_REASON_OBJECT_TAG_EXISTS: _ClassVar[ErrorReason]
    ERROR_REASON_BACKEND_DISABLED: _ClassVar[ErrorReason]
    ERROR_REASON_BACKEND_READ_ONLY: _ClassVar[ErrorReason]
    ERROR_REASON_OBJECT_VERSION_NOT_FOUND: _ClassVar[ErrorReason]
    ERROR_REASON_CONFLICT: _ClassVar[ErrorReason]
    ERROR_REASON_TENANT_NOT_FOUND: _ClassVar[ErrorReason]
ERROR_REASON_UNSPECIFIED: ErrorReason
ERROR_REASON_NOT_FOUND: ErrorReason
ERROR_REASON_VERSION_CONFLICT: ErrorReason
ERROR_REASON_ALREADY_EXISTS: ErrorReason
ERROR_REASON_INVALID_ARGUMENT: ErrorReason
ERROR_REASON_PERMISSION_DENIED: ErrorReason
ERROR_REASON_FAILED_PRECONDITION: ErrorReason
ERROR_REASON_UNAUTHENTICATED: ErrorReason
ERROR_REASON_SUBJECT_TAKEN: ErrorReason
ERROR_REASON_COLLECTION_NOT_EMPTY: ErrorReason
ERROR_REASON_COLLECTION_EXISTS: ErrorReason
ERROR_REASON_BUCKET_NOT_FOUND: ErrorReason
ERROR_REASON_POLICY_UNPARSEABLE: ErrorReason
ERROR_REASON_SLUG_TAKEN: ErrorReason
ERROR_REASON_TENANT_ID_TAKEN: ErrorReason
ERROR_REASON_DISPLAY_NAME_TAKEN: ErrorReason
ERROR_REASON_TENANT_ALREADY_DELETED: ErrorReason
ERROR_REASON_TENANT_NOT_TRASHED: ErrorReason
ERROR_REASON_DEFAULT_BINDING_BUCKET_MISSING: ErrorReason
ERROR_REASON_TENANT_HAS_CHILDREN: ErrorReason
ERROR_REASON_OBJECT_TAG_EXISTS: ErrorReason
ERROR_REASON_BACKEND_DISABLED: ErrorReason
ERROR_REASON_BACKEND_READ_ONLY: ErrorReason
ERROR_REASON_OBJECT_VERSION_NOT_FOUND: ErrorReason
ERROR_REASON_CONFLICT: ErrorReason
ERROR_REASON_TENANT_NOT_FOUND: ErrorReason
