// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: paladin/v1/presign_service.proto

package paladinapi

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GenerateUploadUrlRequest creates a presigned URL for uploading to an existing object.
type GenerateUploadUrlRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant identifier for logical isolation (opaque UUID, used as S3 key prefix).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Bucket containing the object.
	Bucket string `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	// Storage key of the object to upload to.
	Key string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	// Custom TTL for the presigned URL.
	// If omitted, the server uses its default expiration.
	Ttl *durationpb.Duration `protobuf:"bytes,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// Client-provided idempotency key.
	IdempotencyKey string `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateUploadUrlRequest) Reset() {
	*x = GenerateUploadUrlRequest{}
	mi := &file_paladin_v1_presign_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateUploadUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUploadUrlRequest) ProtoMessage() {}

func (x *GenerateUploadUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_v1_presign_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUploadUrlRequest.ProtoReflect.Descriptor instead.
func (*GenerateUploadUrlRequest) Descriptor() ([]byte, []int) {
	return file_paladin_v1_presign_service_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateUploadUrlRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GenerateUploadUrlRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *GenerateUploadUrlRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GenerateUploadUrlRequest) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *GenerateUploadUrlRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// GenerateUploadUrlResponse contains the presigned upload URL.
type GenerateUploadUrlResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Presigned URL for direct upload to the storage backend.
	UploadUrl     *PresignedUrl `protobuf:"bytes,1,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateUploadUrlResponse) Reset() {
	*x = GenerateUploadUrlResponse{}
	mi := &file_paladin_v1_presign_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateUploadUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateUploadUrlResponse) ProtoMessage() {}

func (x *GenerateUploadUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_v1_presign_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateUploadUrlResponse.ProtoReflect.Descriptor instead.
func (*GenerateUploadUrlResponse) Descriptor() ([]byte, []int) {
	return file_paladin_v1_presign_service_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateUploadUrlResponse) GetUploadUrl() *PresignedUrl {
	if x != nil {
		return x.UploadUrl
	}
	return nil
}

// GenerateDownloadUrlRequest creates a presigned URL for downloading from an existing object.
type GenerateDownloadUrlRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Tenant identifier for logical isolation (opaque UUID, used as S3 key prefix).
	TenantId string `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	// Bucket containing the object.
	Bucket string `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	// Storage key of the object to download.
	Key string `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	// Custom TTL for the presigned URL.
	// If omitted, the server uses its default expiration.
	Ttl *durationpb.Duration `protobuf:"bytes,4,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// Optional override for the Content-Disposition header in the download response.
	// Use this to control the filename shown to the end user (e.g. "attachment; filename=\"report.pdf\"").
	ContentDisposition string `protobuf:"bytes,5,opt,name=content_disposition,json=contentDisposition,proto3" json:"content_disposition,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *GenerateDownloadUrlRequest) Reset() {
	*x = GenerateDownloadUrlRequest{}
	mi := &file_paladin_v1_presign_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDownloadUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDownloadUrlRequest) ProtoMessage() {}

func (x *GenerateDownloadUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_v1_presign_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDownloadUrlRequest.ProtoReflect.Descriptor instead.
func (*GenerateDownloadUrlRequest) Descriptor() ([]byte, []int) {
	return file_paladin_v1_presign_service_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateDownloadUrlRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GenerateDownloadUrlRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *GenerateDownloadUrlRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GenerateDownloadUrlRequest) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *GenerateDownloadUrlRequest) GetContentDisposition() string {
	if x != nil {
		return x.ContentDisposition
	}
	return ""
}

// GenerateDownloadUrlResponse contains the presigned download URL.
type GenerateDownloadUrlResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Presigned URL for direct download from the storage backend.
	DownloadUrl   *PresignedUrl `protobuf:"bytes,1,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateDownloadUrlResponse) Reset() {
	*x = GenerateDownloadUrlResponse{}
	mi := &file_paladin_v1_presign_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateDownloadUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateDownloadUrlResponse) ProtoMessage() {}

func (x *GenerateDownloadUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_v1_presign_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateDownloadUrlResponse.ProtoReflect.Descriptor instead.
func (*GenerateDownloadUrlResponse) Descriptor() ([]byte, []int) {
	return file_paladin_v1_presign_service_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateDownloadUrlResponse) GetDownloadUrl() *PresignedUrl {
	if x != nil {
		return x.DownloadUrl
	}
	return nil
}

var File_paladin_v1_presign_service_proto protoreflect.FileDescriptor

const file_paladin_v1_presign_service_proto_rawDesc = "" +
	"\n" +
	"\x1cocp/v1/presign_service.proto\x12\x06ocp.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x12ocp/v1/types.proto\"\xd3\x01\n" +
	"\x18GenerateUploadUrlRequest\x12%\n" +
	"\ttenant_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\btenantId\x12\x1f\n" +
	"\x06bucket\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06bucket\x12\x19\n" +
	"\x03key\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03key\x12+\n" +
	"\x03ttl\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"P\n" +
	"\x19GenerateUploadUrlResponse\x123\n" +
	"\n" +
	"upload_url\x18\x01 \x01(\v2\x14.paladin.v1.PresignedUrlR\tuploadUrl\"\xdd\x01\n" +
	"\x1aGenerateDownloadUrlRequest\x12%\n" +
	"\ttenant_id\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\btenantId\x12\x1f\n" +
	"\x06bucket\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06bucket\x12\x19\n" +
	"\x03key\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03key\x12+\n" +
	"\x03ttl\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\x12/\n" +
	"\x13content_disposition\x18\x05 \x01(\tR\x12contentDisposition\"V\n" +
	"\x1bGenerateDownloadUrlResponse\x127\n" +
	"\fdownload_url\x18\x01 \x01(\v2\x14.paladin.v1.PresignedUrlR\vdownloadUrl2\xf2\x02\n" +
	"\x0ePresignService\x12\xaa\x01\n" +
	"\x11GenerateUploadUrl\x12 .paladin.v1.GenerateUploadUrlRequest\x1a!.paladin.v1.GenerateUploadUrlResponse\"P\x82\xd3\xe4\x93\x02J:\x01*\"E/v1/tenants/{tenant_id}/buckets/{bucket}/objects/{key}:presign-upload\x12\xb2\x01\n" +
	"\x13GenerateDownloadUrl\x12\".paladin.v1.GenerateDownloadUrlRequest\x1a#.paladin.v1.GenerateDownloadUrlResponse\"R\x82\xd3\xe4\x93\x02L:\x01*\"G/v1/tenants/{tenant_id}/buckets/{bucket}/objects/{key}:presign-downloadBQZOgithub.com/oleg-tkachuk/paladin/internal/api/connect/paladinapi;paladinapib\x06proto3"

var (
	file_paladin_v1_presign_service_proto_rawDescOnce sync.Once
	file_paladin_v1_presign_service_proto_rawDescData []byte
)

func file_paladin_v1_presign_service_proto_rawDescGZIP() []byte {
	file_paladin_v1_presign_service_proto_rawDescOnce.Do(func() {
		file_paladin_v1_presign_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paladin_v1_presign_service_proto_rawDesc), len(file_paladin_v1_presign_service_proto_rawDesc)))
	})
	return file_paladin_v1_presign_service_proto_rawDescData
}

var file_paladin_v1_presign_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_paladin_v1_presign_service_proto_goTypes = []any{
	(*GenerateUploadUrlRequest)(nil),    // 0: paladin.v1.GenerateUploadUrlRequest
	(*GenerateUploadUrlResponse)(nil),   // 1: paladin.v1.GenerateUploadUrlResponse
	(*GenerateDownloadUrlRequest)(nil),  // 2: paladin.v1.GenerateDownloadUrlRequest
	(*GenerateDownloadUrlResponse)(nil), // 3: paladin.v1.GenerateDownloadUrlResponse
	(*durationpb.Duration)(nil),         // 4: google.protobuf.Duration
	(*PresignedUrl)(nil),                // 5: paladin.v1.PresignedUrl
}
var file_paladin_v1_presign_service_proto_depIdxs = []int32{
	4, // 0: paladin.v1.GenerateUploadUrlRequest.ttl:type_name -> google.protobuf.Duration
	5, // 1: paladin.v1.GenerateUploadUrlResponse.upload_url:type_name -> paladin.v1.PresignedUrl
	4, // 2: paladin.v1.GenerateDownloadUrlRequest.ttl:type_name -> google.protobuf.Duration
	5, // 3: paladin.v1.GenerateDownloadUrlResponse.download_url:type_name -> paladin.v1.PresignedUrl
	0, // 4: paladin.v1.PresignService.GenerateUploadUrl:input_type -> paladin.v1.GenerateUploadUrlRequest
	2, // 5: paladin.v1.PresignService.GenerateDownloadUrl:input_type -> paladin.v1.GenerateDownloadUrlRequest
	1, // 6: paladin.v1.PresignService.GenerateUploadUrl:output_type -> paladin.v1.GenerateUploadUrlResponse
	3, // 7: paladin.v1.PresignService.GenerateDownloadUrl:output_type -> paladin.v1.GenerateDownloadUrlResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_paladin_v1_presign_service_proto_init() }
func file_paladin_v1_presign_service_proto_init() {
	if File_paladin_v1_presign_service_proto != nil {
		return
	}
	file_paladin_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paladin_v1_presign_service_proto_rawDesc), len(file_paladin_v1_presign_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paladin_v1_presign_service_proto_goTypes,
		DependencyIndexes: file_paladin_v1_presign_service_proto_depIdxs,
		MessageInfos:      file_paladin_v1_presign_service_proto_msgTypes,
	}.Build()
	File_paladin_v1_presign_service_proto = out.File
	file_paladin_v1_presign_service_proto_goTypes = nil
	file_paladin_v1_presign_service_proto_depIdxs = nil
}
