# Generated from paladin/admin/v1/api_token_service.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.12.1 with parameter "protobuf=google".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compat import google_protobuf_binary_codec, google_protobuf_codecs
from connectrpc.compression.gzip import GzipCompression
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.protocol import ProtocolType
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, DEFAULT_READ_MAX_BYTES, Endpoint, EndpointSync
from pyqwest import Client, SyncClient

from .api_token_service_pb2 import APITokenServiceCreateRequest, APITokenServiceCreateResponse, APITokenServiceGetSelfRequest, APITokenServiceGetSelfResponse, APITokenServiceGetUsageRequest, APITokenServiceGetUsageResponse, APITokenServiceListRequest, APITokenServiceListResponse, APITokenServiceRevokeRequest, APITokenServiceRevokeResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext



_DEFAULT_CODECS = google_protobuf_codecs()
_PROTO_BINARY_CODEC = google_protobuf_binary_codec()
_GZIP_COMPRESSION = GzipCompression()

class APITokenService(Protocol):
    """
    APITokenService manages hashed-bearer M2M tokens (`paladin_pat_…`). Distinct
    from capability tokens (CapabilityService) which serve agent-runtime
    federation in JWT format. API tokens are long-lived service-to-
    service credentials that follow the Hatchet / GitHub PATs / Stripe
    pattern: stored as argon2id PHC hash, plaintext returned exactly
    once at creation.

    Naming: request / response types use the `APITokenService<Method>`
    prefix because the bare verbs (Create / Revoke / List) collide with
    other admin services in the same proto package — buf STANDARD lint
    requires the prefix when method names alone aren't unique.
    """
    async def create(self, request: APITokenServiceCreateRequest, ctx: RequestContext[APITokenServiceCreateRequest, APITokenServiceCreateResponse], /) -> APITokenServiceCreateResponse:
        """
        Create mints a new API token. Plaintext is returned exactly once
        in `token`; afterwards only the hash is persisted. Caller MUST
        treat the returned `token` as a write-once secret — the service
        can't recover it.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def revoke(self, request: APITokenServiceRevokeRequest, ctx: RequestContext[APITokenServiceRevokeRequest, APITokenServiceRevokeResponse], /) -> APITokenServiceRevokeResponse:
        """
        Revoke marks a token as revoked at NOW(). Idempotent — re-revoking
        a revoked token is a no-op. Cannot be undone; caller mints a new
        one to replace.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list(self, request: APITokenServiceListRequest, ctx: RequestContext[APITokenServiceListRequest, APITokenServiceListResponse], /) -> APITokenServiceListResponse:
        """
        List enumerates tokens for a tenant. Paginated cursor-style. The
        `token_hash` is never returned; callers see metadata only.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_self(self, request: APITokenServiceGetSelfRequest, ctx: RequestContext[APITokenServiceGetSelfRequest, APITokenServiceGetSelfResponse], /) -> APITokenServiceGetSelfResponse:
        """
        GetSelf introspects the API token attached to the calling request,
        if any. Returns NOT_FOUND when the request was authenticated via
        JWT or capability instead of an API token. Used by clients that
        want to display "you are authenticated as token X" without an
        out-of-band lookup.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_usage(self, request: APITokenServiceGetUsageRequest, ctx: RequestContext[APITokenServiceGetUsageRequest, APITokenServiceGetUsageResponse], /) -> APITokenServiceGetUsageResponse:
        """
        GetUsage returns a readonly snapshot of a token's current rate-
        limit consumption — current/previous bucket counters, the
        weighted sliding-window count, and when the window rolls. Does
        NOT bump the bucket; safe to poll from a Web UI dashboard.
        Returns NOT_FOUND when the token id doesn't exist.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class APITokenServiceASGIApplication(ConnectASGIApplication[APITokenService]):
    def __init__(
        self,
        service: APITokenService | AsyncGenerator[APITokenService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/paladin.admin.v1.APITokenService/Create": Endpoint.unary(
                    method=MethodInfo(
                        name="Create",
                        service_name="paladin.admin.v1.APITokenService",
                        input=APITokenServiceCreateRequest,
                        output=APITokenServiceCreateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create,
                ),
                "/paladin.admin.v1.APITokenService/Revoke": Endpoint.unary(
                    method=MethodInfo(
                        name="Revoke",
                        service_name="paladin.admin.v1.APITokenService",
                        input=APITokenServiceRevokeRequest,
                        output=APITokenServiceRevokeResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.revoke,
                ),
                "/paladin.admin.v1.APITokenService/List": Endpoint.unary(
                    method=MethodInfo(
                        name="List",
                        service_name="paladin.admin.v1.APITokenService",
                        input=APITokenServiceListRequest,
                        output=APITokenServiceListResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list,
                ),
                "/paladin.admin.v1.APITokenService/GetSelf": Endpoint.unary(
                    method=MethodInfo(
                        name="GetSelf",
                        service_name="paladin.admin.v1.APITokenService",
                        input=APITokenServiceGetSelfRequest,
                        output=APITokenServiceGetSelfResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_self,
                ),
                "/paladin.admin.v1.APITokenService/GetUsage": Endpoint.unary(
                    method=MethodInfo(
                        name="GetUsage",
                        service_name="paladin.admin.v1.APITokenService",
                        input=APITokenServiceGetUsageRequest,
                        output=APITokenServiceGetUsageResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_usage,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/paladin.admin.v1.APITokenService"


class APITokenServiceClient(ConnectClient):
    """
    APITokenService manages hashed-bearer M2M tokens (`paladin_pat_…`). Distinct
    from capability tokens (CapabilityService) which serve agent-runtime
    federation in JWT format. API tokens are long-lived service-to-
    service credentials that follow the Hatchet / GitHub PATs / Stripe
    pattern: stored as argon2id PHC hash, plaintext returned exactly
    once at creation.

    Naming: request / response types use the `APITokenService<Method>`
    prefix because the bare verbs (Create / Revoke / List) collide with
    other admin services in the same proto package — buf STANDARD lint
    requires the prefix when method names alone aren't unique.
    """
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    async def create(
        self,
        request: APITokenServiceCreateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> APITokenServiceCreateResponse:
        """
        Create mints a new API token. Plaintext is returned exactly once
        in `token`; afterwards only the hash is persisted. Caller MUST
        treat the returned `token` as a write-once secret — the service
        can't recover it.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Create",
                service_name="paladin.admin.v1.APITokenService",
                input=APITokenServiceCreateRequest,
                output=APITokenServiceCreateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def revoke(
        self,
        request: APITokenServiceRevokeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> APITokenServiceRevokeResponse:
        """
        Revoke marks a token as revoked at NOW(). Idempotent — re-revoking
        a revoked token is a no-op. Cannot be undone; caller mints a new
        one to replace.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Revoke",
                service_name="paladin.admin.v1.APITokenService",
                input=APITokenServiceRevokeRequest,
                output=APITokenServiceRevokeResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list(
        self,
        request: APITokenServiceListRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> APITokenServiceListResponse:
        """
        List enumerates tokens for a tenant. Paginated cursor-style. The
        `token_hash` is never returned; callers see metadata only.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="List",
                service_name="paladin.admin.v1.APITokenService",
                input=APITokenServiceListRequest,
                output=APITokenServiceListResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def get_self(
        self,
        request: APITokenServiceGetSelfRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> APITokenServiceGetSelfResponse:
        """
        GetSelf introspects the API token attached to the calling request,
        if any. Returns NOT_FOUND when the request was authenticated via
        JWT or capability instead of an API token. Used by clients that
        want to display "you are authenticated as token X" without an
        out-of-band lookup.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetSelf",
                service_name="paladin.admin.v1.APITokenService",
                input=APITokenServiceGetSelfRequest,
                output=APITokenServiceGetSelfResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def get_usage(
        self,
        request: APITokenServiceGetUsageRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> APITokenServiceGetUsageResponse:
        """
        GetUsage returns a readonly snapshot of a token's current rate-
        limit consumption — current/previous bucket counters, the
        weighted sliding-window count, and when the window rolls. Does
        NOT bump the bucket; safe to poll from a Web UI dashboard.
        Returns NOT_FOUND when the token id doesn't exist.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetUsage",
                service_name="paladin.admin.v1.APITokenService",
                input=APITokenServiceGetUsageRequest,
                output=APITokenServiceGetUsageResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

class APITokenServiceSync(Protocol):
    """
    APITokenService manages hashed-bearer M2M tokens (`paladin_pat_…`). Distinct
    from capability tokens (CapabilityService) which serve agent-runtime
    federation in JWT format. API tokens are long-lived service-to-
    service credentials that follow the Hatchet / GitHub PATs / Stripe
    pattern: stored as argon2id PHC hash, plaintext returned exactly
    once at creation.

    Naming: request / response types use the `APITokenService<Method>`
    prefix because the bare verbs (Create / Revoke / List) collide with
    other admin services in the same proto package — buf STANDARD lint
    requires the prefix when method names alone aren't unique.
    """
    def create(self, request: APITokenServiceCreateRequest, ctx: RequestContext[APITokenServiceCreateRequest, APITokenServiceCreateResponse], /) -> APITokenServiceCreateResponse:
        """
        Create mints a new API token. Plaintext is returned exactly once
        in `token`; afterwards only the hash is persisted. Caller MUST
        treat the returned `token` as a write-once secret — the service
        can't recover it.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def revoke(self, request: APITokenServiceRevokeRequest, ctx: RequestContext[APITokenServiceRevokeRequest, APITokenServiceRevokeResponse], /) -> APITokenServiceRevokeResponse:
        """
        Revoke marks a token as revoked at NOW(). Idempotent — re-revoking
        a revoked token is a no-op. Cannot be undone; caller mints a new
        one to replace.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list(self, request: APITokenServiceListRequest, ctx: RequestContext[APITokenServiceListRequest, APITokenServiceListResponse], /) -> APITokenServiceListResponse:
        """
        List enumerates tokens for a tenant. Paginated cursor-style. The
        `token_hash` is never returned; callers see metadata only.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_self(self, request: APITokenServiceGetSelfRequest, ctx: RequestContext[APITokenServiceGetSelfRequest, APITokenServiceGetSelfResponse], /) -> APITokenServiceGetSelfResponse:
        """
        GetSelf introspects the API token attached to the calling request,
        if any. Returns NOT_FOUND when the request was authenticated via
        JWT or capability instead of an API token. Used by clients that
        want to display "you are authenticated as token X" without an
        out-of-band lookup.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_usage(self, request: APITokenServiceGetUsageRequest, ctx: RequestContext[APITokenServiceGetUsageRequest, APITokenServiceGetUsageResponse], /) -> APITokenServiceGetUsageResponse:
        """
        GetUsage returns a readonly snapshot of a token's current rate-
        limit consumption — current/previous bucket counters, the
        weighted sliding-window count, and when the window rolls. Does
        NOT bump the bucket; safe to poll from a Web UI dashboard.
        Returns NOT_FOUND when the token id doesn't exist.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class APITokenServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: APITokenServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            endpoints={
                "/paladin.admin.v1.APITokenService/Create": EndpointSync.unary(
                    method=MethodInfo(
                        name="Create",
                        service_name="paladin.admin.v1.APITokenService",
                        input=APITokenServiceCreateRequest,
                        output=APITokenServiceCreateResponse,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create,
                ),
                "/paladin.admin.v1.APITokenService/Revoke": EndpointSync.unary(
                    method=MethodInfo(
                        name="Revoke",
                        service_name="paladin.admin.v1.APITokenService",
                        input=APITokenServiceRevokeRequest,
                        output=APITokenServiceRevokeResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.revoke,
                ),
                "/paladin.admin.v1.APITokenService/List": EndpointSync.unary(
                    method=MethodInfo(
                        name="List",
                        service_name="paladin.admin.v1.APITokenService",
                        input=APITokenServiceListRequest,
                        output=APITokenServiceListResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list,
                ),
                "/paladin.admin.v1.APITokenService/GetSelf": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetSelf",
                        service_name="paladin.admin.v1.APITokenService",
                        input=APITokenServiceGetSelfRequest,
                        output=APITokenServiceGetSelfResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_self,
                ),
                "/paladin.admin.v1.APITokenService/GetUsage": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetUsage",
                        service_name="paladin.admin.v1.APITokenService",
                        input=APITokenServiceGetUsageRequest,
                        output=APITokenServiceGetUsageResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_usage,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/paladin.admin.v1.APITokenService"


class APITokenServiceClientSync(ConnectClientSync):
    """
    APITokenService manages hashed-bearer M2M tokens (`paladin_pat_…`). Distinct
    from capability tokens (CapabilityService) which serve agent-runtime
    federation in JWT format. API tokens are long-lived service-to-
    service credentials that follow the Hatchet / GitHub PATs / Stripe
    pattern: stored as argon2id PHC hash, plaintext returned exactly
    once at creation.

    Naming: request / response types use the `APITokenService<Method>`
    prefix because the bare verbs (Create / Revoke / List) collide with
    other admin services in the same proto package — buf STANDARD lint
    requires the prefix when method names alone aren't unique.
    """
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[InterceptorSync] = (),
        http_client: SyncClient | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    def create(
        self,
        request: APITokenServiceCreateRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> APITokenServiceCreateResponse:
        """
        Create mints a new API token. Plaintext is returned exactly once
        in `token`; afterwards only the hash is persisted. Caller MUST
        treat the returned `token` as a write-once secret — the service
        can't recover it.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Create",
                service_name="paladin.admin.v1.APITokenService",
                input=APITokenServiceCreateRequest,
                output=APITokenServiceCreateResponse,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def revoke(
        self,
        request: APITokenServiceRevokeRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> APITokenServiceRevokeResponse:
        """
        Revoke marks a token as revoked at NOW(). Idempotent — re-revoking
        a revoked token is a no-op. Cannot be undone; caller mints a new
        one to replace.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="Revoke",
                service_name="paladin.admin.v1.APITokenService",
                input=APITokenServiceRevokeRequest,
                output=APITokenServiceRevokeResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list(
        self,
        request: APITokenServiceListRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> APITokenServiceListResponse:
        """
        List enumerates tokens for a tenant. Paginated cursor-style. The
        `token_hash` is never returned; callers see metadata only.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="List",
                service_name="paladin.admin.v1.APITokenService",
                input=APITokenServiceListRequest,
                output=APITokenServiceListResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def get_self(
        self,
        request: APITokenServiceGetSelfRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> APITokenServiceGetSelfResponse:
        """
        GetSelf introspects the API token attached to the calling request,
        if any. Returns NOT_FOUND when the request was authenticated via
        JWT or capability instead of an API token. Used by clients that
        want to display "you are authenticated as token X" without an
        out-of-band lookup.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetSelf",
                service_name="paladin.admin.v1.APITokenService",
                input=APITokenServiceGetSelfRequest,
                output=APITokenServiceGetSelfResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def get_usage(
        self,
        request: APITokenServiceGetUsageRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> APITokenServiceGetUsageResponse:
        """
        GetUsage returns a readonly snapshot of a token's current rate-
        limit consumption — current/previous bucket counters, the
        weighted sliding-window count, and when the window rolls. Does
        NOT bump the bucket; safe to poll from a Web UI dashboard.
        Returns NOT_FOUND when the token id doesn't exist.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetUsage",
                service_name="paladin.admin.v1.APITokenService",
                input=APITokenServiceGetUsageRequest,
                output=APITokenServiceGetUsageResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
