# Generated from paladin/admin/v1/bucket_service.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.12.1 with parameter "protobuf=google".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compat import google_protobuf_binary_codec, google_protobuf_codecs
from connectrpc.compression.gzip import GzipCompression
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.protocol import ProtocolType
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, DEFAULT_READ_MAX_BYTES, Endpoint, EndpointSync
from paladin.admin.v1.types_pb2 import Bucket
from pyqwest import Client, SyncClient

from .bucket_service_pb2 import CreateBucketRequest, DeleteBucketRequest, DeleteBucketResponse, GetBucketRequest, ListAccessibleBucketsRequest, ListBucketsRequest, ListBucketsResponse, SetBucketPolicyRequest, SetLifecycleRulesRequest, SetObjectLockRequest, SetReplicationRequest, SetVersioningRequest, UpdateBucketRequest

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext



_DEFAULT_CODECS = google_protobuf_codecs()
_PROTO_BINARY_CODEC = google_protobuf_binary_codec()
_GZIP_COMPRESSION = GzipCompression()

class BucketService(Protocol):
    """
    BucketService manages physical S3 buckets. Bucket admins create buckets
    and bind them to backends; tenant admins consume them via Collection.
    """
    async def create_bucket(self, request: CreateBucketRequest, ctx: RequestContext[CreateBucketRequest, Bucket], /) -> Bucket:
        """
        CreateBucket registers a bucket on a backend. It does not create the
        physical bucket — see StorageBootstrapService for that.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_bucket(self, request: GetBucketRequest, ctx: RequestContext[GetBucketRequest, Bucket], /) -> Bucket:
        """
        GetBucket returns the bucket, including its versioning, replication and
        object-lock configuration.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def update_bucket(self, request: UpdateBucketRequest, ctx: RequestContext[UpdateBucketRequest, Bucket], /) -> Bucket:
        """
        UpdateBucket applies update_mask; resource_version is required. Versioning,
        replication and object lock have their own RPCs — they are not settable
        through this one.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def delete_bucket(self, request: DeleteBucketRequest, ctx: RequestContext[DeleteBucketRequest, DeleteBucketResponse], /) -> DeleteBucketResponse:
        """
        DeleteBucket removes the registration. delete_on_backend=true also erases
        the physical bucket and its contents, which is irreversible.
        skip_version_check waives the OCC guard and nothing else — the two flags
        are independent, and only one of them destroys anything.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_buckets(self, request: ListBucketsRequest, ctx: RequestContext[ListBucketsRequest, ListBucketsResponse], /) -> ListBucketsResponse:
        """
        ListBuckets returns buckets across every backend, optionally filtered to
        one.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def set_bucket_policy(self, request: SetBucketPolicyRequest, ctx: RequestContext[SetBucketPolicyRequest, Bucket], /) -> Bucket:
        """
        SetBucketPolicy sets/replaces the Cedar policy text. Validated synchronously.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def set_lifecycle_rules(self, request: SetLifecycleRulesRequest, ctx: RequestContext[SetLifecycleRulesRequest, Bucket], /) -> Bucket:
        """
        SetLifecycleRules / SetObjectLock / SetVersioning / SetReplication are
        single-purpose RPCs to keep audit log entries focused.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def set_object_lock(self, request: SetObjectLockRequest, ctx: RequestContext[SetObjectLockRequest, Bucket], /) -> Bucket:
        """
        SetObjectLock configures WORM retention for the bucket (ADR-0013). Enabling
        it is one-way: a bucket with object lock on cannot have it turned off,
        because objects already written under it rely on the guarantee.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def set_versioning(self, request: SetVersioningRequest, ctx: RequestContext[SetVersioningRequest, Bucket], /) -> Bucket:
        """
        SetVersioning turns object versioning on or off. Turning it off keeps the
        versions already recorded — it stops new ones being written.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def set_replication(self, request: SetReplicationRequest, ctx: RequestContext[SetReplicationRequest, Bucket], /) -> Bucket:
        """
        SetReplication configures asynchronous copy to a second backend. Existing
        objects are not backfilled; replication applies from the moment it is
        enabled.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_accessible_buckets(self, request: ListAccessibleBucketsRequest, ctx: RequestContext[ListAccessibleBucketsRequest, ListBucketsResponse], /) -> ListBucketsResponse:
        """
        ListAccessibleBuckets is callable by tenant admins. Returns only buckets
        the caller's principal/scopes are allowed to bind Collections to.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class BucketServiceASGIApplication(ConnectASGIApplication[BucketService]):
    def __init__(
        self,
        service: BucketService | AsyncGenerator[BucketService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/paladin.admin.v1.BucketService/CreateBucket": Endpoint.unary(
                    method=MethodInfo(
                        name="CreateBucket",
                        service_name="paladin.admin.v1.BucketService",
                        input=CreateBucketRequest,
                        output=Bucket,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=svc.create_bucket,
                ),
                "/paladin.admin.v1.BucketService/GetBucket": Endpoint.unary(
                    method=MethodInfo(
                        name="GetBucket",
                        service_name="paladin.admin.v1.BucketService",
                        input=GetBucketRequest,
                        output=Bucket,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_bucket,
                ),
                "/paladin.admin.v1.BucketService/UpdateBucket": Endpoint.unary(
                    method=MethodInfo(
                        name="UpdateBucket",
                        service_name="paladin.admin.v1.BucketService",
                        input=UpdateBucketRequest,
                        output=Bucket,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.update_bucket,
                ),
                "/paladin.admin.v1.BucketService/DeleteBucket": Endpoint.unary(
                    method=MethodInfo(
                        name="DeleteBucket",
                        service_name="paladin.admin.v1.BucketService",
                        input=DeleteBucketRequest,
                        output=DeleteBucketResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.delete_bucket,
                ),
                "/paladin.admin.v1.BucketService/ListBuckets": Endpoint.unary(
                    method=MethodInfo(
                        name="ListBuckets",
                        service_name="paladin.admin.v1.BucketService",
                        input=ListBucketsRequest,
                        output=ListBucketsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_buckets,
                ),
                "/paladin.admin.v1.BucketService/SetBucketPolicy": Endpoint.unary(
                    method=MethodInfo(
                        name="SetBucketPolicy",
                        service_name="paladin.admin.v1.BucketService",
                        input=SetBucketPolicyRequest,
                        output=Bucket,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.set_bucket_policy,
                ),
                "/paladin.admin.v1.BucketService/SetLifecycleRules": Endpoint.unary(
                    method=MethodInfo(
                        name="SetLifecycleRules",
                        service_name="paladin.admin.v1.BucketService",
                        input=SetLifecycleRulesRequest,
                        output=Bucket,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.set_lifecycle_rules,
                ),
                "/paladin.admin.v1.BucketService/SetObjectLock": Endpoint.unary(
                    method=MethodInfo(
                        name="SetObjectLock",
                        service_name="paladin.admin.v1.BucketService",
                        input=SetObjectLockRequest,
                        output=Bucket,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.set_object_lock,
                ),
                "/paladin.admin.v1.BucketService/SetVersioning": Endpoint.unary(
                    method=MethodInfo(
                        name="SetVersioning",
                        service_name="paladin.admin.v1.BucketService",
                        input=SetVersioningRequest,
                        output=Bucket,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.set_versioning,
                ),
                "/paladin.admin.v1.BucketService/SetReplication": Endpoint.unary(
                    method=MethodInfo(
                        name="SetReplication",
                        service_name="paladin.admin.v1.BucketService",
                        input=SetReplicationRequest,
                        output=Bucket,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=svc.set_replication,
                ),
                "/paladin.admin.v1.BucketService/ListAccessibleBuckets": Endpoint.unary(
                    method=MethodInfo(
                        name="ListAccessibleBuckets",
                        service_name="paladin.admin.v1.BucketService",
                        input=ListAccessibleBucketsRequest,
                        output=ListBucketsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_accessible_buckets,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/paladin.admin.v1.BucketService"


class BucketServiceClient(ConnectClient):
    """
    BucketService manages physical S3 buckets. Bucket admins create buckets
    and bind them to backends; tenant admins consume them via Collection.
    """
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    async def create_bucket(
        self,
        request: CreateBucketRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Bucket:
        """
        CreateBucket registers a bucket on a backend. It does not create the
        physical bucket — see StorageBootstrapService for that.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateBucket",
                service_name="paladin.admin.v1.BucketService",
                input=CreateBucketRequest,
                output=Bucket,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def get_bucket(
        self,
        request: GetBucketRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> Bucket:
        """
        GetBucket returns the bucket, including its versioning, replication and
        object-lock configuration.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetBucket",
                service_name="paladin.admin.v1.BucketService",
                input=GetBucketRequest,
                output=Bucket,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def update_bucket(
        self,
        request: UpdateBucketRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Bucket:
        """
        UpdateBucket applies update_mask; resource_version is required. Versioning,
        replication and object lock have their own RPCs — they are not settable
        through this one.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateBucket",
                service_name="paladin.admin.v1.BucketService",
                input=UpdateBucketRequest,
                output=Bucket,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def delete_bucket(
        self,
        request: DeleteBucketRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> DeleteBucketResponse:
        """
        DeleteBucket removes the registration. delete_on_backend=true also erases
        the physical bucket and its contents, which is irreversible.
        skip_version_check waives the OCC guard and nothing else — the two flags
        are independent, and only one of them destroys anything.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteBucket",
                service_name="paladin.admin.v1.BucketService",
                input=DeleteBucketRequest,
                output=DeleteBucketResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_buckets(
        self,
        request: ListBucketsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListBucketsResponse:
        """
        ListBuckets returns buckets across every backend, optionally filtered to
        one.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListBuckets",
                service_name="paladin.admin.v1.BucketService",
                input=ListBucketsRequest,
                output=ListBucketsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def set_bucket_policy(
        self,
        request: SetBucketPolicyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Bucket:
        """
        SetBucketPolicy sets/replaces the Cedar policy text. Validated synchronously.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SetBucketPolicy",
                service_name="paladin.admin.v1.BucketService",
                input=SetBucketPolicyRequest,
                output=Bucket,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def set_lifecycle_rules(
        self,
        request: SetLifecycleRulesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Bucket:
        """
        SetLifecycleRules / SetObjectLock / SetVersioning / SetReplication are
        single-purpose RPCs to keep audit log entries focused.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SetLifecycleRules",
                service_name="paladin.admin.v1.BucketService",
                input=SetLifecycleRulesRequest,
                output=Bucket,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def set_object_lock(
        self,
        request: SetObjectLockRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Bucket:
        """
        SetObjectLock configures WORM retention for the bucket (ADR-0013). Enabling
        it is one-way: a bucket with object lock on cannot have it turned off,
        because objects already written under it rely on the guarantee.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SetObjectLock",
                service_name="paladin.admin.v1.BucketService",
                input=SetObjectLockRequest,
                output=Bucket,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def set_versioning(
        self,
        request: SetVersioningRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Bucket:
        """
        SetVersioning turns object versioning on or off. Turning it off keeps the
        versions already recorded — it stops new ones being written.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SetVersioning",
                service_name="paladin.admin.v1.BucketService",
                input=SetVersioningRequest,
                output=Bucket,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def set_replication(
        self,
        request: SetReplicationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Bucket:
        """
        SetReplication configures asynchronous copy to a second backend. Existing
        objects are not backfilled; replication applies from the moment it is
        enabled.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SetReplication",
                service_name="paladin.admin.v1.BucketService",
                input=SetReplicationRequest,
                output=Bucket,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )

    async def list_accessible_buckets(
        self,
        request: ListAccessibleBucketsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListBucketsResponse:
        """
        ListAccessibleBuckets is callable by tenant admins. Returns only buckets
        the caller's principal/scopes are allowed to bind Collections to.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListAccessibleBuckets",
                service_name="paladin.admin.v1.BucketService",
                input=ListAccessibleBucketsRequest,
                output=ListBucketsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

class BucketServiceSync(Protocol):
    """
    BucketService manages physical S3 buckets. Bucket admins create buckets
    and bind them to backends; tenant admins consume them via Collection.
    """
    def create_bucket(self, request: CreateBucketRequest, ctx: RequestContext[CreateBucketRequest, Bucket], /) -> Bucket:
        """
        CreateBucket registers a bucket on a backend. It does not create the
        physical bucket — see StorageBootstrapService for that.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_bucket(self, request: GetBucketRequest, ctx: RequestContext[GetBucketRequest, Bucket], /) -> Bucket:
        """
        GetBucket returns the bucket, including its versioning, replication and
        object-lock configuration.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def update_bucket(self, request: UpdateBucketRequest, ctx: RequestContext[UpdateBucketRequest, Bucket], /) -> Bucket:
        """
        UpdateBucket applies update_mask; resource_version is required. Versioning,
        replication and object lock have their own RPCs — they are not settable
        through this one.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def delete_bucket(self, request: DeleteBucketRequest, ctx: RequestContext[DeleteBucketRequest, DeleteBucketResponse], /) -> DeleteBucketResponse:
        """
        DeleteBucket removes the registration. delete_on_backend=true also erases
        the physical bucket and its contents, which is irreversible.
        skip_version_check waives the OCC guard and nothing else — the two flags
        are independent, and only one of them destroys anything.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_buckets(self, request: ListBucketsRequest, ctx: RequestContext[ListBucketsRequest, ListBucketsResponse], /) -> ListBucketsResponse:
        """
        ListBuckets returns buckets across every backend, optionally filtered to
        one.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def set_bucket_policy(self, request: SetBucketPolicyRequest, ctx: RequestContext[SetBucketPolicyRequest, Bucket], /) -> Bucket:
        """
        SetBucketPolicy sets/replaces the Cedar policy text. Validated synchronously.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def set_lifecycle_rules(self, request: SetLifecycleRulesRequest, ctx: RequestContext[SetLifecycleRulesRequest, Bucket], /) -> Bucket:
        """
        SetLifecycleRules / SetObjectLock / SetVersioning / SetReplication are
        single-purpose RPCs to keep audit log entries focused.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def set_object_lock(self, request: SetObjectLockRequest, ctx: RequestContext[SetObjectLockRequest, Bucket], /) -> Bucket:
        """
        SetObjectLock configures WORM retention for the bucket (ADR-0013). Enabling
        it is one-way: a bucket with object lock on cannot have it turned off,
        because objects already written under it rely on the guarantee.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def set_versioning(self, request: SetVersioningRequest, ctx: RequestContext[SetVersioningRequest, Bucket], /) -> Bucket:
        """
        SetVersioning turns object versioning on or off. Turning it off keeps the
        versions already recorded — it stops new ones being written.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def set_replication(self, request: SetReplicationRequest, ctx: RequestContext[SetReplicationRequest, Bucket], /) -> Bucket:
        """
        SetReplication configures asynchronous copy to a second backend. Existing
        objects are not backfilled; replication applies from the moment it is
        enabled.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_accessible_buckets(self, request: ListAccessibleBucketsRequest, ctx: RequestContext[ListAccessibleBucketsRequest, ListBucketsResponse], /) -> ListBucketsResponse:
        """
        ListAccessibleBuckets is callable by tenant admins. Returns only buckets
        the caller's principal/scopes are allowed to bind Collections to.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class BucketServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: BucketServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            endpoints={
                "/paladin.admin.v1.BucketService/CreateBucket": EndpointSync.unary(
                    method=MethodInfo(
                        name="CreateBucket",
                        service_name="paladin.admin.v1.BucketService",
                        input=CreateBucketRequest,
                        output=Bucket,
                        idempotency_level=IdempotencyLevel.UNKNOWN,
                    ),
                    function=service.create_bucket,
                ),
                "/paladin.admin.v1.BucketService/GetBucket": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetBucket",
                        service_name="paladin.admin.v1.BucketService",
                        input=GetBucketRequest,
                        output=Bucket,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_bucket,
                ),
                "/paladin.admin.v1.BucketService/UpdateBucket": EndpointSync.unary(
                    method=MethodInfo(
                        name="UpdateBucket",
                        service_name="paladin.admin.v1.BucketService",
                        input=UpdateBucketRequest,
                        output=Bucket,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.update_bucket,
                ),
                "/paladin.admin.v1.BucketService/DeleteBucket": EndpointSync.unary(
                    method=MethodInfo(
                        name="DeleteBucket",
                        service_name="paladin.admin.v1.BucketService",
                        input=DeleteBucketRequest,
                        output=DeleteBucketResponse,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.delete_bucket,
                ),
                "/paladin.admin.v1.BucketService/ListBuckets": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListBuckets",
                        service_name="paladin.admin.v1.BucketService",
                        input=ListBucketsRequest,
                        output=ListBucketsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_buckets,
                ),
                "/paladin.admin.v1.BucketService/SetBucketPolicy": EndpointSync.unary(
                    method=MethodInfo(
                        name="SetBucketPolicy",
                        service_name="paladin.admin.v1.BucketService",
                        input=SetBucketPolicyRequest,
                        output=Bucket,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.set_bucket_policy,
                ),
                "/paladin.admin.v1.BucketService/SetLifecycleRules": EndpointSync.unary(
                    method=MethodInfo(
                        name="SetLifecycleRules",
                        service_name="paladin.admin.v1.BucketService",
                        input=SetLifecycleRulesRequest,
                        output=Bucket,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.set_lifecycle_rules,
                ),
                "/paladin.admin.v1.BucketService/SetObjectLock": EndpointSync.unary(
                    method=MethodInfo(
                        name="SetObjectLock",
                        service_name="paladin.admin.v1.BucketService",
                        input=SetObjectLockRequest,
                        output=Bucket,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.set_object_lock,
                ),
                "/paladin.admin.v1.BucketService/SetVersioning": EndpointSync.unary(
                    method=MethodInfo(
                        name="SetVersioning",
                        service_name="paladin.admin.v1.BucketService",
                        input=SetVersioningRequest,
                        output=Bucket,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.set_versioning,
                ),
                "/paladin.admin.v1.BucketService/SetReplication": EndpointSync.unary(
                    method=MethodInfo(
                        name="SetReplication",
                        service_name="paladin.admin.v1.BucketService",
                        input=SetReplicationRequest,
                        output=Bucket,
                        idempotency_level=IdempotencyLevel.IDEMPOTENT,
                    ),
                    function=service.set_replication,
                ),
                "/paladin.admin.v1.BucketService/ListAccessibleBuckets": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListAccessibleBuckets",
                        service_name="paladin.admin.v1.BucketService",
                        input=ListAccessibleBucketsRequest,
                        output=ListBucketsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_accessible_buckets,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/paladin.admin.v1.BucketService"


class BucketServiceClientSync(ConnectClientSync):
    """
    BucketService manages physical S3 buckets. Bucket admins create buckets
    and bind them to backends; tenant admins consume them via Collection.
    """
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[InterceptorSync] = (),
        http_client: SyncClient | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    def create_bucket(
        self,
        request: CreateBucketRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Bucket:
        """
        CreateBucket registers a bucket on a backend. It does not create the
        physical bucket — see StorageBootstrapService for that.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="CreateBucket",
                service_name="paladin.admin.v1.BucketService",
                input=CreateBucketRequest,
                output=Bucket,
                idempotency_level=IdempotencyLevel.UNKNOWN,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def get_bucket(
        self,
        request: GetBucketRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> Bucket:
        """
        GetBucket returns the bucket, including its versioning, replication and
        object-lock configuration.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetBucket",
                service_name="paladin.admin.v1.BucketService",
                input=GetBucketRequest,
                output=Bucket,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def update_bucket(
        self,
        request: UpdateBucketRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Bucket:
        """
        UpdateBucket applies update_mask; resource_version is required. Versioning,
        replication and object lock have their own RPCs — they are not settable
        through this one.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="UpdateBucket",
                service_name="paladin.admin.v1.BucketService",
                input=UpdateBucketRequest,
                output=Bucket,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def delete_bucket(
        self,
        request: DeleteBucketRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> DeleteBucketResponse:
        """
        DeleteBucket removes the registration. delete_on_backend=true also erases
        the physical bucket and its contents, which is irreversible.
        skip_version_check waives the OCC guard and nothing else — the two flags
        are independent, and only one of them destroys anything.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="DeleteBucket",
                service_name="paladin.admin.v1.BucketService",
                input=DeleteBucketRequest,
                output=DeleteBucketResponse,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_buckets(
        self,
        request: ListBucketsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListBucketsResponse:
        """
        ListBuckets returns buckets across every backend, optionally filtered to
        one.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListBuckets",
                service_name="paladin.admin.v1.BucketService",
                input=ListBucketsRequest,
                output=ListBucketsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def set_bucket_policy(
        self,
        request: SetBucketPolicyRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Bucket:
        """
        SetBucketPolicy sets/replaces the Cedar policy text. Validated synchronously.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SetBucketPolicy",
                service_name="paladin.admin.v1.BucketService",
                input=SetBucketPolicyRequest,
                output=Bucket,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def set_lifecycle_rules(
        self,
        request: SetLifecycleRulesRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Bucket:
        """
        SetLifecycleRules / SetObjectLock / SetVersioning / SetReplication are
        single-purpose RPCs to keep audit log entries focused.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SetLifecycleRules",
                service_name="paladin.admin.v1.BucketService",
                input=SetLifecycleRulesRequest,
                output=Bucket,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def set_object_lock(
        self,
        request: SetObjectLockRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Bucket:
        """
        SetObjectLock configures WORM retention for the bucket (ADR-0013). Enabling
        it is one-way: a bucket with object lock on cannot have it turned off,
        because objects already written under it rely on the guarantee.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SetObjectLock",
                service_name="paladin.admin.v1.BucketService",
                input=SetObjectLockRequest,
                output=Bucket,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def set_versioning(
        self,
        request: SetVersioningRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Bucket:
        """
        SetVersioning turns object versioning on or off. Turning it off keeps the
        versions already recorded — it stops new ones being written.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SetVersioning",
                service_name="paladin.admin.v1.BucketService",
                input=SetVersioningRequest,
                output=Bucket,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def set_replication(
        self,
        request: SetReplicationRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
    ) -> Bucket:
        """
        SetReplication configures asynchronous copy to a second backend. Existing
        objects are not backfilled; replication applies from the moment it is
        enabled.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="SetReplication",
                service_name="paladin.admin.v1.BucketService",
                input=SetReplicationRequest,
                output=Bucket,
                idempotency_level=IdempotencyLevel.IDEMPOTENT,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
        )
    def list_accessible_buckets(
        self,
        request: ListAccessibleBucketsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListBucketsResponse:
        """
        ListAccessibleBuckets is callable by tenant admins. Returns only buckets
        the caller's principal/scopes are allowed to bind Collections to.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListAccessibleBuckets",
                service_name="paladin.admin.v1.BucketService",
                input=ListAccessibleBucketsRequest,
                output=ListBucketsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
