# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: paladin/admin/v1/cel_service.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'paladin/admin/v1/cel_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from buf.validate import validate_pb2 as buf_dot_validate_dot_validate__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"paladin/admin/v1/cel_service.proto\x12\x10paladin.admin.v1\x1a\x1b\x62uf/validate/validate.proto\"A\n\x12ValidateCELRequest\x12\x17\n\x06schema\x18\x01 \x01(\tB\x07\xbaH\x04r\x02\x10\x01\x12\x12\n\nexpression\x18\x02 \x01(\t\"S\n\x13ValidateCELResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0c\n\x04line\x18\x03 \x01(\x05\x12\x0e\n\x06\x63olumn\x18\x04 \x01(\x05\x32j\n\nCELService\x12\\\n\x08Validate\x12$.paladin.admin.v1.ValidateCELRequest\x1a%.paladin.admin.v1.ValidateCELResponse\"\x03\x90\x02\x01\x42LZJgithub.com/oleg-tkachuk/paladin/sdk/go/gen/paladin/admin/v1;paladinadminv1b\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'paladin.admin.v1.cel_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'ZJgithub.com/oleg-tkachuk/paladin/sdk/go/gen/paladin/admin/v1;paladinadminv1'
  _globals['_VALIDATECELREQUEST'].fields_by_name['schema']._loaded_options = None
  _globals['_VALIDATECELREQUEST'].fields_by_name['schema']._serialized_options = b'\272H\004r\002\020\001'
  _globals['_CELSERVICE'].methods_by_name['Validate']._loaded_options = None
  _globals['_CELSERVICE'].methods_by_name['Validate']._serialized_options = b'\220\002\001'
  _globals['_VALIDATECELREQUEST']._serialized_start=85
  _globals['_VALIDATECELREQUEST']._serialized_end=150
  _globals['_VALIDATECELRESPONSE']._serialized_start=152
  _globals['_VALIDATECELRESPONSE']._serialized_end=235
  _globals['_CELSERVICE']._serialized_start=237
  _globals['_CELSERVICE']._serialized_end=343
# @@protoc_insertion_point(module_scope)
