# Generated from paladin/admin/v1/system_service.proto. DO NOT EDIT.
# Generated by protoc-gen-connectrpc-py v0.12.1 with parameter "protobuf=google".
# ruff: noqa: PGH004
# ruff: noqa
# fmt: off

from __future__ import annotations

from typing import Protocol, TYPE_CHECKING

from connectrpc.client import ConnectClient, ConnectClientSync
from connectrpc.code import Code
from connectrpc.compat import google_protobuf_binary_codec, google_protobuf_codecs
from connectrpc.compression.gzip import GzipCompression
from connectrpc.errors import ConnectError
from connectrpc.method import IdempotencyLevel, MethodInfo
from connectrpc.protocol import ProtocolType
from connectrpc.server import ConnectASGIApplication, ConnectWSGIApplication, DEFAULT_READ_MAX_BYTES, Endpoint, EndpointSync
from pyqwest import Client, SyncClient

from .system_service_pb2 import GetConfigRequest, GetConfigResponse, GetDispatcherStatsRequest, GetDispatcherStatsResponse, GetPlatformStatsRequest, GetPlatformStatsResponse, ListPlatformStatsTenantsRequest, ListPlatformStatsTenantsResponse

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator, Iterable, Mapping

    from connectrpc.codec import Codec
    from connectrpc.compression import Compression
    from connectrpc.interceptor import Interceptor, InterceptorSync
    from connectrpc.request import Headers, RequestContext



_DEFAULT_CODECS = google_protobuf_codecs()
_PROTO_BINARY_CODEC = google_protobuf_binary_codec()
_GZIP_COMPRESSION = GzipCompression()

class SystemService(Protocol):
    """
    SystemService on the admin plane exposes operator-only diagnostics
    that contain redacted-but-sensitive configuration. Distinct from
    paladin.iam.v1.SystemService (which is open to any authenticated user
    for build/version/health) — admin SystemService is gated to
    platform.admin role so we can ship the running config without
    leaking shape to regular tenants.
    """
    async def get_config(self, request: GetConfigRequest, ctx: RequestContext[GetConfigRequest, GetConfigResponse], /) -> GetConfigResponse:
        """
        GetConfig returns the running control-plane configuration as a
        single YAML blob with all secrets replaced by "***". The shape
        matches the on-disk config.yaml exactly so an operator can diff
        what's loaded against what's checked in. Cheap; no DB touch.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_dispatcher_stats(self, request: GetDispatcherStatsRequest, ctx: RequestContext[GetDispatcherStatsRequest, GetDispatcherStatsResponse], /) -> GetDispatcherStatsResponse:
        """
        GetDispatcherStats returns the event dispatcher's operator view:
        global delivery-queue depth plus a per-subscription breakdown of
        stuck work (pending/failed counts + the latest error). The admin
        plane PROXIES the dispatcher pod's ops endpoint — the stats are
        computed there because event_deliveries is RLS'd per tenant and
        only the dispatcher's BYPASSRLS pool sees the cross-tenant whole.
        Empty/zeroed response with `available=false` when the dispatcher
        ops endpoint is unconfigured or unreachable — the console renders
        "stats unavailable" rather than erroring.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def get_platform_stats(self, request: GetPlatformStatsRequest, ctx: RequestContext[GetPlatformStatsRequest, GetPlatformStatsResponse], /) -> GetPlatformStatsResponse:
        """
        GetPlatformStats returns a cross-tenant census of the control plane:
        how many tenants / storage backends / buckets / object keys / users
        exist and how they break down, plus per-tenant object counts by
        state. Backs the console's /stats page.

        Two data sources, one response (see GetPlatformStatsResponse): the
        control-plane counts come from this pod's pool; the object census
        is proxied from the worker pod's BYPASSRLS ops endpoint and
        degrades to `objects.available=false` when that is unconfigured or
        unreachable. Read-only, no audit row — it is a dashboard poll.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    async def list_platform_stats_tenants(self, request: ListPlatformStatsTenantsRequest, ctx: RequestContext[ListPlatformStatsTenantsRequest, ListPlatformStatsTenantsResponse], /) -> ListPlatformStatsTenantsResponse:
        """
        ListPlatformStatsTenants answers "whose" for one of the census counts
        GetPlatformStats flags for attention: the tenants behind it, biggest
        share first, paged like the object table. The counts are computed from
        the same predicates as the census, so a full walk plus `unattributed`
        adds up to the number GetPlatformStats reported at the same instant.

        Proxied from the worker like the census, but with no degraded answer:
        UNAVAILABLE when the worker leg is unconfigured or unreachable, because
        an empty list would read as "nobody". Read-only, no audit row.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class SystemServiceASGIApplication(ConnectASGIApplication[SystemService]):
    def __init__(
        self,
        service: SystemService | AsyncGenerator[SystemService],
        *,
        interceptors: Iterable[Interceptor] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            service=service,
            endpoints=lambda svc: {
                "/paladin.admin.v1.SystemService/GetConfig": Endpoint.unary(
                    method=MethodInfo(
                        name="GetConfig",
                        service_name="paladin.admin.v1.SystemService",
                        input=GetConfigRequest,
                        output=GetConfigResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_config,
                ),
                "/paladin.admin.v1.SystemService/GetDispatcherStats": Endpoint.unary(
                    method=MethodInfo(
                        name="GetDispatcherStats",
                        service_name="paladin.admin.v1.SystemService",
                        input=GetDispatcherStatsRequest,
                        output=GetDispatcherStatsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_dispatcher_stats,
                ),
                "/paladin.admin.v1.SystemService/GetPlatformStats": Endpoint.unary(
                    method=MethodInfo(
                        name="GetPlatformStats",
                        service_name="paladin.admin.v1.SystemService",
                        input=GetPlatformStatsRequest,
                        output=GetPlatformStatsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.get_platform_stats,
                ),
                "/paladin.admin.v1.SystemService/ListPlatformStatsTenants": Endpoint.unary(
                    method=MethodInfo(
                        name="ListPlatformStatsTenants",
                        service_name="paladin.admin.v1.SystemService",
                        input=ListPlatformStatsTenantsRequest,
                        output=ListPlatformStatsTenantsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=svc.list_platform_stats_tenants,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/paladin.admin.v1.SystemService"


class SystemServiceClient(ConnectClient):
    """
    SystemService on the admin plane exposes operator-only diagnostics
    that contain redacted-but-sensitive configuration. Distinct from
    paladin.iam.v1.SystemService (which is open to any authenticated user
    for build/version/health) — admin SystemService is gated to
    platform.admin role so we can ship the running config without
    leaking shape to regular tenants.
    """
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[Interceptor] = (),
        http_client: Client | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    async def get_config(
        self,
        request: GetConfigRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetConfigResponse:
        """
        GetConfig returns the running control-plane configuration as a
        single YAML blob with all secrets replaced by "***". The shape
        matches the on-disk config.yaml exactly so an operator can diff
        what's loaded against what's checked in. Cheap; no DB touch.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetConfig",
                service_name="paladin.admin.v1.SystemService",
                input=GetConfigRequest,
                output=GetConfigResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def get_dispatcher_stats(
        self,
        request: GetDispatcherStatsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetDispatcherStatsResponse:
        """
        GetDispatcherStats returns the event dispatcher's operator view:
        global delivery-queue depth plus a per-subscription breakdown of
        stuck work (pending/failed counts + the latest error). The admin
        plane PROXIES the dispatcher pod's ops endpoint — the stats are
        computed there because event_deliveries is RLS'd per tenant and
        only the dispatcher's BYPASSRLS pool sees the cross-tenant whole.
        Empty/zeroed response with `available=false` when the dispatcher
        ops endpoint is unconfigured or unreachable — the console renders
        "stats unavailable" rather than erroring.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetDispatcherStats",
                service_name="paladin.admin.v1.SystemService",
                input=GetDispatcherStatsRequest,
                output=GetDispatcherStatsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def get_platform_stats(
        self,
        request: GetPlatformStatsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetPlatformStatsResponse:
        """
        GetPlatformStats returns a cross-tenant census of the control plane:
        how many tenants / storage backends / buckets / object keys / users
        exist and how they break down, plus per-tenant object counts by
        state. Backs the console's /stats page.

        Two data sources, one response (see GetPlatformStatsResponse): the
        control-plane counts come from this pod's pool; the object census
        is proxied from the worker pod's BYPASSRLS ops endpoint and
        degrades to `objects.available=false` when that is unconfigured or
        unreachable. Read-only, no audit row — it is a dashboard poll.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetPlatformStats",
                service_name="paladin.admin.v1.SystemService",
                input=GetPlatformStatsRequest,
                output=GetPlatformStatsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

    async def list_platform_stats_tenants(
        self,
        request: ListPlatformStatsTenantsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListPlatformStatsTenantsResponse:
        """
        ListPlatformStatsTenants answers "whose" for one of the census counts
        GetPlatformStats flags for attention: the tenants behind it, biggest
        share first, paged like the object table. The counts are computed from
        the same predicates as the census, so a full walk plus `unattributed`
        adds up to the number GetPlatformStats reported at the same instant.

        Proxied from the worker like the census, but with no degraded answer:
        UNAVAILABLE when the worker leg is unconfigured or unreachable, because
        an empty list would read as "nobody". Read-only, no audit row.
        """
        return await self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListPlatformStatsTenants",
                service_name="paladin.admin.v1.SystemService",
                input=ListPlatformStatsTenantsRequest,
                output=ListPlatformStatsTenantsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )

class SystemServiceSync(Protocol):
    """
    SystemService on the admin plane exposes operator-only diagnostics
    that contain redacted-but-sensitive configuration. Distinct from
    paladin.iam.v1.SystemService (which is open to any authenticated user
    for build/version/health) — admin SystemService is gated to
    platform.admin role so we can ship the running config without
    leaking shape to regular tenants.
    """
    def get_config(self, request: GetConfigRequest, ctx: RequestContext[GetConfigRequest, GetConfigResponse], /) -> GetConfigResponse:
        """
        GetConfig returns the running control-plane configuration as a
        single YAML blob with all secrets replaced by "***". The shape
        matches the on-disk config.yaml exactly so an operator can diff
        what's loaded against what's checked in. Cheap; no DB touch.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_dispatcher_stats(self, request: GetDispatcherStatsRequest, ctx: RequestContext[GetDispatcherStatsRequest, GetDispatcherStatsResponse], /) -> GetDispatcherStatsResponse:
        """
        GetDispatcherStats returns the event dispatcher's operator view:
        global delivery-queue depth plus a per-subscription breakdown of
        stuck work (pending/failed counts + the latest error). The admin
        plane PROXIES the dispatcher pod's ops endpoint — the stats are
        computed there because event_deliveries is RLS'd per tenant and
        only the dispatcher's BYPASSRLS pool sees the cross-tenant whole.
        Empty/zeroed response with `available=false` when the dispatcher
        ops endpoint is unconfigured or unreachable — the console renders
        "stats unavailable" rather than erroring.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def get_platform_stats(self, request: GetPlatformStatsRequest, ctx: RequestContext[GetPlatformStatsRequest, GetPlatformStatsResponse], /) -> GetPlatformStatsResponse:
        """
        GetPlatformStats returns a cross-tenant census of the control plane:
        how many tenants / storage backends / buckets / object keys / users
        exist and how they break down, plus per-tenant object counts by
        state. Backs the console's /stats page.

        Two data sources, one response (see GetPlatformStatsResponse): the
        control-plane counts come from this pod's pool; the object census
        is proxied from the worker pod's BYPASSRLS ops endpoint and
        degrades to `objects.available=false` when that is unconfigured or
        unreachable. Read-only, no audit row — it is a dashboard poll.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')

    def list_platform_stats_tenants(self, request: ListPlatformStatsTenantsRequest, ctx: RequestContext[ListPlatformStatsTenantsRequest, ListPlatformStatsTenantsResponse], /) -> ListPlatformStatsTenantsResponse:
        """
        ListPlatformStatsTenants answers "whose" for one of the census counts
        GetPlatformStats flags for attention: the tenants behind it, biggest
        share first, paged like the object table. The counts are computed from
        the same predicates as the census, so a full walk plus `unattributed`
        adds up to the number GetPlatformStats reported at the same instant.

        Proxied from the worker like the census, but with no degraded answer:
        UNAVAILABLE when the worker leg is unconfigured or unreachable, because
        an empty list would read as "nobody". Read-only, no audit row.
        """
        raise ConnectError(Code.UNIMPLEMENTED, 'Not implemented')


class SystemServiceWSGIApplication(ConnectWSGIApplication):
    def __init__(
        self,
        service: SystemServiceSync,
        interceptors: Iterable[InterceptorSync] = (),
        read_max_bytes: int | None = DEFAULT_READ_MAX_BYTES,
        compressions: Iterable[Compression] | None = None,
        codecs: Iterable[Codec] | None = _DEFAULT_CODECS,
    ) -> None:
        super().__init__(
            endpoints={
                "/paladin.admin.v1.SystemService/GetConfig": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetConfig",
                        service_name="paladin.admin.v1.SystemService",
                        input=GetConfigRequest,
                        output=GetConfigResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_config,
                ),
                "/paladin.admin.v1.SystemService/GetDispatcherStats": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetDispatcherStats",
                        service_name="paladin.admin.v1.SystemService",
                        input=GetDispatcherStatsRequest,
                        output=GetDispatcherStatsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_dispatcher_stats,
                ),
                "/paladin.admin.v1.SystemService/GetPlatformStats": EndpointSync.unary(
                    method=MethodInfo(
                        name="GetPlatformStats",
                        service_name="paladin.admin.v1.SystemService",
                        input=GetPlatformStatsRequest,
                        output=GetPlatformStatsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.get_platform_stats,
                ),
                "/paladin.admin.v1.SystemService/ListPlatformStatsTenants": EndpointSync.unary(
                    method=MethodInfo(
                        name="ListPlatformStatsTenants",
                        service_name="paladin.admin.v1.SystemService",
                        input=ListPlatformStatsTenantsRequest,
                        output=ListPlatformStatsTenantsResponse,
                        idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
                    ),
                    function=service.list_platform_stats_tenants,
                ),
            },
            interceptors=interceptors,
            read_max_bytes=read_max_bytes,
            compressions=compressions,
            codecs=codecs,
        )

    @property
    def path(self) -> str:
        """Returns the URL path to mount the application to when serving multiple applications."""
        return "/paladin.admin.v1.SystemService"


class SystemServiceClientSync(ConnectClientSync):
    """
    SystemService on the admin plane exposes operator-only diagnostics
    that contain redacted-but-sensitive configuration. Distinct from
    paladin.iam.v1.SystemService (which is open to any authenticated user
    for build/version/health) — admin SystemService is gated to
    platform.admin role so we can ship the running config without
    leaking shape to regular tenants.
    """
    def __init__(
        self,
        address: str,
        *,
        codec: Codec | None = _PROTO_BINARY_CODEC,
        protocol: ProtocolType = ProtocolType.CONNECT,
        accept_compression: Iterable[Compression] | None = None,
        send_compression: Compression | None = _GZIP_COMPRESSION,
        timeout_ms: int | None = None,
        read_max_bytes: int | None = None,
        interceptors: Iterable[InterceptorSync] = (),
        http_client: SyncClient | None = None,
    ) -> None:
        super().__init__(
            address=address,
            codec=codec,
            protocol=protocol,
            accept_compression=accept_compression,
            send_compression=send_compression,
            timeout_ms=timeout_ms,
            read_max_bytes=read_max_bytes,
            interceptors=interceptors,
            http_client=http_client,
        )
    def get_config(
        self,
        request: GetConfigRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetConfigResponse:
        """
        GetConfig returns the running control-plane configuration as a
        single YAML blob with all secrets replaced by "***". The shape
        matches the on-disk config.yaml exactly so an operator can diff
        what's loaded against what's checked in. Cheap; no DB touch.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetConfig",
                service_name="paladin.admin.v1.SystemService",
                input=GetConfigRequest,
                output=GetConfigResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def get_dispatcher_stats(
        self,
        request: GetDispatcherStatsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetDispatcherStatsResponse:
        """
        GetDispatcherStats returns the event dispatcher's operator view:
        global delivery-queue depth plus a per-subscription breakdown of
        stuck work (pending/failed counts + the latest error). The admin
        plane PROXIES the dispatcher pod's ops endpoint — the stats are
        computed there because event_deliveries is RLS'd per tenant and
        only the dispatcher's BYPASSRLS pool sees the cross-tenant whole.
        Empty/zeroed response with `available=false` when the dispatcher
        ops endpoint is unconfigured or unreachable — the console renders
        "stats unavailable" rather than erroring.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetDispatcherStats",
                service_name="paladin.admin.v1.SystemService",
                input=GetDispatcherStatsRequest,
                output=GetDispatcherStatsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def get_platform_stats(
        self,
        request: GetPlatformStatsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> GetPlatformStatsResponse:
        """
        GetPlatformStats returns a cross-tenant census of the control plane:
        how many tenants / storage backends / buckets / object keys / users
        exist and how they break down, plus per-tenant object counts by
        state. Backs the console's /stats page.

        Two data sources, one response (see GetPlatformStatsResponse): the
        control-plane counts come from this pod's pool; the object census
        is proxied from the worker pod's BYPASSRLS ops endpoint and
        degrades to `objects.available=false` when that is unconfigured or
        unreachable. Read-only, no audit row — it is a dashboard poll.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="GetPlatformStats",
                service_name="paladin.admin.v1.SystemService",
                input=GetPlatformStatsRequest,
                output=GetPlatformStatsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
    def list_platform_stats_tenants(
        self,
        request: ListPlatformStatsTenantsRequest,
        *,
        headers: Headers | Mapping[str, str] | None = None, 
        timeout_ms: int | None = None,
        use_get: bool = False,
    ) -> ListPlatformStatsTenantsResponse:
        """
        ListPlatformStatsTenants answers "whose" for one of the census counts
        GetPlatformStats flags for attention: the tenants behind it, biggest
        share first, paged like the object table. The counts are computed from
        the same predicates as the census, so a full walk plus `unattributed`
        adds up to the number GetPlatformStats reported at the same instant.

        Proxied from the worker like the census, but with no degraded answer:
        UNAVAILABLE when the worker leg is unconfigured or unreachable, because
        an empty list would read as "nobody". Read-only, no audit row.
        """
        return self.execute_unary(
            request=request,
            method=MethodInfo(
                name="ListPlatformStatsTenants",
                service_name="paladin.admin.v1.SystemService",
                input=ListPlatformStatsTenantsRequest,
                output=ListPlatformStatsTenantsResponse,
                idempotency_level=IdempotencyLevel.NO_SIDE_EFFECTS,
            ),
            headers=headers,
            timeout_ms=timeout_ms,
            use_get=use_get,
        )
