// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const categoryExists = `-- name: CategoryExists :one
SELECT EXISTS(
  SELECT 1 FROM object_categories
  WHERE tenant_id = $1 AND slug = $2
) AS exists
`

func (q *Queries) CategoryExists(ctx context.Context, tenantID string, slug string) (bool, error) {
	row := q.db.QueryRow(ctx, categoryExists, tenantID, slug)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const categoryObjectCount = `-- name: CategoryObjectCount :one
SELECT COUNT(*)::bigint AS count
FROM objects
WHERE tenant_id = $1 AND category = $2
  AND status NOT IN ('hard_deleted')
`

func (q *Queries) CategoryObjectCount(ctx context.Context, tenantID string, category string) (int64, error) {
	row := q.db.QueryRow(ctx, categoryObjectCount, tenantID, category)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCategory = `-- name: CreateCategory :exec

INSERT INTO object_categories (id, tenant_id, slug, name, description)
VALUES ($1, $2, $3, $4, $5)
`

// Category queries
func (q *Queries) CreateCategory(ctx context.Context, iD pgtype.UUID, tenantID string, slug string, name string, description *string) error {
	_, err := q.db.Exec(ctx, createCategory,
		iD,
		tenantID,
		slug,
		name,
		description,
	)
	return err
}

const deleteCategory = `-- name: DeleteCategory :execrows
DELETE FROM object_categories
WHERE tenant_id = $1 AND slug = $2
`

func (q *Queries) DeleteCategory(ctx context.Context, tenantID string, slug string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteCategory, tenantID, slug)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCategory = `-- name: GetCategory :one
SELECT id, tenant_id, slug, name, description, created_at, updated_at
FROM object_categories
WHERE tenant_id = $1 AND slug = $2
`

func (q *Queries) GetCategory(ctx context.Context, tenantID string, slug string) (ObjectCategory, error) {
	row := q.db.QueryRow(ctx, getCategory, tenantID, slug)
	var i ObjectCategory
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCategories = `-- name: ListCategories :many
SELECT id, tenant_id, slug, name, description, created_at, updated_at
FROM object_categories
WHERE tenant_id = $1
  AND ($3::timestamptz IS NULL OR created_at < $3)
ORDER BY created_at DESC
LIMIT $2
`

func (q *Queries) ListCategories(ctx context.Context, tenantID string, limit int32, cursor pgtype.Timestamptz) ([]ObjectCategory, error) {
	rows, err := q.db.Query(ctx, listCategories, tenantID, limit, cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ObjectCategory
	for rows.Next() {
		var i ObjectCategory
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
