// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: object_upload_intents.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUploadIntent = `-- name: CreateUploadIntent :exec

INSERT INTO object_upload_intents (
    id, tenant_id, bucket, object_key, category, subpath,
    content_type, size_bytes, labels, tags, external_ref,
    idempotency_key, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
`

// Object upload intent queries
//
// Intents hold the server-generated upload intent produced by UploadObject
// until the client confirms success via CompleteObject. No object exists in
// the `objects` table while an intent is outstanding; on completion the
// intent is deleted and an object row is INSERTed in the same transaction.
func (q *Queries) CreateUploadIntent(ctx context.Context, iD pgtype.UUID, tenantID string, bucket string, objectKey string, category string, subpath *string, contentType string, sizeBytes int64, labels []byte, tags []byte, externalRef *string, idempotencyKey *string, expiresAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, createUploadIntent,
		iD,
		tenantID,
		bucket,
		objectKey,
		category,
		subpath,
		contentType,
		sizeBytes,
		labels,
		tags,
		externalRef,
		idempotencyKey,
		expiresAt,
	)
	return err
}

const deleteExpiredUploadIntents = `-- name: DeleteExpiredUploadIntents :execrows
DELETE FROM object_upload_intents AS oui
WHERE oui.id IN (
    SELECT inner_oui.id
    FROM object_upload_intents AS inner_oui
    WHERE inner_oui.expires_at < $1
    LIMIT $2
)
`

func (q *Queries) DeleteExpiredUploadIntents(ctx context.Context, expiresAt pgtype.Timestamptz, limit int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredUploadIntents, expiresAt, limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteUploadIntent = `-- name: DeleteUploadIntent :execrows
DELETE FROM object_upload_intents
WHERE tenant_id = $1 AND id = $2
`

func (q *Queries) DeleteUploadIntent(ctx context.Context, tenantID string, iD pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUploadIntent, tenantID, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUploadIntent = `-- name: GetUploadIntent :one
SELECT object_upload_intents.id, object_upload_intents.tenant_id, object_upload_intents.bucket, object_upload_intents.object_key, object_upload_intents.category, object_upload_intents.subpath, object_upload_intents.content_type, object_upload_intents.size_bytes, object_upload_intents.labels, object_upload_intents.tags, object_upload_intents.external_ref, object_upload_intents.idempotency_key, object_upload_intents.created_at, object_upload_intents.expires_at
FROM object_upload_intents
WHERE tenant_id = $1 AND id = $2
`

type GetUploadIntentRow struct {
	ObjectUploadIntent ObjectUploadIntent `json:"object_upload_intent"`
}

func (q *Queries) GetUploadIntent(ctx context.Context, tenantID string, iD pgtype.UUID) (GetUploadIntentRow, error) {
	row := q.db.QueryRow(ctx, getUploadIntent, tenantID, iD)
	var i GetUploadIntentRow
	err := row.Scan(
		&i.ObjectUploadIntent.ID,
		&i.ObjectUploadIntent.TenantID,
		&i.ObjectUploadIntent.Bucket,
		&i.ObjectUploadIntent.ObjectKey,
		&i.ObjectUploadIntent.Category,
		&i.ObjectUploadIntent.Subpath,
		&i.ObjectUploadIntent.ContentType,
		&i.ObjectUploadIntent.SizeBytes,
		&i.ObjectUploadIntent.Labels,
		&i.ObjectUploadIntent.Tags,
		&i.ObjectUploadIntent.ExternalRef,
		&i.ObjectUploadIntent.IdempotencyKey,
		&i.ObjectUploadIntent.CreatedAt,
		&i.ObjectUploadIntent.ExpiresAt,
	)
	return i, err
}

const getUploadIntentByIdempotencyKey = `-- name: GetUploadIntentByIdempotencyKey :one
SELECT object_upload_intents.id, object_upload_intents.tenant_id, object_upload_intents.bucket, object_upload_intents.object_key, object_upload_intents.category, object_upload_intents.subpath, object_upload_intents.content_type, object_upload_intents.size_bytes, object_upload_intents.labels, object_upload_intents.tags, object_upload_intents.external_ref, object_upload_intents.idempotency_key, object_upload_intents.created_at, object_upload_intents.expires_at
FROM object_upload_intents
WHERE tenant_id = $1 AND idempotency_key = $2
`

type GetUploadIntentByIdempotencyKeyRow struct {
	ObjectUploadIntent ObjectUploadIntent `json:"object_upload_intent"`
}

func (q *Queries) GetUploadIntentByIdempotencyKey(ctx context.Context, tenantID string, idempotencyKey *string) (GetUploadIntentByIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getUploadIntentByIdempotencyKey, tenantID, idempotencyKey)
	var i GetUploadIntentByIdempotencyKeyRow
	err := row.Scan(
		&i.ObjectUploadIntent.ID,
		&i.ObjectUploadIntent.TenantID,
		&i.ObjectUploadIntent.Bucket,
		&i.ObjectUploadIntent.ObjectKey,
		&i.ObjectUploadIntent.Category,
		&i.ObjectUploadIntent.Subpath,
		&i.ObjectUploadIntent.ContentType,
		&i.ObjectUploadIntent.SizeBytes,
		&i.ObjectUploadIntent.Labels,
		&i.ObjectUploadIntent.Tags,
		&i.ObjectUploadIntent.ExternalRef,
		&i.ObjectUploadIntent.IdempotencyKey,
		&i.ObjectUploadIntent.CreatedAt,
		&i.ObjectUploadIntent.ExpiresAt,
	)
	return i, err
}

const getUploadIntentByKey = `-- name: GetUploadIntentByKey :one
SELECT object_upload_intents.id, object_upload_intents.tenant_id, object_upload_intents.bucket, object_upload_intents.object_key, object_upload_intents.category, object_upload_intents.subpath, object_upload_intents.content_type, object_upload_intents.size_bytes, object_upload_intents.labels, object_upload_intents.tags, object_upload_intents.external_ref, object_upload_intents.idempotency_key, object_upload_intents.created_at, object_upload_intents.expires_at
FROM object_upload_intents
WHERE tenant_id = $1 AND bucket = $2 AND object_key = $3
`

type GetUploadIntentByKeyRow struct {
	ObjectUploadIntent ObjectUploadIntent `json:"object_upload_intent"`
}

func (q *Queries) GetUploadIntentByKey(ctx context.Context, tenantID string, bucket string, objectKey string) (GetUploadIntentByKeyRow, error) {
	row := q.db.QueryRow(ctx, getUploadIntentByKey, tenantID, bucket, objectKey)
	var i GetUploadIntentByKeyRow
	err := row.Scan(
		&i.ObjectUploadIntent.ID,
		&i.ObjectUploadIntent.TenantID,
		&i.ObjectUploadIntent.Bucket,
		&i.ObjectUploadIntent.ObjectKey,
		&i.ObjectUploadIntent.Category,
		&i.ObjectUploadIntent.Subpath,
		&i.ObjectUploadIntent.ContentType,
		&i.ObjectUploadIntent.SizeBytes,
		&i.ObjectUploadIntent.Labels,
		&i.ObjectUploadIntent.Tags,
		&i.ObjectUploadIntent.ExternalRef,
		&i.ObjectUploadIntent.IdempotencyKey,
		&i.ObjectUploadIntent.CreatedAt,
		&i.ObjectUploadIntent.ExpiresAt,
	)
	return i, err
}
