// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: objects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkDeleteObject = `-- name: BulkDeleteObject :execrows
DELETE FROM objects
WHERE tenant_id = $1 AND id = ANY($2::uuid[])
`

func (q *Queries) BulkDeleteObject(ctx context.Context, tenantID string, column2 []pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, bulkDeleteObject, tenantID, column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bulkMarkObjectSoftDeleted = `-- name: BulkMarkObjectSoftDeleted :execrows
UPDATE objects
SET status = 'soft_deleted',
    deleted_at = now(),
    updated_at = now()
WHERE tenant_id = $1
  AND id = ANY($2::uuid[])
  AND status != 'soft_deleted'
  AND status != 'hard_deleted'
`

func (q *Queries) BulkMarkObjectSoftDeleted(ctx context.Context, tenantID string, column2 []pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, bulkMarkObjectSoftDeleted, tenantID, column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const bulkRestoreObject = `-- name: BulkRestoreObject :execrows
UPDATE objects
SET status = 'uploaded',
    deleted_at = NULL,
    updated_at = now()
WHERE tenant_id = $1
  AND id = ANY($2::uuid[])
  AND status = 'soft_deleted'
`

func (q *Queries) BulkRestoreObject(ctx context.Context, tenantID string, column2 []pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, bulkRestoreObject, tenantID, column2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createObject = `-- name: CreateObject :exec

INSERT INTO objects (
    id, tenant_id, object_key, bucket, content_type, size_bytes,
    checksum_sha256, status, expires_at, labels, external_ref, category, subpath
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13
)
`

// Objects queries
func (q *Queries) CreateObject(ctx context.Context, iD pgtype.UUID, tenantID string, objectKey string, bucket string, contentType string, sizeBytes int64, checksumSha256 *string, status string, expiresAt pgtype.Timestamptz, labels []byte, externalRef *string, category string, subpath *string) error {
	_, err := q.db.Exec(ctx, createObject,
		iD,
		tenantID,
		objectKey,
		bucket,
		contentType,
		sizeBytes,
		checksumSha256,
		status,
		expiresAt,
		labels,
		externalRef,
		category,
		subpath,
	)
	return err
}

const deleteObject = `-- name: DeleteObject :execrows
DELETE FROM objects
WHERE tenant_id = $1 AND id = $2
`

func (q *Queries) DeleteObject(ctx context.Context, tenantID string, iD pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteObject, tenantID, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getObject = `-- name: GetObject :one
SELECT objects.id, objects.tenant_id, objects.object_key, objects.bucket, objects.content_type, objects.size_bytes, objects.checksum_sha256, objects.status, objects.created_at, objects.updated_at, objects.expires_at, objects.labels, objects.external_ref, objects.stored_etag, objects.stored_size_bytes, objects.completed_at, objects.deleted_at, objects.category, objects.subpath
FROM objects
WHERE tenant_id = $1 AND id = $2
`

type GetObjectRow struct {
	Object Object `json:"object"`
}

func (q *Queries) GetObject(ctx context.Context, tenantID string, iD pgtype.UUID) (GetObjectRow, error) {
	row := q.db.QueryRow(ctx, getObject, tenantID, iD)
	var i GetObjectRow
	err := row.Scan(
		&i.Object.ID,
		&i.Object.TenantID,
		&i.Object.ObjectKey,
		&i.Object.Bucket,
		&i.Object.ContentType,
		&i.Object.SizeBytes,
		&i.Object.ChecksumSha256,
		&i.Object.Status,
		&i.Object.CreatedAt,
		&i.Object.UpdatedAt,
		&i.Object.ExpiresAt,
		&i.Object.Labels,
		&i.Object.ExternalRef,
		&i.Object.StoredEtag,
		&i.Object.StoredSizeBytes,
		&i.Object.CompletedAt,
		&i.Object.DeletedAt,
		&i.Object.Category,
		&i.Object.Subpath,
	)
	return i, err
}

const getObjectByExternalRef = `-- name: GetObjectByExternalRef :one
SELECT objects.id, objects.tenant_id, objects.object_key, objects.bucket, objects.content_type, objects.size_bytes, objects.checksum_sha256, objects.status, objects.created_at, objects.updated_at, objects.expires_at, objects.labels, objects.external_ref, objects.stored_etag, objects.stored_size_bytes, objects.completed_at, objects.deleted_at, objects.category, objects.subpath
FROM objects
WHERE tenant_id = $1 AND external_ref = $2
`

type GetObjectByExternalRefRow struct {
	Object Object `json:"object"`
}

func (q *Queries) GetObjectByExternalRef(ctx context.Context, tenantID string, externalRef *string) (GetObjectByExternalRefRow, error) {
	row := q.db.QueryRow(ctx, getObjectByExternalRef, tenantID, externalRef)
	var i GetObjectByExternalRefRow
	err := row.Scan(
		&i.Object.ID,
		&i.Object.TenantID,
		&i.Object.ObjectKey,
		&i.Object.Bucket,
		&i.Object.ContentType,
		&i.Object.SizeBytes,
		&i.Object.ChecksumSha256,
		&i.Object.Status,
		&i.Object.CreatedAt,
		&i.Object.UpdatedAt,
		&i.Object.ExpiresAt,
		&i.Object.Labels,
		&i.Object.ExternalRef,
		&i.Object.StoredEtag,
		&i.Object.StoredSizeBytes,
		&i.Object.CompletedAt,
		&i.Object.DeletedAt,
		&i.Object.Category,
		&i.Object.Subpath,
	)
	return i, err
}

const getObjectStats = `-- name: GetObjectStats :one
SELECT 
    COUNT(*)::bigint as total_count,
    COALESCE(SUM(size_bytes), 0)::bigint as total_size,
    COUNT(*) FILTER (WHERE status = 'pending')::bigint as pending_count,
    COUNT(*) FILTER (WHERE status = 'uploading')::bigint as uploading_count,
    COUNT(*) FILTER (WHERE status = 'uploaded')::bigint as uploaded_count,
    COUNT(*) FILTER (WHERE status = 'complete')::bigint as complete_count,
    COUNT(*) FILTER (WHERE status = 'soft_deleted')::bigint as soft_deleted_count
FROM objects
WHERE tenant_id = $1
`

type GetObjectStatsRow struct {
	TotalCount       int64 `json:"total_count"`
	TotalSize        int64 `json:"total_size"`
	PendingCount     int64 `json:"pending_count"`
	UploadingCount   int64 `json:"uploading_count"`
	UploadedCount    int64 `json:"uploaded_count"`
	CompleteCount    int64 `json:"complete_count"`
	SoftDeletedCount int64 `json:"soft_deleted_count"`
}

func (q *Queries) GetObjectStats(ctx context.Context, tenantID string) (GetObjectStatsRow, error) {
	row := q.db.QueryRow(ctx, getObjectStats, tenantID)
	var i GetObjectStatsRow
	err := row.Scan(
		&i.TotalCount,
		&i.TotalSize,
		&i.PendingCount,
		&i.UploadingCount,
		&i.UploadedCount,
		&i.CompleteCount,
		&i.SoftDeletedCount,
	)
	return i, err
}

const listExpiredPendingObjects = `-- name: ListExpiredPendingObjects :many
SELECT objects.id, objects.tenant_id, objects.object_key, objects.bucket, objects.content_type, objects.size_bytes, objects.checksum_sha256, objects.status, objects.created_at, objects.updated_at, objects.expires_at, objects.labels, objects.external_ref, objects.stored_etag, objects.stored_size_bytes, objects.completed_at, objects.deleted_at, objects.category, objects.subpath
FROM objects
WHERE status = 'pending' AND expires_at < $1
LIMIT $2
`

type ListExpiredPendingObjectsRow struct {
	Object Object `json:"object"`
}

func (q *Queries) ListExpiredPendingObjects(ctx context.Context, expiresAt pgtype.Timestamptz, limit int32) ([]ListExpiredPendingObjectsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredPendingObjects, expiresAt, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredPendingObjectsRow
	for rows.Next() {
		var i ListExpiredPendingObjectsRow
		if err := rows.Scan(
			&i.Object.ID,
			&i.Object.TenantID,
			&i.Object.ObjectKey,
			&i.Object.Bucket,
			&i.Object.ContentType,
			&i.Object.SizeBytes,
			&i.Object.ChecksumSha256,
			&i.Object.Status,
			&i.Object.CreatedAt,
			&i.Object.UpdatedAt,
			&i.Object.ExpiresAt,
			&i.Object.Labels,
			&i.Object.ExternalRef,
			&i.Object.StoredEtag,
			&i.Object.StoredSizeBytes,
			&i.Object.CompletedAt,
			&i.Object.DeletedAt,
			&i.Object.Category,
			&i.Object.Subpath,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listObjects = `-- name: ListObjects :many
SELECT objects.id, objects.tenant_id, objects.object_key, objects.bucket, objects.content_type, objects.size_bytes, objects.checksum_sha256, objects.status, objects.created_at, objects.updated_at, objects.expires_at, objects.labels, objects.external_ref, objects.stored_etag, objects.stored_size_bytes, objects.completed_at, objects.deleted_at, objects.category, objects.subpath, COUNT(*) OVER() AS total_count
FROM objects
WHERE tenant_id = $1
  AND ($2::text IS NULL OR status = $2)
  AND ($3::text IS NULL OR external_ref = $3)
  AND ($4::timestamptz IS NULL OR created_at >= $4::timestamptz)
  AND ($5::timestamptz IS NULL OR created_at < $5::timestamptz)
  AND ($6::timestamptz IS NULL OR created_at < $6::timestamptz)
  AND (
    $7::text IS NULL OR 
    ($8::bool AND (category = $7 OR category LIKE $7 || '/%')) OR
    category = $7
  )
  AND ($9::text IS NULL OR object_key LIKE $9 || '%')
ORDER BY
    -- Sorting logic
    CASE WHEN $10::text = 'name' AND $11::text = 'asc' THEN object_key END ASC,
    CASE WHEN $10::text = 'name' AND $11::text = 'desc' THEN object_key END DESC,
    CASE WHEN $10::text = 'category' AND $11::text = 'asc' THEN category END ASC,
    CASE WHEN $10::text = 'category' AND $11::text = 'desc' THEN category END DESC,
    CASE WHEN $10::text = 'size' AND $11::text = 'asc' THEN size_bytes END ASC,
    CASE WHEN $10::text = 'size' AND $11::text = 'desc' THEN size_bytes END DESC,
    CASE WHEN $10::text = 'status' AND $11::text = 'asc' THEN status END ASC,
    CASE WHEN $10::text = 'status' AND $11::text = 'desc' THEN status END DESC,
    CASE WHEN ($10::text = 'created' OR $10::text IS NULL) AND $11::text = 'asc' THEN created_at END ASC,
    CASE WHEN ($10::text = 'created' OR $10::text IS NULL) AND ($11::text = 'desc' OR $11::text IS NULL) THEN created_at END DESC
LIMIT $12
`

type ListObjectsRow struct {
	Object     Object `json:"object"`
	TotalCount int64  `json:"total_count"`
}

func (q *Queries) ListObjects(ctx context.Context, tenantID string, status *string, externalRef *string, createdAfter pgtype.Timestamptz, createdBefore pgtype.Timestamptz, cursor pgtype.Timestamptz, category *string, recursive bool, keyPrefix *string, sortBy string, sortOrder string, limitVal int32) ([]ListObjectsRow, error) {
	rows, err := q.db.Query(ctx, listObjects,
		tenantID,
		status,
		externalRef,
		createdAfter,
		createdBefore,
		cursor,
		category,
		recursive,
		keyPrefix,
		sortBy,
		sortOrder,
		limitVal,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListObjectsRow
	for rows.Next() {
		var i ListObjectsRow
		if err := rows.Scan(
			&i.Object.ID,
			&i.Object.TenantID,
			&i.Object.ObjectKey,
			&i.Object.Bucket,
			&i.Object.ContentType,
			&i.Object.SizeBytes,
			&i.Object.ChecksumSha256,
			&i.Object.Status,
			&i.Object.CreatedAt,
			&i.Object.UpdatedAt,
			&i.Object.ExpiresAt,
			&i.Object.Labels,
			&i.Object.ExternalRef,
			&i.Object.StoredEtag,
			&i.Object.StoredSizeBytes,
			&i.Object.CompletedAt,
			&i.Object.DeletedAt,
			&i.Object.Category,
			&i.Object.Subpath,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markObjectComplete = `-- name: MarkObjectComplete :execrows
UPDATE objects
SET status = 'complete',
    stored_etag = $3,
    stored_size_bytes = $4,
    completed_at = now(),
    updated_at = now()
WHERE tenant_id = $1
  AND id = $2
  AND (status = 'pending' OR status = 'uploading')
`

func (q *Queries) MarkObjectComplete(ctx context.Context, tenantID string, iD pgtype.UUID, storedEtag *string, storedSizeBytes *int64) (int64, error) {
	result, err := q.db.Exec(ctx, markObjectComplete,
		tenantID,
		iD,
		storedEtag,
		storedSizeBytes,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markObjectHardDeleted = `-- name: MarkObjectHardDeleted :execrows
UPDATE objects
SET status = 'hard_deleted',
    deleted_at = COALESCE(deleted_at, now()),
    updated_at = now()
WHERE tenant_id = $1
  AND id = $2
  AND status != 'hard_deleted'
`

func (q *Queries) MarkObjectHardDeleted(ctx context.Context, tenantID string, iD pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markObjectHardDeleted, tenantID, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markObjectSoftDeleted = `-- name: MarkObjectSoftDeleted :execrows
UPDATE objects
SET status = 'soft_deleted',
    deleted_at = now(),
    updated_at = now()
WHERE tenant_id = $1
  AND id = $2
  AND status != 'soft_deleted'
  AND status != 'hard_deleted'
`

func (q *Queries) MarkObjectSoftDeleted(ctx context.Context, tenantID string, iD pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markObjectSoftDeleted, tenantID, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const patchObjectExternalRef = `-- name: PatchObjectExternalRef :one
UPDATE objects
SET external_ref = $3,
    updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING objects.id, objects.tenant_id, objects.object_key, objects.bucket, objects.content_type, objects.size_bytes, objects.checksum_sha256, objects.status, objects.created_at, objects.updated_at, objects.expires_at, objects.labels, objects.external_ref, objects.stored_etag, objects.stored_size_bytes, objects.completed_at, objects.deleted_at, objects.category, objects.subpath
`

type PatchObjectExternalRefRow struct {
	Object Object `json:"object"`
}

func (q *Queries) PatchObjectExternalRef(ctx context.Context, tenantID string, iD pgtype.UUID, externalRef *string) (PatchObjectExternalRefRow, error) {
	row := q.db.QueryRow(ctx, patchObjectExternalRef, tenantID, iD, externalRef)
	var i PatchObjectExternalRefRow
	err := row.Scan(
		&i.Object.ID,
		&i.Object.TenantID,
		&i.Object.ObjectKey,
		&i.Object.Bucket,
		&i.Object.ContentType,
		&i.Object.SizeBytes,
		&i.Object.ChecksumSha256,
		&i.Object.Status,
		&i.Object.CreatedAt,
		&i.Object.UpdatedAt,
		&i.Object.ExpiresAt,
		&i.Object.Labels,
		&i.Object.ExternalRef,
		&i.Object.StoredEtag,
		&i.Object.StoredSizeBytes,
		&i.Object.CompletedAt,
		&i.Object.DeletedAt,
		&i.Object.Category,
		&i.Object.Subpath,
	)
	return i, err
}

const patchObjectLabels = `-- name: PatchObjectLabels :one
UPDATE objects
SET labels = labels || $3,
    updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING objects.id, objects.tenant_id, objects.object_key, objects.bucket, objects.content_type, objects.size_bytes, objects.checksum_sha256, objects.status, objects.created_at, objects.updated_at, objects.expires_at, objects.labels, objects.external_ref, objects.stored_etag, objects.stored_size_bytes, objects.completed_at, objects.deleted_at, objects.category, objects.subpath
`

type PatchObjectLabelsRow struct {
	Object Object `json:"object"`
}

func (q *Queries) PatchObjectLabels(ctx context.Context, tenantID string, iD pgtype.UUID, labels []byte) (PatchObjectLabelsRow, error) {
	row := q.db.QueryRow(ctx, patchObjectLabels, tenantID, iD, labels)
	var i PatchObjectLabelsRow
	err := row.Scan(
		&i.Object.ID,
		&i.Object.TenantID,
		&i.Object.ObjectKey,
		&i.Object.Bucket,
		&i.Object.ContentType,
		&i.Object.SizeBytes,
		&i.Object.ChecksumSha256,
		&i.Object.Status,
		&i.Object.CreatedAt,
		&i.Object.UpdatedAt,
		&i.Object.ExpiresAt,
		&i.Object.Labels,
		&i.Object.ExternalRef,
		&i.Object.StoredEtag,
		&i.Object.StoredSizeBytes,
		&i.Object.CompletedAt,
		&i.Object.DeletedAt,
		&i.Object.Category,
		&i.Object.Subpath,
	)
	return i, err
}

const patchObjectLabelsAndExternalRef = `-- name: PatchObjectLabelsAndExternalRef :one
UPDATE objects
SET labels = labels || $3,
    external_ref = $4,
    updated_at = now()
WHERE tenant_id = $1 AND id = $2
RETURNING objects.id, objects.tenant_id, objects.object_key, objects.bucket, objects.content_type, objects.size_bytes, objects.checksum_sha256, objects.status, objects.created_at, objects.updated_at, objects.expires_at, objects.labels, objects.external_ref, objects.stored_etag, objects.stored_size_bytes, objects.completed_at, objects.deleted_at, objects.category, objects.subpath
`

type PatchObjectLabelsAndExternalRefRow struct {
	Object Object `json:"object"`
}

func (q *Queries) PatchObjectLabelsAndExternalRef(ctx context.Context, tenantID string, iD pgtype.UUID, labels []byte, externalRef *string) (PatchObjectLabelsAndExternalRefRow, error) {
	row := q.db.QueryRow(ctx, patchObjectLabelsAndExternalRef,
		tenantID,
		iD,
		labels,
		externalRef,
	)
	var i PatchObjectLabelsAndExternalRefRow
	err := row.Scan(
		&i.Object.ID,
		&i.Object.TenantID,
		&i.Object.ObjectKey,
		&i.Object.Bucket,
		&i.Object.ContentType,
		&i.Object.SizeBytes,
		&i.Object.ChecksumSha256,
		&i.Object.Status,
		&i.Object.CreatedAt,
		&i.Object.UpdatedAt,
		&i.Object.ExpiresAt,
		&i.Object.Labels,
		&i.Object.ExternalRef,
		&i.Object.StoredEtag,
		&i.Object.StoredSizeBytes,
		&i.Object.CompletedAt,
		&i.Object.DeletedAt,
		&i.Object.Category,
		&i.Object.Subpath,
	)
	return i, err
}

const restoreObject = `-- name: RestoreObject :execrows
UPDATE objects
SET status = 'uploaded',
    deleted_at = NULL,
    updated_at = now()
WHERE tenant_id = $1
  AND id = $2
  AND status = 'soft_deleted'
`

func (q *Queries) RestoreObject(ctx context.Context, tenantID string, iD pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, restoreObject, tenantID, iD)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateObjectStatus = `-- name: UpdateObjectStatus :execrows
UPDATE objects
SET status = $3, updated_at = NOW()
WHERE tenant_id = $1 AND id = $2
`

func (q *Queries) UpdateObjectStatus(ctx context.Context, tenantID string, iD pgtype.UUID, status string) (int64, error) {
	result, err := q.db.Exec(ctx, updateObjectStatus, tenantID, iD, status)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
