# Custom Optimized PostgreSQL Configuration
listen_addresses = '*'
max_connections = 200
shared_buffers = 256MB
work_mem = 8MB
maintenance_work_mem = 64MB
effective_io_concurrency = 200
random_page_cost = 1.1
wal_level = logical
max_wal_size = 1GB
min_wal_size = 512MB
checkpoint_timeout = 15min
autovacuum = on
autovacuum_max_workers = 3
autovacuum_naptime = 15s
autovacuum_vacuum_threshold = 50
autovacuum_analyze_threshold = 50
autovacuum_vacuum_scale_factor = 0.05
autovacuum_analyze_scale_factor = 0.02
effective_cache_size = 768MB
