// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: paladin/data/v1/batch_service.proto

package paladindatav1connect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"
	v1 "github.com/oleg-tkachuk/paladin/internal/api/pb/data/v1"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BatchServiceName is the fully-qualified name of the BatchService service.
	BatchServiceName = "paladin.data.v1.BatchService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BatchServiceBatchDeleteObjectsProcedure is the fully-qualified name of the BatchService's
	// BatchDeleteObjects RPC.
	BatchServiceBatchDeleteObjectsProcedure = "/paladin.data.v1.BatchService/BatchDeleteObjects"
	// BatchServiceBatchCopyObjectsProcedure is the fully-qualified name of the BatchService's
	// BatchCopyObjects RPC.
	BatchServiceBatchCopyObjectsProcedure = "/paladin.data.v1.BatchService/BatchCopyObjects"
	// BatchServiceBatchRestoreObjectsProcedure is the fully-qualified name of the BatchService's
	// BatchRestoreObjects RPC.
	BatchServiceBatchRestoreObjectsProcedure = "/paladin.data.v1.BatchService/BatchRestoreObjects"
	// BatchServiceBatchUpdateTagsProcedure is the fully-qualified name of the BatchService's
	// BatchUpdateTags RPC.
	BatchServiceBatchUpdateTagsProcedure = "/paladin.data.v1.BatchService/BatchUpdateTags"
)

// BatchServiceClient is a client for the paladin.data.v1.BatchService service.
type BatchServiceClient interface {
	BatchDeleteObjects(context.Context, *connect.Request[v1.BatchDeleteObjectsRequest]) (*connect.Response[v1.Operation], error)
	BatchCopyObjects(context.Context, *connect.Request[v1.BatchCopyObjectsRequest]) (*connect.Response[v1.Operation], error)
	BatchRestoreObjects(context.Context, *connect.Request[v1.BatchRestoreObjectsRequest]) (*connect.Response[v1.Operation], error)
	BatchUpdateTags(context.Context, *connect.Request[v1.BatchUpdateTagsRequest]) (*connect.Response[v1.Operation], error)
}

// NewBatchServiceClient constructs a client for the paladin.data.v1.BatchService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBatchServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BatchServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	batchServiceMethods := v1.File_paladin_data_v1_batch_service_proto.Services().ByName("BatchService").Methods()
	return &batchServiceClient{
		batchDeleteObjects: connect.NewClient[v1.BatchDeleteObjectsRequest, v1.Operation](
			httpClient,
			baseURL+BatchServiceBatchDeleteObjectsProcedure,
			connect.WithSchema(batchServiceMethods.ByName("BatchDeleteObjects")),
			connect.WithClientOptions(opts...),
		),
		batchCopyObjects: connect.NewClient[v1.BatchCopyObjectsRequest, v1.Operation](
			httpClient,
			baseURL+BatchServiceBatchCopyObjectsProcedure,
			connect.WithSchema(batchServiceMethods.ByName("BatchCopyObjects")),
			connect.WithClientOptions(opts...),
		),
		batchRestoreObjects: connect.NewClient[v1.BatchRestoreObjectsRequest, v1.Operation](
			httpClient,
			baseURL+BatchServiceBatchRestoreObjectsProcedure,
			connect.WithSchema(batchServiceMethods.ByName("BatchRestoreObjects")),
			connect.WithClientOptions(opts...),
		),
		batchUpdateTags: connect.NewClient[v1.BatchUpdateTagsRequest, v1.Operation](
			httpClient,
			baseURL+BatchServiceBatchUpdateTagsProcedure,
			connect.WithSchema(batchServiceMethods.ByName("BatchUpdateTags")),
			connect.WithClientOptions(opts...),
		),
	}
}

// batchServiceClient implements BatchServiceClient.
type batchServiceClient struct {
	batchDeleteObjects  *connect.Client[v1.BatchDeleteObjectsRequest, v1.Operation]
	batchCopyObjects    *connect.Client[v1.BatchCopyObjectsRequest, v1.Operation]
	batchRestoreObjects *connect.Client[v1.BatchRestoreObjectsRequest, v1.Operation]
	batchUpdateTags     *connect.Client[v1.BatchUpdateTagsRequest, v1.Operation]
}

// BatchDeleteObjects calls paladin.data.v1.BatchService.BatchDeleteObjects.
func (c *batchServiceClient) BatchDeleteObjects(ctx context.Context, req *connect.Request[v1.BatchDeleteObjectsRequest]) (*connect.Response[v1.Operation], error) {
	return c.batchDeleteObjects.CallUnary(ctx, req)
}

// BatchCopyObjects calls paladin.data.v1.BatchService.BatchCopyObjects.
func (c *batchServiceClient) BatchCopyObjects(ctx context.Context, req *connect.Request[v1.BatchCopyObjectsRequest]) (*connect.Response[v1.Operation], error) {
	return c.batchCopyObjects.CallUnary(ctx, req)
}

// BatchRestoreObjects calls paladin.data.v1.BatchService.BatchRestoreObjects.
func (c *batchServiceClient) BatchRestoreObjects(ctx context.Context, req *connect.Request[v1.BatchRestoreObjectsRequest]) (*connect.Response[v1.Operation], error) {
	return c.batchRestoreObjects.CallUnary(ctx, req)
}

// BatchUpdateTags calls paladin.data.v1.BatchService.BatchUpdateTags.
func (c *batchServiceClient) BatchUpdateTags(ctx context.Context, req *connect.Request[v1.BatchUpdateTagsRequest]) (*connect.Response[v1.Operation], error) {
	return c.batchUpdateTags.CallUnary(ctx, req)
}

// BatchServiceHandler is an implementation of the paladin.data.v1.BatchService service.
type BatchServiceHandler interface {
	BatchDeleteObjects(context.Context, *connect.Request[v1.BatchDeleteObjectsRequest]) (*connect.Response[v1.Operation], error)
	BatchCopyObjects(context.Context, *connect.Request[v1.BatchCopyObjectsRequest]) (*connect.Response[v1.Operation], error)
	BatchRestoreObjects(context.Context, *connect.Request[v1.BatchRestoreObjectsRequest]) (*connect.Response[v1.Operation], error)
	BatchUpdateTags(context.Context, *connect.Request[v1.BatchUpdateTagsRequest]) (*connect.Response[v1.Operation], error)
}

// NewBatchServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBatchServiceHandler(svc BatchServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	batchServiceMethods := v1.File_paladin_data_v1_batch_service_proto.Services().ByName("BatchService").Methods()
	batchServiceBatchDeleteObjectsHandler := connect.NewUnaryHandler(
		BatchServiceBatchDeleteObjectsProcedure,
		svc.BatchDeleteObjects,
		connect.WithSchema(batchServiceMethods.ByName("BatchDeleteObjects")),
		connect.WithHandlerOptions(opts...),
	)
	batchServiceBatchCopyObjectsHandler := connect.NewUnaryHandler(
		BatchServiceBatchCopyObjectsProcedure,
		svc.BatchCopyObjects,
		connect.WithSchema(batchServiceMethods.ByName("BatchCopyObjects")),
		connect.WithHandlerOptions(opts...),
	)
	batchServiceBatchRestoreObjectsHandler := connect.NewUnaryHandler(
		BatchServiceBatchRestoreObjectsProcedure,
		svc.BatchRestoreObjects,
		connect.WithSchema(batchServiceMethods.ByName("BatchRestoreObjects")),
		connect.WithHandlerOptions(opts...),
	)
	batchServiceBatchUpdateTagsHandler := connect.NewUnaryHandler(
		BatchServiceBatchUpdateTagsProcedure,
		svc.BatchUpdateTags,
		connect.WithSchema(batchServiceMethods.ByName("BatchUpdateTags")),
		connect.WithHandlerOptions(opts...),
	)
	return "/paladin.data.v1.BatchService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BatchServiceBatchDeleteObjectsProcedure:
			batchServiceBatchDeleteObjectsHandler.ServeHTTP(w, r)
		case BatchServiceBatchCopyObjectsProcedure:
			batchServiceBatchCopyObjectsHandler.ServeHTTP(w, r)
		case BatchServiceBatchRestoreObjectsProcedure:
			batchServiceBatchRestoreObjectsHandler.ServeHTTP(w, r)
		case BatchServiceBatchUpdateTagsProcedure:
			batchServiceBatchUpdateTagsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBatchServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBatchServiceHandler struct{}

func (UnimplementedBatchServiceHandler) BatchDeleteObjects(context.Context, *connect.Request[v1.BatchDeleteObjectsRequest]) (*connect.Response[v1.Operation], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paladin.data.v1.BatchService.BatchDeleteObjects is not implemented"))
}

func (UnimplementedBatchServiceHandler) BatchCopyObjects(context.Context, *connect.Request[v1.BatchCopyObjectsRequest]) (*connect.Response[v1.Operation], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paladin.data.v1.BatchService.BatchCopyObjects is not implemented"))
}

func (UnimplementedBatchServiceHandler) BatchRestoreObjects(context.Context, *connect.Request[v1.BatchRestoreObjectsRequest]) (*connect.Response[v1.Operation], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paladin.data.v1.BatchService.BatchRestoreObjects is not implemented"))
}

func (UnimplementedBatchServiceHandler) BatchUpdateTags(context.Context, *connect.Request[v1.BatchUpdateTagsRequest]) (*connect.Response[v1.Operation], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paladin.data.v1.BatchService.BatchUpdateTags is not implemented"))
}
