// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: paladin/iam/v1/auth_service.proto

package paladiniamv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoginRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// For local IdP: subject is username/email. For federated IdP this RPC
	// accepts an upstream authorization code instead (see auth_method).
	Subject  string `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	// Optional upstream IdP code (OIDC authorization-code flow).
	UpstreamCode string `protobuf:"bytes,3,opt,name=upstream_code,json=upstreamCode,proto3" json:"upstream_code,omitempty"`
	// Audience the caller wants the access token for. Server-side ACL still
	// applies — caller cannot escalate beyond their roles.
	RequestedAudience string `protobuf:"bytes,4,opt,name=requested_audience,json=requestedAudience,proto3" json:"requested_audience,omitempty"` // default: "paladin-data"
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *LoginRequest) Reset() {
	*x = LoginRequest{}
	mi := &file_paladin_iam_v1_auth_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginRequest) ProtoMessage() {}

func (x *LoginRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_iam_v1_auth_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginRequest.ProtoReflect.Descriptor instead.
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return file_paladin_iam_v1_auth_service_proto_rawDescGZIP(), []int{0}
}

func (x *LoginRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *LoginRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *LoginRequest) GetUpstreamCode() string {
	if x != nil {
		return x.UpstreamCode
	}
	return ""
}

func (x *LoginRequest) GetRequestedAudience() string {
	if x != nil {
		return x.RequestedAudience
	}
	return ""
}

type LoginResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        *TokenPair             `protobuf:"bytes,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	User          *User                  `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoginResponse) Reset() {
	*x = LoginResponse{}
	mi := &file_paladin_iam_v1_auth_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoginResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoginResponse) ProtoMessage() {}

func (x *LoginResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_iam_v1_auth_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoginResponse.ProtoReflect.Descriptor instead.
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return file_paladin_iam_v1_auth_service_proto_rawDescGZIP(), []int{1}
}

func (x *LoginResponse) GetTokens() *TokenPair {
	if x != nil {
		return x.Tokens
	}
	return nil
}

func (x *LoginResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

type RefreshTokenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefreshToken  string                 `protobuf:"bytes,1,opt,name=refresh_token,json=refreshToken,proto3" json:"refresh_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenRequest) Reset() {
	*x = RefreshTokenRequest{}
	mi := &file_paladin_iam_v1_auth_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenRequest) ProtoMessage() {}

func (x *RefreshTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_iam_v1_auth_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenRequest.ProtoReflect.Descriptor instead.
func (*RefreshTokenRequest) Descriptor() ([]byte, []int) {
	return file_paladin_iam_v1_auth_service_proto_rawDescGZIP(), []int{2}
}

func (x *RefreshTokenRequest) GetRefreshToken() string {
	if x != nil {
		return x.RefreshToken
	}
	return ""
}

type RefreshTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tokens        *TokenPair             `protobuf:"bytes,1,opt,name=tokens,proto3" json:"tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RefreshTokenResponse) Reset() {
	*x = RefreshTokenResponse{}
	mi := &file_paladin_iam_v1_auth_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RefreshTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RefreshTokenResponse) ProtoMessage() {}

func (x *RefreshTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_iam_v1_auth_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RefreshTokenResponse.ProtoReflect.Descriptor instead.
func (*RefreshTokenResponse) Descriptor() ([]byte, []int) {
	return file_paladin_iam_v1_auth_service_proto_rawDescGZIP(), []int{3}
}

func (x *RefreshTokenResponse) GetTokens() *TokenPair {
	if x != nil {
		return x.Tokens
	}
	return nil
}

type RevokeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Either an access or refresh token; server identifies which.
	Token         string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeRequest) Reset() {
	*x = RevokeRequest{}
	mi := &file_paladin_iam_v1_auth_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeRequest) ProtoMessage() {}

func (x *RevokeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_iam_v1_auth_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeRequest.ProtoReflect.Descriptor instead.
func (*RevokeRequest) Descriptor() ([]byte, []int) {
	return file_paladin_iam_v1_auth_service_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type RevokeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeResponse) Reset() {
	*x = RevokeResponse{}
	mi := &file_paladin_iam_v1_auth_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeResponse) ProtoMessage() {}

func (x *RevokeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_iam_v1_auth_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeResponse.ProtoReflect.Descriptor instead.
func (*RevokeResponse) Descriptor() ([]byte, []int) {
	return file_paladin_iam_v1_auth_service_proto_rawDescGZIP(), []int{5}
}

type WhoAmIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIRequest) Reset() {
	*x = WhoAmIRequest{}
	mi := &file_paladin_iam_v1_auth_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIRequest) ProtoMessage() {}

func (x *WhoAmIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_iam_v1_auth_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIRequest.ProtoReflect.Descriptor instead.
func (*WhoAmIRequest) Descriptor() ([]byte, []int) {
	return file_paladin_iam_v1_auth_service_proto_rawDescGZIP(), []int{6}
}

type WhoAmIResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	User  *User                  `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// Audience extracted from the presented token; useful for SPAs that
	// reuse one client to talk to multiple planes.
	Audience      string `protobuf:"bytes,2,opt,name=audience,proto3" json:"audience,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIResponse) Reset() {
	*x = WhoAmIResponse{}
	mi := &file_paladin_iam_v1_auth_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIResponse) ProtoMessage() {}

func (x *WhoAmIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_iam_v1_auth_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIResponse.ProtoReflect.Descriptor instead.
func (*WhoAmIResponse) Descriptor() ([]byte, []int) {
	return file_paladin_iam_v1_auth_service_proto_rawDescGZIP(), []int{7}
}

func (x *WhoAmIResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *WhoAmIResponse) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

type ChangePasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OldPassword   string                 `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordRequest) Reset() {
	*x = ChangePasswordRequest{}
	mi := &file_paladin_iam_v1_auth_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordRequest) ProtoMessage() {}

func (x *ChangePasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_iam_v1_auth_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordRequest.ProtoReflect.Descriptor instead.
func (*ChangePasswordRequest) Descriptor() ([]byte, []int) {
	return file_paladin_iam_v1_auth_service_proto_rawDescGZIP(), []int{8}
}

func (x *ChangePasswordRequest) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordRequest) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ChangePasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResponse) Reset() {
	*x = ChangePasswordResponse{}
	mi := &file_paladin_iam_v1_auth_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResponse) ProtoMessage() {}

func (x *ChangePasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_iam_v1_auth_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResponse.ProtoReflect.Descriptor instead.
func (*ChangePasswordResponse) Descriptor() ([]byte, []int) {
	return file_paladin_iam_v1_auth_service_proto_rawDescGZIP(), []int{9}
}

var File_paladin_iam_v1_auth_service_proto protoreflect.FileDescriptor

const file_paladin_iam_v1_auth_service_proto_rawDesc = "" +
	"\n" +
	"\x1docp/iam/v1/auth_service.proto\x12\n" +
	"paladin.iam.v1\x1a\x1bbuf/validate/validate.proto\x1a\x16ocp/iam/v1/types.proto\"\xa1\x01\n" +
	"\fLoginRequest\x12!\n" +
	"\asubject\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\asubject\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12#\n" +
	"\rupstream_code\x18\x03 \x01(\tR\fupstreamCode\x12-\n" +
	"\x12requested_audience\x18\x04 \x01(\tR\x11requestedAudience\"d\n" +
	"\rLoginResponse\x12-\n" +
	"\x06tokens\x18\x01 \x01(\v2\x15.paladin.iam.v1.TokenPairR\x06tokens\x12$\n" +
	"\x04user\x18\x02 \x01(\v2\x10.paladin.iam.v1.UserR\x04user\"C\n" +
	"\x13RefreshTokenRequest\x12,\n" +
	"\rrefresh_token\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\frefreshToken\"E\n" +
	"\x14RefreshTokenResponse\x12-\n" +
	"\x06tokens\x18\x01 \x01(\v2\x15.paladin.iam.v1.TokenPairR\x06tokens\".\n" +
	"\rRevokeRequest\x12\x1d\n" +
	"\x05token\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x05token\"\x10\n" +
	"\x0eRevokeResponse\"\x0f\n" +
	"\rWhoAmIRequest\"R\n" +
	"\x0eWhoAmIResponse\x12$\n" +
	"\x04user\x18\x01 \x01(\v2\x10.paladin.iam.v1.UserR\x04user\x12\x1a\n" +
	"\baudience\x18\x02 \x01(\tR\baudience\"o\n" +
	"\x15ChangePasswordRequest\x12*\n" +
	"\fold_password\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\voldPassword\x12*\n" +
	"\fnew_password\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\fR\vnewPassword\"\x18\n" +
	"\x16ChangePasswordResponse2\xf9\x02\n" +
	"\vAuthService\x12<\n" +
	"\x05Login\x12\x18.paladin.iam.v1.LoginRequest\x1a\x19.paladin.iam.v1.LoginResponse\x12Q\n" +
	"\fRefreshToken\x12\x1f.paladin.iam.v1.RefreshTokenRequest\x1a .paladin.iam.v1.RefreshTokenResponse\x12?\n" +
	"\x06Revoke\x12\x19.paladin.iam.v1.RevokeRequest\x1a\x1a.paladin.iam.v1.RevokeResponse\x12?\n" +
	"\x06WhoAmI\x12\x19.paladin.iam.v1.WhoAmIRequest\x1a\x1a.paladin.iam.v1.WhoAmIResponse\x12W\n" +
	"\x0eChangePassword\x12!.paladin.iam.v1.ChangePasswordRequest\x1a\".paladin.iam.v1.ChangePasswordResponseBNZLgithub.com/oleg-tkachuk/paladin/internal/api/pb/iam/v1;paladiniamv1b\x06proto3"

var (
	file_paladin_iam_v1_auth_service_proto_rawDescOnce sync.Once
	file_paladin_iam_v1_auth_service_proto_rawDescData []byte
)

func file_paladin_iam_v1_auth_service_proto_rawDescGZIP() []byte {
	file_paladin_iam_v1_auth_service_proto_rawDescOnce.Do(func() {
		file_paladin_iam_v1_auth_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paladin_iam_v1_auth_service_proto_rawDesc), len(file_paladin_iam_v1_auth_service_proto_rawDesc)))
	})
	return file_paladin_iam_v1_auth_service_proto_rawDescData
}

var file_paladin_iam_v1_auth_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_paladin_iam_v1_auth_service_proto_goTypes = []any{
	(*LoginRequest)(nil),           // 0: paladin.iam.v1.LoginRequest
	(*LoginResponse)(nil),          // 1: paladin.iam.v1.LoginResponse
	(*RefreshTokenRequest)(nil),    // 2: paladin.iam.v1.RefreshTokenRequest
	(*RefreshTokenResponse)(nil),   // 3: paladin.iam.v1.RefreshTokenResponse
	(*RevokeRequest)(nil),          // 4: paladin.iam.v1.RevokeRequest
	(*RevokeResponse)(nil),         // 5: paladin.iam.v1.RevokeResponse
	(*WhoAmIRequest)(nil),          // 6: paladin.iam.v1.WhoAmIRequest
	(*WhoAmIResponse)(nil),         // 7: paladin.iam.v1.WhoAmIResponse
	(*ChangePasswordRequest)(nil),  // 8: paladin.iam.v1.ChangePasswordRequest
	(*ChangePasswordResponse)(nil), // 9: paladin.iam.v1.ChangePasswordResponse
	(*TokenPair)(nil),              // 10: paladin.iam.v1.TokenPair
	(*User)(nil),                   // 11: paladin.iam.v1.User
}
var file_paladin_iam_v1_auth_service_proto_depIdxs = []int32{
	10, // 0: paladin.iam.v1.LoginResponse.tokens:type_name -> paladin.iam.v1.TokenPair
	11, // 1: paladin.iam.v1.LoginResponse.user:type_name -> paladin.iam.v1.User
	10, // 2: paladin.iam.v1.RefreshTokenResponse.tokens:type_name -> paladin.iam.v1.TokenPair
	11, // 3: paladin.iam.v1.WhoAmIResponse.user:type_name -> paladin.iam.v1.User
	0,  // 4: paladin.iam.v1.AuthService.Login:input_type -> paladin.iam.v1.LoginRequest
	2,  // 5: paladin.iam.v1.AuthService.RefreshToken:input_type -> paladin.iam.v1.RefreshTokenRequest
	4,  // 6: paladin.iam.v1.AuthService.Revoke:input_type -> paladin.iam.v1.RevokeRequest
	6,  // 7: paladin.iam.v1.AuthService.WhoAmI:input_type -> paladin.iam.v1.WhoAmIRequest
	8,  // 8: paladin.iam.v1.AuthService.ChangePassword:input_type -> paladin.iam.v1.ChangePasswordRequest
	1,  // 9: paladin.iam.v1.AuthService.Login:output_type -> paladin.iam.v1.LoginResponse
	3,  // 10: paladin.iam.v1.AuthService.RefreshToken:output_type -> paladin.iam.v1.RefreshTokenResponse
	5,  // 11: paladin.iam.v1.AuthService.Revoke:output_type -> paladin.iam.v1.RevokeResponse
	7,  // 12: paladin.iam.v1.AuthService.WhoAmI:output_type -> paladin.iam.v1.WhoAmIResponse
	9,  // 13: paladin.iam.v1.AuthService.ChangePassword:output_type -> paladin.iam.v1.ChangePasswordResponse
	9,  // [9:14] is the sub-list for method output_type
	4,  // [4:9] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_paladin_iam_v1_auth_service_proto_init() }
func file_paladin_iam_v1_auth_service_proto_init() {
	if File_paladin_iam_v1_auth_service_proto != nil {
		return
	}
	file_paladin_iam_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paladin_iam_v1_auth_service_proto_rawDesc), len(file_paladin_iam_v1_auth_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paladin_iam_v1_auth_service_proto_goTypes,
		DependencyIndexes: file_paladin_iam_v1_auth_service_proto_depIdxs,
		MessageInfos:      file_paladin_iam_v1_auth_service_proto_msgTypes,
	}.Build()
	File_paladin_iam_v1_auth_service_proto = out.File
	file_paladin_iam_v1_auth_service_proto_goTypes = nil
	file_paladin_iam_v1_auth_service_proto_depIdxs = nil
}
