// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package auth

import (
	mock "github.com/stretchr/testify/mock"
)

// newMockidempotencyKeyCarrier creates a new instance of mockidempotencyKeyCarrier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockidempotencyKeyCarrier(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockidempotencyKeyCarrier {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &mockidempotencyKeyCarrier{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// mockidempotencyKeyCarrier is an autogenerated mock type for the idempotencyKeyCarrier type
type mockidempotencyKeyCarrier struct {
	mock.Mock
}

type mockidempotencyKeyCarrier_Expecter struct {
	mock *mock.Mock
}

func (_m *mockidempotencyKeyCarrier) EXPECT() *mockidempotencyKeyCarrier_Expecter {
	return &mockidempotencyKeyCarrier_Expecter{mock: &_m.Mock}
}

// GetIdempotencyKey provides a mock function for the type mockidempotencyKeyCarrier
func (_mock *mockidempotencyKeyCarrier) GetIdempotencyKey() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetIdempotencyKey")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// mockidempotencyKeyCarrier_GetIdempotencyKey_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIdempotencyKey'
type mockidempotencyKeyCarrier_GetIdempotencyKey_Call struct {
	*mock.Call
}

// GetIdempotencyKey is a helper method to define mock.On call
func (_e *mockidempotencyKeyCarrier_Expecter) GetIdempotencyKey() *mockidempotencyKeyCarrier_GetIdempotencyKey_Call {
	return &mockidempotencyKeyCarrier_GetIdempotencyKey_Call{Call: _e.mock.On("GetIdempotencyKey")}
}

func (_c *mockidempotencyKeyCarrier_GetIdempotencyKey_Call) Run(run func()) *mockidempotencyKeyCarrier_GetIdempotencyKey_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockidempotencyKeyCarrier_GetIdempotencyKey_Call) Return(s string) *mockidempotencyKeyCarrier_GetIdempotencyKey_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *mockidempotencyKeyCarrier_GetIdempotencyKey_Call) RunAndReturn(run func() string) *mockidempotencyKeyCarrier_GetIdempotencyKey_Call {
	_c.Call.Return(run)
	return _c
}
