// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             (unknown)
// source: public/v1/paladin.proto

package publicapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Paladin_CreateObject_FullMethodName      = "/paladin.public.v1.Paladin/CreateObject"
	Paladin_GetObject_FullMethodName         = "/paladin.public.v1.Paladin/GetObject"
	Paladin_GetObjectMeta_FullMethodName     = "/paladin.public.v1.Paladin/GetObjectMeta"
	Paladin_CompleteObject_FullMethodName    = "/paladin.public.v1.Paladin/CompleteObject"
	Paladin_DeleteObject_FullMethodName      = "/paladin.public.v1.Paladin/DeleteObject"
	Paladin_RestoreObject_FullMethodName     = "/paladin.public.v1.Paladin/RestoreObject"
	Paladin_PurgeObject_FullMethodName       = "/paladin.public.v1.Paladin/PurgeObject"
	Paladin_InitiateMultipart_FullMethodName = "/paladin.public.v1.Paladin/InitiateMultipart"
	Paladin_SignPart_FullMethodName          = "/paladin.public.v1.Paladin/SignPart"
	Paladin_CompleteMultipart_FullMethodName = "/paladin.public.v1.Paladin/CompleteMultipart"
	Paladin_AbortMultipart_FullMethodName    = "/paladin.public.v1.Paladin/AbortMultipart"
	Paladin_ListCategories_FullMethodName    = "/paladin.public.v1.Paladin/ListCategories"
	Paladin_GetCategory_FullMethodName       = "/paladin.public.v1.Paladin/GetCategory"
	Paladin_CreateCategory_FullMethodName    = "/paladin.public.v1.Paladin/CreateCategory"
	Paladin_DeleteCategory_FullMethodName    = "/paladin.public.v1.Paladin/DeleteCategory"
	Paladin_GetCategoryStats_FullMethodName  = "/paladin.public.v1.Paladin/GetCategoryStats"
	Paladin_GetObjectStats_FullMethodName    = "/paladin.public.v1.Paladin/GetObjectStats"
	Paladin_ListObjects_FullMethodName       = "/paladin.public.v1.Paladin/ListObjects"
)

// PaladinClient is the client API for Paladin service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PaladinClient interface {
	CreateObject(ctx context.Context, in *CreateObjectRequest, opts ...grpc.CallOption) (*CreateObjectResponse, error)
	GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (*GetObjectResponse, error)
	GetObjectMeta(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (*GetObjectMetaResponse, error)
	CompleteObject(ctx context.Context, in *CompleteObjectRequest, opts ...grpc.CallOption) (*CompleteObjectResponse, error)
	DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*DeleteObjectResponse, error)
	// RestoreObject brings back a soft-deleted object to its original state.
	RestoreObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*DeleteObjectResponse, error)
	// PurgeObject permanently deletes an object and its data from storage.
	// This action cannot be undone.
	PurgeObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*DeleteObjectResponse, error)
	InitiateMultipart(ctx context.Context, in *InitiateMultipartRequest, opts ...grpc.CallOption) (*InitiateMultipartResponse, error)
	SignPart(ctx context.Context, in *SignPartRequest, opts ...grpc.CallOption) (*SignPartResponse, error)
	CompleteMultipart(ctx context.Context, in *CompleteMultipartRequest, opts ...grpc.CallOption) (*CompleteMultipartResponse, error)
	AbortMultipart(ctx context.Context, in *AbortMultipartRequest, opts ...grpc.CallOption) (*AbortMultipartResponse, error)
	// Categories
	ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error)
	GetCategory(ctx context.Context, in *GetCategoryRequest, opts ...grpc.CallOption) (*GetCategoryResponse, error)
	CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*GetCategoryResponse, error)
	DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error)
	GetCategoryStats(ctx context.Context, in *GetCategoryStatsRequest, opts ...grpc.CallOption) (*GetCategoryStatsResponse, error)
	GetObjectStats(ctx context.Context, in *GetObjectStatsRequest, opts ...grpc.CallOption) (*GetObjectStatsResponse, error)
	ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*ListObjectsResponse, error)
}

type objectControlPlaneClient struct {
	cc grpc.ClientConnInterface
}

func NewPaladinClient(cc grpc.ClientConnInterface) PaladinClient {
	return &objectControlPlaneClient{cc}
}

func (c *objectControlPlaneClient) CreateObject(ctx context.Context, in *CreateObjectRequest, opts ...grpc.CallOption) (*CreateObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateObjectResponse)
	err := c.cc.Invoke(ctx, Paladin_CreateObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectControlPlaneClient) GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (*GetObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetObjectResponse)
	err := c.cc.Invoke(ctx, Paladin_GetObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectControlPlaneClient) GetObjectMeta(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (*GetObjectMetaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetObjectMetaResponse)
	err := c.cc.Invoke(ctx, Paladin_GetObjectMeta_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectControlPlaneClient) CompleteObject(ctx context.Context, in *CompleteObjectRequest, opts ...grpc.CallOption) (*CompleteObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteObjectResponse)
	err := c.cc.Invoke(ctx, Paladin_CompleteObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectControlPlaneClient) DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*DeleteObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteObjectResponse)
	err := c.cc.Invoke(ctx, Paladin_DeleteObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectControlPlaneClient) RestoreObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*DeleteObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteObjectResponse)
	err := c.cc.Invoke(ctx, Paladin_RestoreObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectControlPlaneClient) PurgeObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*DeleteObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteObjectResponse)
	err := c.cc.Invoke(ctx, Paladin_PurgeObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectControlPlaneClient) InitiateMultipart(ctx context.Context, in *InitiateMultipartRequest, opts ...grpc.CallOption) (*InitiateMultipartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateMultipartResponse)
	err := c.cc.Invoke(ctx, Paladin_InitiateMultipart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectControlPlaneClient) SignPart(ctx context.Context, in *SignPartRequest, opts ...grpc.CallOption) (*SignPartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SignPartResponse)
	err := c.cc.Invoke(ctx, Paladin_SignPart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectControlPlaneClient) CompleteMultipart(ctx context.Context, in *CompleteMultipartRequest, opts ...grpc.CallOption) (*CompleteMultipartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteMultipartResponse)
	err := c.cc.Invoke(ctx, Paladin_CompleteMultipart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectControlPlaneClient) AbortMultipart(ctx context.Context, in *AbortMultipartRequest, opts ...grpc.CallOption) (*AbortMultipartResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortMultipartResponse)
	err := c.cc.Invoke(ctx, Paladin_AbortMultipart_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectControlPlaneClient) ListCategories(ctx context.Context, in *ListCategoriesRequest, opts ...grpc.CallOption) (*ListCategoriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCategoriesResponse)
	err := c.cc.Invoke(ctx, Paladin_ListCategories_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectControlPlaneClient) GetCategory(ctx context.Context, in *GetCategoryRequest, opts ...grpc.CallOption) (*GetCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoryResponse)
	err := c.cc.Invoke(ctx, Paladin_GetCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectControlPlaneClient) CreateCategory(ctx context.Context, in *CreateCategoryRequest, opts ...grpc.CallOption) (*GetCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoryResponse)
	err := c.cc.Invoke(ctx, Paladin_CreateCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectControlPlaneClient) DeleteCategory(ctx context.Context, in *DeleteCategoryRequest, opts ...grpc.CallOption) (*DeleteCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCategoryResponse)
	err := c.cc.Invoke(ctx, Paladin_DeleteCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectControlPlaneClient) GetCategoryStats(ctx context.Context, in *GetCategoryStatsRequest, opts ...grpc.CallOption) (*GetCategoryStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCategoryStatsResponse)
	err := c.cc.Invoke(ctx, Paladin_GetCategoryStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectControlPlaneClient) GetObjectStats(ctx context.Context, in *GetObjectStatsRequest, opts ...grpc.CallOption) (*GetObjectStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetObjectStatsResponse)
	err := c.cc.Invoke(ctx, Paladin_GetObjectStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *objectControlPlaneClient) ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*ListObjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListObjectsResponse)
	err := c.cc.Invoke(ctx, Paladin_ListObjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PaladinServer is the server API for Paladin service.
// All implementations must embed UnimplementedPaladinServer
// for forward compatibility.
type PaladinServer interface {
	CreateObject(context.Context, *CreateObjectRequest) (*CreateObjectResponse, error)
	GetObject(context.Context, *GetObjectRequest) (*GetObjectResponse, error)
	GetObjectMeta(context.Context, *GetObjectRequest) (*GetObjectMetaResponse, error)
	CompleteObject(context.Context, *CompleteObjectRequest) (*CompleteObjectResponse, error)
	DeleteObject(context.Context, *DeleteObjectRequest) (*DeleteObjectResponse, error)
	// RestoreObject brings back a soft-deleted object to its original state.
	RestoreObject(context.Context, *DeleteObjectRequest) (*DeleteObjectResponse, error)
	// PurgeObject permanently deletes an object and its data from storage.
	// This action cannot be undone.
	PurgeObject(context.Context, *DeleteObjectRequest) (*DeleteObjectResponse, error)
	InitiateMultipart(context.Context, *InitiateMultipartRequest) (*InitiateMultipartResponse, error)
	SignPart(context.Context, *SignPartRequest) (*SignPartResponse, error)
	CompleteMultipart(context.Context, *CompleteMultipartRequest) (*CompleteMultipartResponse, error)
	AbortMultipart(context.Context, *AbortMultipartRequest) (*AbortMultipartResponse, error)
	// Categories
	ListCategories(context.Context, *ListCategoriesRequest) (*ListCategoriesResponse, error)
	GetCategory(context.Context, *GetCategoryRequest) (*GetCategoryResponse, error)
	CreateCategory(context.Context, *CreateCategoryRequest) (*GetCategoryResponse, error)
	DeleteCategory(context.Context, *DeleteCategoryRequest) (*DeleteCategoryResponse, error)
	GetCategoryStats(context.Context, *GetCategoryStatsRequest) (*GetCategoryStatsResponse, error)
	GetObjectStats(context.Context, *GetObjectStatsRequest) (*GetObjectStatsResponse, error)
	ListObjects(context.Context, *ListObjectsRequest) (*ListObjectsResponse, error)
	mustEmbedUnimplementedPaladinServer()
}

// UnimplementedPaladinServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPaladinServer struct{}

func (UnimplementedPaladinServer) CreateObject(context.Context, *CreateObjectRequest) (*CreateObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateObject not implemented")
}
func (UnimplementedPaladinServer) GetObject(context.Context, *GetObjectRequest) (*GetObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetObject not implemented")
}
func (UnimplementedPaladinServer) GetObjectMeta(context.Context, *GetObjectRequest) (*GetObjectMetaResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetObjectMeta not implemented")
}
func (UnimplementedPaladinServer) CompleteObject(context.Context, *CompleteObjectRequest) (*CompleteObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteObject not implemented")
}
func (UnimplementedPaladinServer) DeleteObject(context.Context, *DeleteObjectRequest) (*DeleteObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteObject not implemented")
}
func (UnimplementedPaladinServer) RestoreObject(context.Context, *DeleteObjectRequest) (*DeleteObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RestoreObject not implemented")
}
func (UnimplementedPaladinServer) PurgeObject(context.Context, *DeleteObjectRequest) (*DeleteObjectResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PurgeObject not implemented")
}
func (UnimplementedPaladinServer) InitiateMultipart(context.Context, *InitiateMultipartRequest) (*InitiateMultipartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InitiateMultipart not implemented")
}
func (UnimplementedPaladinServer) SignPart(context.Context, *SignPartRequest) (*SignPartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SignPart not implemented")
}
func (UnimplementedPaladinServer) CompleteMultipart(context.Context, *CompleteMultipartRequest) (*CompleteMultipartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteMultipart not implemented")
}
func (UnimplementedPaladinServer) AbortMultipart(context.Context, *AbortMultipartRequest) (*AbortMultipartResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AbortMultipart not implemented")
}
func (UnimplementedPaladinServer) ListCategories(context.Context, *ListCategoriesRequest) (*ListCategoriesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCategories not implemented")
}
func (UnimplementedPaladinServer) GetCategory(context.Context, *GetCategoryRequest) (*GetCategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategory not implemented")
}
func (UnimplementedPaladinServer) CreateCategory(context.Context, *CreateCategoryRequest) (*GetCategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateCategory not implemented")
}
func (UnimplementedPaladinServer) DeleteCategory(context.Context, *DeleteCategoryRequest) (*DeleteCategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCategory not implemented")
}
func (UnimplementedPaladinServer) GetCategoryStats(context.Context, *GetCategoryStatsRequest) (*GetCategoryStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCategoryStats not implemented")
}
func (UnimplementedPaladinServer) GetObjectStats(context.Context, *GetObjectStatsRequest) (*GetObjectStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetObjectStats not implemented")
}
func (UnimplementedPaladinServer) ListObjects(context.Context, *ListObjectsRequest) (*ListObjectsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListObjects not implemented")
}
func (UnimplementedPaladinServer) mustEmbedUnimplementedPaladinServer() {}
func (UnimplementedPaladinServer) testEmbeddedByValue()                            {}

// UnsafePaladinServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PaladinServer will
// result in compilation errors.
type UnsafePaladinServer interface {
	mustEmbedUnimplementedPaladinServer()
}

func RegisterPaladinServer(s grpc.ServiceRegistrar, srv PaladinServer) {
	// If the following call panics, it indicates UnimplementedPaladinServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Paladin_ServiceDesc, srv)
}

func _Paladin_CreateObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaladinServer).CreateObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paladin_CreateObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaladinServer).CreateObject(ctx, req.(*CreateObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paladin_GetObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaladinServer).GetObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paladin_GetObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaladinServer).GetObject(ctx, req.(*GetObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paladin_GetObjectMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaladinServer).GetObjectMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paladin_GetObjectMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaladinServer).GetObjectMeta(ctx, req.(*GetObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paladin_CompleteObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaladinServer).CompleteObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paladin_CompleteObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaladinServer).CompleteObject(ctx, req.(*CompleteObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paladin_DeleteObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaladinServer).DeleteObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paladin_DeleteObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaladinServer).DeleteObject(ctx, req.(*DeleteObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paladin_RestoreObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaladinServer).RestoreObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paladin_RestoreObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaladinServer).RestoreObject(ctx, req.(*DeleteObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paladin_PurgeObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaladinServer).PurgeObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paladin_PurgeObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaladinServer).PurgeObject(ctx, req.(*DeleteObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paladin_InitiateMultipart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateMultipartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaladinServer).InitiateMultipart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paladin_InitiateMultipart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaladinServer).InitiateMultipart(ctx, req.(*InitiateMultipartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paladin_SignPart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SignPartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaladinServer).SignPart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paladin_SignPart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaladinServer).SignPart(ctx, req.(*SignPartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paladin_CompleteMultipart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteMultipartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaladinServer).CompleteMultipart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paladin_CompleteMultipart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaladinServer).CompleteMultipart(ctx, req.(*CompleteMultipartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paladin_AbortMultipart_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortMultipartRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaladinServer).AbortMultipart(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paladin_AbortMultipart_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaladinServer).AbortMultipart(ctx, req.(*AbortMultipartRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paladin_ListCategories_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCategoriesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaladinServer).ListCategories(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paladin_ListCategories_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaladinServer).ListCategories(ctx, req.(*ListCategoriesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paladin_GetCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaladinServer).GetCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paladin_GetCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaladinServer).GetCategory(ctx, req.(*GetCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paladin_CreateCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaladinServer).CreateCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paladin_CreateCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaladinServer).CreateCategory(ctx, req.(*CreateCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paladin_DeleteCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaladinServer).DeleteCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paladin_DeleteCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaladinServer).DeleteCategory(ctx, req.(*DeleteCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paladin_GetCategoryStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCategoryStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaladinServer).GetCategoryStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paladin_GetCategoryStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaladinServer).GetCategoryStats(ctx, req.(*GetCategoryStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paladin_GetObjectStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaladinServer).GetObjectStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paladin_GetObjectStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaladinServer).GetObjectStats(ctx, req.(*GetObjectStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Paladin_ListObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PaladinServer).ListObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Paladin_ListObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PaladinServer).ListObjects(ctx, req.(*ListObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Paladin_ServiceDesc is the grpc.ServiceDesc for Paladin service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Paladin_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "paladin.public.v1.Paladin",
	HandlerType: (*PaladinServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateObject",
			Handler:    _Paladin_CreateObject_Handler,
		},
		{
			MethodName: "GetObject",
			Handler:    _Paladin_GetObject_Handler,
		},
		{
			MethodName: "GetObjectMeta",
			Handler:    _Paladin_GetObjectMeta_Handler,
		},
		{
			MethodName: "CompleteObject",
			Handler:    _Paladin_CompleteObject_Handler,
		},
		{
			MethodName: "DeleteObject",
			Handler:    _Paladin_DeleteObject_Handler,
		},
		{
			MethodName: "RestoreObject",
			Handler:    _Paladin_RestoreObject_Handler,
		},
		{
			MethodName: "PurgeObject",
			Handler:    _Paladin_PurgeObject_Handler,
		},
		{
			MethodName: "InitiateMultipart",
			Handler:    _Paladin_InitiateMultipart_Handler,
		},
		{
			MethodName: "SignPart",
			Handler:    _Paladin_SignPart_Handler,
		},
		{
			MethodName: "CompleteMultipart",
			Handler:    _Paladin_CompleteMultipart_Handler,
		},
		{
			MethodName: "AbortMultipart",
			Handler:    _Paladin_AbortMultipart_Handler,
		},
		{
			MethodName: "ListCategories",
			Handler:    _Paladin_ListCategories_Handler,
		},
		{
			MethodName: "GetCategory",
			Handler:    _Paladin_GetCategory_Handler,
		},
		{
			MethodName: "CreateCategory",
			Handler:    _Paladin_CreateCategory_Handler,
		},
		{
			MethodName: "DeleteCategory",
			Handler:    _Paladin_DeleteCategory_Handler,
		},
		{
			MethodName: "GetCategoryStats",
			Handler:    _Paladin_GetCategoryStats_Handler,
		},
		{
			MethodName: "GetObjectStats",
			Handler:    _Paladin_GetObjectStats_Handler,
		},
		{
			MethodName: "ListObjects",
			Handler:    _Paladin_ListObjects_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "public/v1/paladin.proto",
}
