// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: paladin/v1/tenant_service.proto

package paladinapiconnect

import (
	context "context"
	errors "errors"
	http "net/http"
	strings "strings"

	connect "connectrpc.com/connect"
	paladinapi "github.com/oleg-tkachuk/paladin/internal/api/connect/paladinapi"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TenantServiceName is the fully-qualified name of the TenantService service.
	TenantServiceName = "paladin.v1.TenantService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TenantServiceCreateTenantProcedure is the fully-qualified name of the TenantService's
	// CreateTenant RPC.
	TenantServiceCreateTenantProcedure = "/paladin.v1.TenantService/CreateTenant"
	// TenantServiceGetTenantProcedure is the fully-qualified name of the TenantService's GetTenant RPC.
	TenantServiceGetTenantProcedure = "/paladin.v1.TenantService/GetTenant"
	// TenantServiceListTenantsProcedure is the fully-qualified name of the TenantService's ListTenants
	// RPC.
	TenantServiceListTenantsProcedure = "/paladin.v1.TenantService/ListTenants"
	// TenantServiceDeleteTenantProcedure is the fully-qualified name of the TenantService's
	// DeleteTenant RPC.
	TenantServiceDeleteTenantProcedure = "/paladin.v1.TenantService/DeleteTenant"
	// TenantServiceUpdateTenantMetadataProcedure is the fully-qualified name of the TenantService's
	// UpdateTenantMetadata RPC.
	TenantServiceUpdateTenantMetadataProcedure = "/paladin.v1.TenantService/UpdateTenantMetadata"
)

// TenantServiceClient is a client for the paladin.v1.TenantService service.
type TenantServiceClient interface {
	// CreateTenant provisions a new tenant in the system.
	CreateTenant(context.Context, *connect.Request[paladinapi.CreateTenantRequest]) (*connect.Response[paladinapi.CreateTenantResponse], error)
	// GetTenant retrieves a tenant's details and metadata.
	GetTenant(context.Context, *connect.Request[paladinapi.GetTenantRequest]) (*connect.Response[paladinapi.GetTenantResponse], error)
	// ListTenants returns a paginated list of tenants matching the filter.
	ListTenants(context.Context, *connect.Request[paladinapi.ListTenantsRequest]) (*connect.Response[paladinapi.ListTenantsResponse], error)
	// DeleteTenant removes a tenant record. Fails if the tenant still has objects.
	DeleteTenant(context.Context, *connect.Request[paladinapi.DeleteTenantRequest]) (*connect.Response[paladinapi.DeleteTenantResponse], error)
	// UpdateTenantMetadata performs a partial update of a tenant's labels, tags, or display name.
	UpdateTenantMetadata(context.Context, *connect.Request[paladinapi.UpdateTenantMetadataRequest]) (*connect.Response[paladinapi.UpdateTenantMetadataResponse], error)
}

// NewTenantServiceClient constructs a client for the paladin.v1.TenantService service. By default, it
// uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses, and sends
// uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or
// connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTenantServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TenantServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	tenantServiceMethods := paladinapi.File_paladin_v1_tenant_service_proto.Services().ByName("TenantService").Methods()
	return &tenantServiceClient{
		createTenant: connect.NewClient[paladinapi.CreateTenantRequest, paladinapi.CreateTenantResponse](
			httpClient,
			baseURL+TenantServiceCreateTenantProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("CreateTenant")),
			connect.WithClientOptions(opts...),
		),
		getTenant: connect.NewClient[paladinapi.GetTenantRequest, paladinapi.GetTenantResponse](
			httpClient,
			baseURL+TenantServiceGetTenantProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("GetTenant")),
			connect.WithClientOptions(opts...),
		),
		listTenants: connect.NewClient[paladinapi.ListTenantsRequest, paladinapi.ListTenantsResponse](
			httpClient,
			baseURL+TenantServiceListTenantsProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("ListTenants")),
			connect.WithClientOptions(opts...),
		),
		deleteTenant: connect.NewClient[paladinapi.DeleteTenantRequest, paladinapi.DeleteTenantResponse](
			httpClient,
			baseURL+TenantServiceDeleteTenantProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("DeleteTenant")),
			connect.WithClientOptions(opts...),
		),
		updateTenantMetadata: connect.NewClient[paladinapi.UpdateTenantMetadataRequest, paladinapi.UpdateTenantMetadataResponse](
			httpClient,
			baseURL+TenantServiceUpdateTenantMetadataProcedure,
			connect.WithSchema(tenantServiceMethods.ByName("UpdateTenantMetadata")),
			connect.WithClientOptions(opts...),
		),
	}
}

// tenantServiceClient implements TenantServiceClient.
type tenantServiceClient struct {
	createTenant         *connect.Client[paladinapi.CreateTenantRequest, paladinapi.CreateTenantResponse]
	getTenant            *connect.Client[paladinapi.GetTenantRequest, paladinapi.GetTenantResponse]
	listTenants          *connect.Client[paladinapi.ListTenantsRequest, paladinapi.ListTenantsResponse]
	deleteTenant         *connect.Client[paladinapi.DeleteTenantRequest, paladinapi.DeleteTenantResponse]
	updateTenantMetadata *connect.Client[paladinapi.UpdateTenantMetadataRequest, paladinapi.UpdateTenantMetadataResponse]
}

// CreateTenant calls paladin.v1.TenantService.CreateTenant.
func (c *tenantServiceClient) CreateTenant(ctx context.Context, req *connect.Request[paladinapi.CreateTenantRequest]) (*connect.Response[paladinapi.CreateTenantResponse], error) {
	return c.createTenant.CallUnary(ctx, req)
}

// GetTenant calls paladin.v1.TenantService.GetTenant.
func (c *tenantServiceClient) GetTenant(ctx context.Context, req *connect.Request[paladinapi.GetTenantRequest]) (*connect.Response[paladinapi.GetTenantResponse], error) {
	return c.getTenant.CallUnary(ctx, req)
}

// ListTenants calls paladin.v1.TenantService.ListTenants.
func (c *tenantServiceClient) ListTenants(ctx context.Context, req *connect.Request[paladinapi.ListTenantsRequest]) (*connect.Response[paladinapi.ListTenantsResponse], error) {
	return c.listTenants.CallUnary(ctx, req)
}

// DeleteTenant calls paladin.v1.TenantService.DeleteTenant.
func (c *tenantServiceClient) DeleteTenant(ctx context.Context, req *connect.Request[paladinapi.DeleteTenantRequest]) (*connect.Response[paladinapi.DeleteTenantResponse], error) {
	return c.deleteTenant.CallUnary(ctx, req)
}

// UpdateTenantMetadata calls paladin.v1.TenantService.UpdateTenantMetadata.
func (c *tenantServiceClient) UpdateTenantMetadata(ctx context.Context, req *connect.Request[paladinapi.UpdateTenantMetadataRequest]) (*connect.Response[paladinapi.UpdateTenantMetadataResponse], error) {
	return c.updateTenantMetadata.CallUnary(ctx, req)
}

// TenantServiceHandler is an implementation of the paladin.v1.TenantService service.
type TenantServiceHandler interface {
	// CreateTenant provisions a new tenant in the system.
	CreateTenant(context.Context, *connect.Request[paladinapi.CreateTenantRequest]) (*connect.Response[paladinapi.CreateTenantResponse], error)
	// GetTenant retrieves a tenant's details and metadata.
	GetTenant(context.Context, *connect.Request[paladinapi.GetTenantRequest]) (*connect.Response[paladinapi.GetTenantResponse], error)
	// ListTenants returns a paginated list of tenants matching the filter.
	ListTenants(context.Context, *connect.Request[paladinapi.ListTenantsRequest]) (*connect.Response[paladinapi.ListTenantsResponse], error)
	// DeleteTenant removes a tenant record. Fails if the tenant still has objects.
	DeleteTenant(context.Context, *connect.Request[paladinapi.DeleteTenantRequest]) (*connect.Response[paladinapi.DeleteTenantResponse], error)
	// UpdateTenantMetadata performs a partial update of a tenant's labels, tags, or display name.
	UpdateTenantMetadata(context.Context, *connect.Request[paladinapi.UpdateTenantMetadataRequest]) (*connect.Response[paladinapi.UpdateTenantMetadataResponse], error)
}

// NewTenantServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTenantServiceHandler(svc TenantServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	tenantServiceMethods := paladinapi.File_paladin_v1_tenant_service_proto.Services().ByName("TenantService").Methods()
	tenantServiceCreateTenantHandler := connect.NewUnaryHandler(
		TenantServiceCreateTenantProcedure,
		svc.CreateTenant,
		connect.WithSchema(tenantServiceMethods.ByName("CreateTenant")),
		connect.WithHandlerOptions(opts...),
	)
	tenantServiceGetTenantHandler := connect.NewUnaryHandler(
		TenantServiceGetTenantProcedure,
		svc.GetTenant,
		connect.WithSchema(tenantServiceMethods.ByName("GetTenant")),
		connect.WithHandlerOptions(opts...),
	)
	tenantServiceListTenantsHandler := connect.NewUnaryHandler(
		TenantServiceListTenantsProcedure,
		svc.ListTenants,
		connect.WithSchema(tenantServiceMethods.ByName("ListTenants")),
		connect.WithHandlerOptions(opts...),
	)
	tenantServiceDeleteTenantHandler := connect.NewUnaryHandler(
		TenantServiceDeleteTenantProcedure,
		svc.DeleteTenant,
		connect.WithSchema(tenantServiceMethods.ByName("DeleteTenant")),
		connect.WithHandlerOptions(opts...),
	)
	tenantServiceUpdateTenantMetadataHandler := connect.NewUnaryHandler(
		TenantServiceUpdateTenantMetadataProcedure,
		svc.UpdateTenantMetadata,
		connect.WithSchema(tenantServiceMethods.ByName("UpdateTenantMetadata")),
		connect.WithHandlerOptions(opts...),
	)
	return "/paladin.v1.TenantService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TenantServiceCreateTenantProcedure:
			tenantServiceCreateTenantHandler.ServeHTTP(w, r)
		case TenantServiceGetTenantProcedure:
			tenantServiceGetTenantHandler.ServeHTTP(w, r)
		case TenantServiceListTenantsProcedure:
			tenantServiceListTenantsHandler.ServeHTTP(w, r)
		case TenantServiceDeleteTenantProcedure:
			tenantServiceDeleteTenantHandler.ServeHTTP(w, r)
		case TenantServiceUpdateTenantMetadataProcedure:
			tenantServiceUpdateTenantMetadataHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTenantServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTenantServiceHandler struct{}

func (UnimplementedTenantServiceHandler) CreateTenant(context.Context, *connect.Request[paladinapi.CreateTenantRequest]) (*connect.Response[paladinapi.CreateTenantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paladin.v1.TenantService.CreateTenant is not implemented"))
}

func (UnimplementedTenantServiceHandler) GetTenant(context.Context, *connect.Request[paladinapi.GetTenantRequest]) (*connect.Response[paladinapi.GetTenantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paladin.v1.TenantService.GetTenant is not implemented"))
}

func (UnimplementedTenantServiceHandler) ListTenants(context.Context, *connect.Request[paladinapi.ListTenantsRequest]) (*connect.Response[paladinapi.ListTenantsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paladin.v1.TenantService.ListTenants is not implemented"))
}

func (UnimplementedTenantServiceHandler) DeleteTenant(context.Context, *connect.Request[paladinapi.DeleteTenantRequest]) (*connect.Response[paladinapi.DeleteTenantResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paladin.v1.TenantService.DeleteTenant is not implemented"))
}

func (UnimplementedTenantServiceHandler) UpdateTenantMetadata(context.Context, *connect.Request[paladinapi.UpdateTenantMetadataRequest]) (*connect.Response[paladinapi.UpdateTenantMetadataResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("paladin.v1.TenantService.UpdateTenantMetadata is not implemented"))
}
