"""Python client for the Paladin API.

The generated stubs live in ``paladin.admin.v1``, ``paladin.data.v1``,
``paladin.iam.v1`` and ``paladin.common.v1``. ``paladin.connect`` builds a
client for every service of each plane; ``paladin.client`` holds what every
call needs, and ``paladin.auth`` the tokens.
"""

from paladin.auth import (
    AUDIENCE_ADMIN,
    AUDIENCE_DATA,
    AUDIENCE_IAM,
    TOKEN_REFRESH_MARGIN,
    AsyncSession,
    Session,
    StaticToken,
)
from paladin.client import (
    DEFAULT_RETRY_BASE_DELAY,
    DEFAULT_RETRY_MAX_DELAY,
    HEADER_API_TOKEN,
    HEADER_AUTHORIZATION,
    HEADER_CAPABILITY,
    HEADER_IDEMPOTENCY_KEY,
    HEADER_RETRY_AFTER,
    HEADER_USER_AGENT,
    Client,
    Retry,
    current_idempotency_key,
    default_retryable,
    idempotency_key,
    no_idempotency_key,
    parse_retry_after,
    user_agent,
)
from paladin.connect import AsyncPaladin, Endpoints, Paladin, connect, connect_async
from paladin.tls import DEFAULT_TLS_RELOAD_INTERVAL, TLS
from paladin.transfer import (
    CHECKSUM_CRC32C,
    CHECKSUM_MD5,
    CHECKSUM_SHA256,
    DEFAULT_TRANSFER_CONNECT_TIMEOUT,
    DEFAULT_TRANSFER_POOL_MAX_IDLE_PER_HOST,
    DEFAULT_TRANSFER_READ_TIMEOUT,
    IntegrityError,
    ObjectReader,
    RangeIgnoredError,
    Transfer,
    TransferError,
)
from paladin.workflows import (
    DEFAULT_MAX_POLL_INTERVAL,
    DEFAULT_MULTIPART_THRESHOLD,
    DEFAULT_PART_CONCURRENCY,
    DEFAULT_POLL_INTERVAL,
    OperationFailed,
    apages,
    await_operation,
    download,
    download_stream,
    mask,
    pages,
    upload,
    wait,
)

__all__ = [
    "AUDIENCE_ADMIN",
    "AUDIENCE_DATA",
    "AUDIENCE_IAM",
    "CHECKSUM_CRC32C",
    "CHECKSUM_MD5",
    "CHECKSUM_SHA256",
    "DEFAULT_MAX_POLL_INTERVAL",
    "DEFAULT_MULTIPART_THRESHOLD",
    "DEFAULT_PART_CONCURRENCY",
    "DEFAULT_POLL_INTERVAL",
    "DEFAULT_RETRY_BASE_DELAY",
    "DEFAULT_RETRY_MAX_DELAY",
    "DEFAULT_TLS_RELOAD_INTERVAL",
    "DEFAULT_TRANSFER_CONNECT_TIMEOUT",
    "DEFAULT_TRANSFER_POOL_MAX_IDLE_PER_HOST",
    "DEFAULT_TRANSFER_READ_TIMEOUT",
    "HEADER_API_TOKEN",
    "HEADER_AUTHORIZATION",
    "HEADER_CAPABILITY",
    "HEADER_IDEMPOTENCY_KEY",
    "HEADER_RETRY_AFTER",
    "HEADER_USER_AGENT",
    "TLS",
    "TOKEN_REFRESH_MARGIN",
    "AsyncPaladin",
    "AsyncSession",
    "Client",
    "Endpoints",
    "IntegrityError",
    "ObjectReader",
    "OperationFailed",
    "Paladin",
    "RangeIgnoredError",
    "Retry",
    "Session",
    "StaticToken",
    "Transfer",
    "TransferError",
    "apages",
    "await_operation",
    "connect",
    "connect_async",
    "current_idempotency_key",
    "default_retryable",
    "download",
    "download_stream",
    "idempotency_key",
    "mask",
    "no_idempotency_key",
    "pages",
    "parse_retry_after",
    "upload",
    "user_agent",
    "wait",
]
