// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: paladin/data/v1/object_service.proto

package paladindatav1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/oleg-tkachuk/paladin/internal/api/pb/common/v1"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PresignTransport int32

const (
	PresignTransport_PRESIGN_TRANSPORT_UNSPECIFIED PresignTransport = 0
	PresignTransport_PRESIGN_TRANSPORT_PUT         PresignTransport = 1
	PresignTransport_PRESIGN_TRANSPORT_POST        PresignTransport = 2
)

// Enum value maps for PresignTransport.
var (
	PresignTransport_name = map[int32]string{
		0: "PRESIGN_TRANSPORT_UNSPECIFIED",
		1: "PRESIGN_TRANSPORT_PUT",
		2: "PRESIGN_TRANSPORT_POST",
	}
	PresignTransport_value = map[string]int32{
		"PRESIGN_TRANSPORT_UNSPECIFIED": 0,
		"PRESIGN_TRANSPORT_PUT":         1,
		"PRESIGN_TRANSPORT_POST":        2,
	}
)

func (x PresignTransport) Enum() *PresignTransport {
	p := new(PresignTransport)
	*p = x
	return p
}

func (x PresignTransport) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PresignTransport) Descriptor() protoreflect.EnumDescriptor {
	return file_paladin_data_v1_object_service_proto_enumTypes[0].Descriptor()
}

func (PresignTransport) Type() protoreflect.EnumType {
	return &file_paladin_data_v1_object_service_proto_enumTypes[0]
}

func (x PresignTransport) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PresignTransport.Descriptor instead.
func (PresignTransport) EnumDescriptor() ([]byte, []int) {
	return file_paladin_data_v1_object_service_proto_rawDescGZIP(), []int{0}
}

// ─── Versioning ─────────────────────────────────────────────────────────────
type ObjectVersion struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource name: "tenants/{tenant_id_or_slug}/collections/{ok}/objects/{id}/versions/{ver}".
	Name           string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	VersionId      string                 `protobuf:"bytes,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	ObjectId       string                 `protobuf:"bytes,3,opt,name=object_id,json=objectId,proto3" json:"object_id,omitempty"`
	IsDeleteMarker bool                   `protobuf:"varint,4,opt,name=is_delete_marker,json=isDeleteMarker,proto3" json:"is_delete_marker,omitempty"`
	StoragePath    string                 `protobuf:"bytes,5,opt,name=storage_path,json=storagePath,proto3" json:"storage_path,omitempty"`
	SizeBytes      int64                  `protobuf:"varint,6,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	Etag           string                 `protobuf:"bytes,7,opt,name=etag,proto3" json:"etag,omitempty"`
	Checksum       *ChecksumDigest        `protobuf:"bytes,8,opt,name=checksum,proto3" json:"checksum,omitempty"`
	ContentType    string                 `protobuf:"bytes,9,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,10,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags           map[string]string      `protobuf:"bytes,11,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Lock           *ObjectLockState       `protobuf:"bytes,12,opt,name=lock,proto3" json:"lock,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	IsCurrent      bool                   `protobuf:"varint,14,opt,name=is_current,json=isCurrent,proto3" json:"is_current,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ObjectVersion) Reset() {
	*x = ObjectVersion{}
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectVersion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectVersion) ProtoMessage() {}

func (x *ObjectVersion) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectVersion.ProtoReflect.Descriptor instead.
func (*ObjectVersion) Descriptor() ([]byte, []int) {
	return file_paladin_data_v1_object_service_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectVersion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectVersion) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

func (x *ObjectVersion) GetObjectId() string {
	if x != nil {
		return x.ObjectId
	}
	return ""
}

func (x *ObjectVersion) GetIsDeleteMarker() bool {
	if x != nil {
		return x.IsDeleteMarker
	}
	return false
}

func (x *ObjectVersion) GetStoragePath() string {
	if x != nil {
		return x.StoragePath
	}
	return ""
}

func (x *ObjectVersion) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ObjectVersion) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *ObjectVersion) GetChecksum() *ChecksumDigest {
	if x != nil {
		return x.Checksum
	}
	return nil
}

func (x *ObjectVersion) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ObjectVersion) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *ObjectVersion) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *ObjectVersion) GetLock() *ObjectLockState {
	if x != nil {
		return x.Lock
	}
	return nil
}

func (x *ObjectVersion) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ObjectVersion) GetIsCurrent() bool {
	if x != nil {
		return x.IsCurrent
	}
	return false
}

type ListObjectVersionsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Object resource name (parent of the versions collection).
	Parent        string          `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Page          *v1.PageRequest `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObjectVersionsRequest) Reset() {
	*x = ListObjectVersionsRequest{}
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectVersionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectVersionsRequest) ProtoMessage() {}

func (x *ListObjectVersionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectVersionsRequest.ProtoReflect.Descriptor instead.
func (*ListObjectVersionsRequest) Descriptor() ([]byte, []int) {
	return file_paladin_data_v1_object_service_proto_rawDescGZIP(), []int{1}
}

func (x *ListObjectVersionsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListObjectVersionsRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

type ListObjectVersionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*ObjectVersion       `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	Page          *v1.PageResponse       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObjectVersionsResponse) Reset() {
	*x = ListObjectVersionsResponse{}
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectVersionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectVersionsResponse) ProtoMessage() {}

func (x *ListObjectVersionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectVersionsResponse.ProtoReflect.Descriptor instead.
func (*ListObjectVersionsResponse) Descriptor() ([]byte, []int) {
	return file_paladin_data_v1_object_service_proto_rawDescGZIP(), []int{2}
}

func (x *ListObjectVersionsResponse) GetVersions() []*ObjectVersion {
	if x != nil {
		return x.Versions
	}
	return nil
}

func (x *ListObjectVersionsResponse) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type GetObjectVersionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Resource name: "tenants/{tenant_id_or_slug}/collections/{ok}/objects/{id}/versions/{ver}".
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectVersionRequest) Reset() {
	*x = GetObjectVersionRequest{}
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectVersionRequest) ProtoMessage() {}

func (x *GetObjectVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectVersionRequest.ProtoReflect.Descriptor instead.
func (*GetObjectVersionRequest) Descriptor() ([]byte, []int) {
	return file_paladin_data_v1_object_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetObjectVersionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RestoreObjectVersionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// OCC, required: expected_version=0 disables the check in SQL, so an
	//   absent guard would restore over a concurrent change instead of
	//   failing. This is the CURRENT object's version, not the version being
	//   restored — the console takes it from the object the versions tab is
	//   showing.
	ResourceVersion string `protobuf:"bytes,2,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RestoreObjectVersionRequest) Reset() {
	*x = RestoreObjectVersionRequest{}
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreObjectVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreObjectVersionRequest) ProtoMessage() {}

func (x *RestoreObjectVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreObjectVersionRequest.ProtoReflect.Descriptor instead.
func (*RestoreObjectVersionRequest) Descriptor() ([]byte, []int) {
	return file_paladin_data_v1_object_service_proto_rawDescGZIP(), []int{4}
}

func (x *RestoreObjectVersionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestoreObjectVersionRequest) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

// ─── Upload ─────────────────────────────────────────────────────────────────
type UploadObjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parent Collection: "tenants/{tenant_id_or_slug}/collections/{ok}".
	Parent        string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Key           string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"` // empty → server uses object_id as key
	ContentType   string `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	SizeHintBytes int64  `protobuf:"varint,4,opt,name=size_hint_bytes,json=sizeHintBytes,proto3" json:"size_hint_bytes,omitempty"`
	// UNSPECIFIED is allowed and means "let the server pick" — handler
	// resolves the empty value to SHA256 (the data-plane default the
	// PresignedPUT verification path expects). The earlier
	// `not_in: [0]` rule was failing every JSON client that omits
	// enum-zero on the wire, including stale browser bundles.
	ChecksumAlgorithm v1.ChecksumAlgorithm `protobuf:"varint,5,opt,name=checksum_algorithm,json=checksumAlgorithm,proto3,enum=paladin.common.v1.ChecksumAlgorithm" json:"checksum_algorithm,omitempty"`
	Metadata          map[string]string    `protobuf:"bytes,6,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags              map[string]string    `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ExternalRef       string               `protobuf:"bytes,8,opt,name=external_ref,json=externalRef,proto3" json:"external_ref,omitempty"`
	Transport         PresignTransport     `protobuf:"varint,9,opt,name=transport,proto3,enum=paladin.data.v1.PresignTransport" json:"transport,omitempty"`
	// Optional idempotency key. Equivalent to the `Idempotency-Key` HTTP
	// header — the interceptor reads whichever is present, and rejects the
	// request if both are set and disagree. A repeat with the same key
	// replays the first response instead of re-executing.
	IdempotencyKey string `protobuf:"bytes,10,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UploadObjectRequest) Reset() {
	*x = UploadObjectRequest{}
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadObjectRequest) ProtoMessage() {}

func (x *UploadObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadObjectRequest.ProtoReflect.Descriptor instead.
func (*UploadObjectRequest) Descriptor() ([]byte, []int) {
	return file_paladin_data_v1_object_service_proto_rawDescGZIP(), []int{5}
}

func (x *UploadObjectRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *UploadObjectRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UploadObjectRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UploadObjectRequest) GetSizeHintBytes() int64 {
	if x != nil {
		return x.SizeHintBytes
	}
	return 0
}

func (x *UploadObjectRequest) GetChecksumAlgorithm() v1.ChecksumAlgorithm {
	if x != nil {
		return x.ChecksumAlgorithm
	}
	return v1.ChecksumAlgorithm(0)
}

func (x *UploadObjectRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UploadObjectRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UploadObjectRequest) GetExternalRef() string {
	if x != nil {
		return x.ExternalRef
	}
	return ""
}

func (x *UploadObjectRequest) GetTransport() PresignTransport {
	if x != nil {
		return x.Transport
	}
	return PresignTransport_PRESIGN_TRANSPORT_UNSPECIFIED
}

func (x *UploadObjectRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type UploadObjectResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Object         *Object                `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	UploadUrl      *v1.PresignedUrl       `protobuf:"bytes,2,opt,name=upload_url,json=uploadUrl,proto3" json:"upload_url,omitempty"`
	CompletionMode v1.CompletionMode      `protobuf:"varint,3,opt,name=completion_mode,json=completionMode,proto3,enum=paladin.common.v1.CompletionMode" json:"completion_mode,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UploadObjectResponse) Reset() {
	*x = UploadObjectResponse{}
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadObjectResponse) ProtoMessage() {}

func (x *UploadObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadObjectResponse.ProtoReflect.Descriptor instead.
func (*UploadObjectResponse) Descriptor() ([]byte, []int) {
	return file_paladin_data_v1_object_service_proto_rawDescGZIP(), []int{6}
}

func (x *UploadObjectResponse) GetObject() *Object {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *UploadObjectResponse) GetUploadUrl() *v1.PresignedUrl {
	if x != nil {
		return x.UploadUrl
	}
	return nil
}

func (x *UploadObjectResponse) GetCompletionMode() v1.CompletionMode {
	if x != nil {
		return x.CompletionMode
	}
	return v1.CompletionMode(0)
}

// ─── Download ───────────────────────────────────────────────────────────────
type DownloadObjectRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Name               string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Ttl                *durationpb.Duration   `protobuf:"bytes,2,opt,name=ttl,proto3" json:"ttl,omitempty"`
	ContentDisposition string                 `protobuf:"bytes,3,opt,name=content_disposition,json=contentDisposition,proto3" json:"content_disposition,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DownloadObjectRequest) Reset() {
	*x = DownloadObjectRequest{}
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadObjectRequest) ProtoMessage() {}

func (x *DownloadObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadObjectRequest.ProtoReflect.Descriptor instead.
func (*DownloadObjectRequest) Descriptor() ([]byte, []int) {
	return file_paladin_data_v1_object_service_proto_rawDescGZIP(), []int{7}
}

func (x *DownloadObjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DownloadObjectRequest) GetTtl() *durationpb.Duration {
	if x != nil {
		return x.Ttl
	}
	return nil
}

func (x *DownloadObjectRequest) GetContentDisposition() string {
	if x != nil {
		return x.ContentDisposition
	}
	return ""
}

type DownloadObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        *Object                `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	DownloadUrl   *v1.PresignedUrl       `protobuf:"bytes,2,opt,name=download_url,json=downloadUrl,proto3" json:"download_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadObjectResponse) Reset() {
	*x = DownloadObjectResponse{}
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadObjectResponse) ProtoMessage() {}

func (x *DownloadObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadObjectResponse.ProtoReflect.Descriptor instead.
func (*DownloadObjectResponse) Descriptor() ([]byte, []int) {
	return file_paladin_data_v1_object_service_proto_rawDescGZIP(), []int{8}
}

func (x *DownloadObjectResponse) GetObject() *Object {
	if x != nil {
		return x.Object
	}
	return nil
}

func (x *DownloadObjectResponse) GetDownloadUrl() *v1.PresignedUrl {
	if x != nil {
		return x.DownloadUrl
	}
	return nil
}

// ─── Get / Lookup ───────────────────────────────────────────────────────────
type GetObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectRequest) Reset() {
	*x = GetObjectRequest{}
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectRequest) ProtoMessage() {}

func (x *GetObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectRequest.ProtoReflect.Descriptor instead.
func (*GetObjectRequest) Descriptor() ([]byte, []int) {
	return file_paladin_data_v1_object_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetObjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type LookupObjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parent Collection — required to disambiguate `key` lookups.
	Parent        string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Key           string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LookupObjectRequest) Reset() {
	*x = LookupObjectRequest{}
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupObjectRequest) ProtoMessage() {}

func (x *LookupObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupObjectRequest.ProtoReflect.Descriptor instead.
func (*LookupObjectRequest) Descriptor() ([]byte, []int) {
	return file_paladin_data_v1_object_service_proto_rawDescGZIP(), []int{10}
}

func (x *LookupObjectRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *LookupObjectRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

// ─── Update ─────────────────────────────────────────────────────────────────
type UpdateObjectRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Name            string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ResourceVersion string                 `protobuf:"bytes,2,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	UpdateMask      *fieldmaskpb.FieldMask `protobuf:"bytes,3,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	Metadata        map[string]string      `protobuf:"bytes,4,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Tags            map[string]string      `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ContentType     string                 `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	ExternalRef     string                 `protobuf:"bytes,7,opt,name=external_ref,json=externalRef,proto3" json:"external_ref,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateObjectRequest) Reset() {
	*x = UpdateObjectRequest{}
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateObjectRequest) ProtoMessage() {}

func (x *UpdateObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateObjectRequest.ProtoReflect.Descriptor instead.
func (*UpdateObjectRequest) Descriptor() ([]byte, []int) {
	return file_paladin_data_v1_object_service_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateObjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateObjectRequest) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

func (x *UpdateObjectRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateObjectRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *UpdateObjectRequest) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *UpdateObjectRequest) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *UpdateObjectRequest) GetExternalRef() string {
	if x != nil {
		return x.ExternalRef
	}
	return ""
}

// ─── Complete ───────────────────────────────────────────────────────────────
type CompleteObjectRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Etag          string                 `protobuf:"bytes,2,opt,name=etag,proto3" json:"etag,omitempty"`
	ChecksumValue string                 `protobuf:"bytes,3,opt,name=checksum_value,json=checksumValue,proto3" json:"checksum_value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteObjectRequest) Reset() {
	*x = CompleteObjectRequest{}
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteObjectRequest) ProtoMessage() {}

func (x *CompleteObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteObjectRequest.ProtoReflect.Descriptor instead.
func (*CompleteObjectRequest) Descriptor() ([]byte, []int) {
	return file_paladin_data_v1_object_service_proto_rawDescGZIP(), []int{12}
}

func (x *CompleteObjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CompleteObjectRequest) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *CompleteObjectRequest) GetChecksumValue() string {
	if x != nil {
		return x.ChecksumValue
	}
	return ""
}

// ─── Delete / Restore ───────────────────────────────────────────────────────
type DeleteObjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// OCC, required: an absent guard would silently become a blind delete
	//   (expected_version=0 disables the check in SQL). permanent and
	//   bypass_governance_retention widen what is destroyed; neither is an
	//   opt-out of the concurrency check.
	ResourceVersion string `protobuf:"bytes,2,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	Permanent       bool   `protobuf:"varint,3,opt,name=permanent,proto3" json:"permanent,omitempty"`
	// Only honored when the caller has GOVERNANCE bypass (role
	// `lock.governance.bypass` or `platform.admin`), and only against a
	// GOVERNANCE window — legal hold and COMPLIANCE are absolute. The server
	// sets `paladin.bypass_governance_retention` for the deletion transaction;
	// the trigger on object_locks reads it before refusing to drop a locked
	// row.
	BypassGovernanceRetention bool `protobuf:"varint,4,opt,name=bypass_governance_retention,json=bypassGovernanceRetention,proto3" json:"bypass_governance_retention,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *DeleteObjectRequest) Reset() {
	*x = DeleteObjectRequest{}
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteObjectRequest) ProtoMessage() {}

func (x *DeleteObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteObjectRequest.ProtoReflect.Descriptor instead.
func (*DeleteObjectRequest) Descriptor() ([]byte, []int) {
	return file_paladin_data_v1_object_service_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteObjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeleteObjectRequest) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

func (x *DeleteObjectRequest) GetPermanent() bool {
	if x != nil {
		return x.Permanent
	}
	return false
}

func (x *DeleteObjectRequest) GetBypassGovernanceRetention() bool {
	if x != nil {
		return x.BypassGovernanceRetention
	}
	return false
}

type DeleteObjectResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Object        *Object                `protobuf:"bytes,1,opt,name=object,proto3" json:"object,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteObjectResponse) Reset() {
	*x = DeleteObjectResponse{}
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteObjectResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteObjectResponse) ProtoMessage() {}

func (x *DeleteObjectResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteObjectResponse.ProtoReflect.Descriptor instead.
func (*DeleteObjectResponse) Descriptor() ([]byte, []int) {
	return file_paladin_data_v1_object_service_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteObjectResponse) GetObject() *Object {
	if x != nil {
		return x.Object
	}
	return nil
}

// ─── Object Lock ────────────────────────────────────────────────────────────
type SetObjectRetentionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Object resource name: "tenants/{tenant}/collections/{ok}/objects/{id}".
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// GOVERNANCE | COMPLIANCE. Required.
	//
	// COMPLIANCE cannot be downgraded to GOVERNANCE and its window cannot be
	// shortened by anyone, including a platform admin — that is what makes it
	// usable as a regulatory control rather than a strong suggestion.
	Mode string `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	// When the retention expires. Must be in the future, and must not be
	// earlier than an existing window unless the current mode is GOVERNANCE
	// and bypass_governance_retention is set.
	RetainUntil *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=retain_until,json=retainUntil,proto3" json:"retain_until,omitempty"`
	// Permits shortening or clearing an active GOVERNANCE window. Requires role
	// `lock.governance.bypass` or `platform.admin`. Ignored when the existing
	// window is COMPLIANCE, which no role can shorten.
	BypassGovernanceRetention bool `protobuf:"varint,4,opt,name=bypass_governance_retention,json=bypassGovernanceRetention,proto3" json:"bypass_governance_retention,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *SetObjectRetentionRequest) Reset() {
	*x = SetObjectRetentionRequest{}
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetObjectRetentionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetObjectRetentionRequest) ProtoMessage() {}

func (x *SetObjectRetentionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetObjectRetentionRequest.ProtoReflect.Descriptor instead.
func (*SetObjectRetentionRequest) Descriptor() ([]byte, []int) {
	return file_paladin_data_v1_object_service_proto_rawDescGZIP(), []int{15}
}

func (x *SetObjectRetentionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetObjectRetentionRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *SetObjectRetentionRequest) GetRetainUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.RetainUntil
	}
	return nil
}

func (x *SetObjectRetentionRequest) GetBypassGovernanceRetention() bool {
	if x != nil {
		return x.BypassGovernanceRetention
	}
	return false
}

type SetObjectLegalHoldRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	LegalHold     bool                   `protobuf:"varint,2,opt,name=legal_hold,json=legalHold,proto3" json:"legal_hold,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetObjectLegalHoldRequest) Reset() {
	*x = SetObjectLegalHoldRequest{}
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetObjectLegalHoldRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetObjectLegalHoldRequest) ProtoMessage() {}

func (x *SetObjectLegalHoldRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetObjectLegalHoldRequest.ProtoReflect.Descriptor instead.
func (*SetObjectLegalHoldRequest) Descriptor() ([]byte, []int) {
	return file_paladin_data_v1_object_service_proto_rawDescGZIP(), []int{16}
}

func (x *SetObjectLegalHoldRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SetObjectLegalHoldRequest) GetLegalHold() bool {
	if x != nil {
		return x.LegalHold
	}
	return false
}

type GetObjectLockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetObjectLockRequest) Reset() {
	*x = GetObjectLockRequest{}
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetObjectLockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetObjectLockRequest) ProtoMessage() {}

func (x *GetObjectLockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetObjectLockRequest.ProtoReflect.Descriptor instead.
func (*GetObjectLockRequest) Descriptor() ([]byte, []int) {
	return file_paladin_data_v1_object_service_proto_rawDescGZIP(), []int{17}
}

func (x *GetObjectLockRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type RestoreObjectRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// OCC, required: expected_version=0 disables the check in SQL, so an
	//   absent guard would restore over a concurrent change instead of
	//   failing. The console reads the version from the trash listing,
	//   which shows it in a Version column.
	ResourceVersion string `protobuf:"bytes,2,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RestoreObjectRequest) Reset() {
	*x = RestoreObjectRequest{}
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreObjectRequest) ProtoMessage() {}

func (x *RestoreObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreObjectRequest.ProtoReflect.Descriptor instead.
func (*RestoreObjectRequest) Descriptor() ([]byte, []int) {
	return file_paladin_data_v1_object_service_proto_rawDescGZIP(), []int{18}
}

func (x *RestoreObjectRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RestoreObjectRequest) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

// ─── Copy ───────────────────────────────────────────────────────────────────
type CopyObjectRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	SourceName string                 `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	// Destination Collection resource name.
	DestinationCollection string            `protobuf:"bytes,2,opt,name=destination_collection,json=destinationCollection,proto3" json:"destination_collection,omitempty"`
	DestinationKey        string            `protobuf:"bytes,3,opt,name=destination_key,json=destinationKey,proto3" json:"destination_key,omitempty"`
	MetadataOverride      *MetadataOverride `protobuf:"bytes,4,opt,name=metadata_override,json=metadataOverride,proto3,oneof" json:"metadata_override,omitempty"`
	TagsOverride          *TagsOverride     `protobuf:"bytes,5,opt,name=tags_override,json=tagsOverride,proto3,oneof" json:"tags_override,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *CopyObjectRequest) Reset() {
	*x = CopyObjectRequest{}
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CopyObjectRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CopyObjectRequest) ProtoMessage() {}

func (x *CopyObjectRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CopyObjectRequest.ProtoReflect.Descriptor instead.
func (*CopyObjectRequest) Descriptor() ([]byte, []int) {
	return file_paladin_data_v1_object_service_proto_rawDescGZIP(), []int{19}
}

func (x *CopyObjectRequest) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *CopyObjectRequest) GetDestinationCollection() string {
	if x != nil {
		return x.DestinationCollection
	}
	return ""
}

func (x *CopyObjectRequest) GetDestinationKey() string {
	if x != nil {
		return x.DestinationKey
	}
	return ""
}

func (x *CopyObjectRequest) GetMetadataOverride() *MetadataOverride {
	if x != nil {
		return x.MetadataOverride
	}
	return nil
}

func (x *CopyObjectRequest) GetTagsOverride() *TagsOverride {
	if x != nil {
		return x.TagsOverride
	}
	return nil
}

type MetadataOverride struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      map[string]string      `protobuf:"bytes,1,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataOverride) Reset() {
	*x = MetadataOverride{}
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataOverride) ProtoMessage() {}

func (x *MetadataOverride) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataOverride.ProtoReflect.Descriptor instead.
func (*MetadataOverride) Descriptor() ([]byte, []int) {
	return file_paladin_data_v1_object_service_proto_rawDescGZIP(), []int{20}
}

func (x *MetadataOverride) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type TagsOverride struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          map[string]string      `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagsOverride) Reset() {
	*x = TagsOverride{}
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagsOverride) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagsOverride) ProtoMessage() {}

func (x *TagsOverride) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagsOverride.ProtoReflect.Descriptor instead.
func (*TagsOverride) Descriptor() ([]byte, []int) {
	return file_paladin_data_v1_object_service_proto_rawDescGZIP(), []int{21}
}

func (x *TagsOverride) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

// ─── List / Count ───────────────────────────────────────────────────────────
type ListObjectsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parent Collection: "tenants/{tenant_id_or_slug}/collections/{ok}".
	Parent        string          `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Page          *v1.PageRequest `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	Filter        string          `protobuf:"bytes,3,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy       string          `protobuf:"bytes,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	SortOrder     v1.SortOrder    `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3,enum=paladin.common.v1.SortOrder" json:"sort_order,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObjectsRequest) Reset() {
	*x = ListObjectsRequest{}
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsRequest) ProtoMessage() {}

func (x *ListObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsRequest.ProtoReflect.Descriptor instead.
func (*ListObjectsRequest) Descriptor() ([]byte, []int) {
	return file_paladin_data_v1_object_service_proto_rawDescGZIP(), []int{22}
}

func (x *ListObjectsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *ListObjectsRequest) GetPage() *v1.PageRequest {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ListObjectsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *ListObjectsRequest) GetOrderBy() string {
	if x != nil {
		return x.OrderBy
	}
	return ""
}

func (x *ListObjectsRequest) GetSortOrder() v1.SortOrder {
	if x != nil {
		return x.SortOrder
	}
	return v1.SortOrder(0)
}

type ListObjectsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*Object              `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	Page          *v1.PageResponse       `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListObjectsResponse) Reset() {
	*x = ListObjectsResponse{}
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListObjectsResponse) ProtoMessage() {}

func (x *ListObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListObjectsResponse.ProtoReflect.Descriptor instead.
func (*ListObjectsResponse) Descriptor() ([]byte, []int) {
	return file_paladin_data_v1_object_service_proto_rawDescGZIP(), []int{23}
}

func (x *ListObjectsResponse) GetObjects() []*Object {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *ListObjectsResponse) GetPage() *v1.PageResponse {
	if x != nil {
		return x.Page
	}
	return nil
}

type CountObjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parent        string                 `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Filter        string                 `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CountObjectsRequest) Reset() {
	*x = CountObjectsRequest{}
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountObjectsRequest) ProtoMessage() {}

func (x *CountObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountObjectsRequest.ProtoReflect.Descriptor instead.
func (*CountObjectsRequest) Descriptor() ([]byte, []int) {
	return file_paladin_data_v1_object_service_proto_rawDescGZIP(), []int{24}
}

func (x *CountObjectsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CountObjectsRequest) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

type CountObjectsResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ApproximateCount int64                  `protobuf:"varint,1,opt,name=approximate_count,json=approximateCount,proto3" json:"approximate_count,omitempty"`
	Exact            bool                   `protobuf:"varint,2,opt,name=exact,proto3" json:"exact,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CountObjectsResponse) Reset() {
	*x = CountObjectsResponse{}
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CountObjectsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CountObjectsResponse) ProtoMessage() {}

func (x *CountObjectsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_paladin_data_v1_object_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CountObjectsResponse.ProtoReflect.Descriptor instead.
func (*CountObjectsResponse) Descriptor() ([]byte, []int) {
	return file_paladin_data_v1_object_service_proto_rawDescGZIP(), []int{25}
}

func (x *CountObjectsResponse) GetApproximateCount() int64 {
	if x != nil {
		return x.ApproximateCount
	}
	return 0
}

func (x *CountObjectsResponse) GetExact() bool {
	if x != nil {
		return x.Exact
	}
	return false
}

var File_paladin_data_v1_object_service_proto protoreflect.FileDescriptor

const file_paladin_data_v1_object_service_proto_rawDesc = "" +
	"\n" +
	"#paladin/data/v1/object_service.proto\x12\x0elegate.data.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1egoogle/protobuf/duration.proto\x1a google/protobuf/field_mask.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a!paladin/common/v1/pagination.proto\x1a\x1flegate/common/v1/resource.proto\x1a\x1alegate/data/v1/types.proto\x1a\x1fgoogle/api/field_behavior.proto\"\xd3\x05\n" +
	"\rObjectVersion\x12\x17\n" +
	"\x04name\x18\x01 \x01(\tB\x03\xe0A\bR\x04name\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\tR\tversionId\x12\x1b\n" +
	"\tobject_id\x18\x03 \x01(\tR\bobjectId\x12(\n" +
	"\x10is_delete_marker\x18\x04 \x01(\bR\x0eisDeleteMarker\x12!\n" +
	"\fstorage_path\x18\x05 \x01(\tR\vstoragePath\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\x06 \x01(\x03R\tsizeBytes\x12\x12\n" +
	"\x04etag\x18\a \x01(\tR\x04etag\x12:\n" +
	"\bchecksum\x18\b \x01(\v2\x1e.paladin.data.v1.ChecksumDigestR\bchecksum\x12!\n" +
	"\fcontent_type\x18\t \x01(\tR\vcontentType\x12G\n" +
	"\bmetadata\x18\n" +
	" \x03(\v2+.paladin.data.v1.ObjectVersion.MetadataEntryR\bmetadata\x12;\n" +
	"\x04tags\x18\v \x03(\v2'.paladin.data.v1.ObjectVersion.TagsEntryR\x04tags\x123\n" +
	"\x04lock\x18\f \x01(\v2\x1f.paladin.data.v1.ObjectLockStateR\x04lock\x12>\n" +
	"\n" +
	"created_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampB\x03\xe0A\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"is_current\x18\x0e \x01(\bR\tisCurrent\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	"\x19ListObjectVersionsRequest\x12\x1f\n" +
	"\x06parent\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06parent\x121\n" +
	"\x04page\x18\x02 \x01(\v2\x1d.paladin.common.v1.PageRequestR\x04page\"\x8b\x01\n" +
	"\x1aListObjectVersionsResponse\x129\n" +
	"\bversions\x18\x01 \x03(\v2\x1d.paladin.data.v1.ObjectVersionR\bversions\x122\n" +
	"\x04page\x18\x02 \x01(\v2\x1e.paladin.common.v1.PageResponseR\x04page\"6\n" +
	"\x17GetObjectVersionRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\"n\n" +
	"\x1bRestoreObjectVersionRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x122\n" +
	"\x10resource_version\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0fresourceVersion\"\x8e\x05\n" +
	"\x13UploadObjectRequest\x12\x1f\n" +
	"\x06parent\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06parent\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12*\n" +
	"\fcontent_type\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\vcontentType\x12&\n" +
	"\x0fsize_hint_bytes\x18\x04 \x01(\x03R\rsizeHintBytes\x12\\\n" +
	"\x12checksum_algorithm\x18\x05 \x01(\x0e2#.paladin.common.v1.ChecksumAlgorithmB\b\xbaH\x05\x82\x01\x02\x10\x01R\x11checksumAlgorithm\x12M\n" +
	"\bmetadata\x18\x06 \x03(\v21.paladin.data.v1.UploadObjectRequest.MetadataEntryR\bmetadata\x12A\n" +
	"\x04tags\x18\a \x03(\v2-.paladin.data.v1.UploadObjectRequest.TagsEntryR\x04tags\x12!\n" +
	"\fexternal_ref\x18\b \x01(\tR\vexternalRef\x12>\n" +
	"\ttransport\x18\t \x01(\x0e2 .paladin.data.v1.PresignTransportR\ttransport\x12'\n" +
	"\x0fidempotency_key\x18\n" +
	" \x01(\tR\x0eidempotencyKey\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd0\x01\n" +
	"\x14UploadObjectResponse\x12.\n" +
	"\x06object\x18\x01 \x01(\v2\x16.paladin.data.v1.ObjectR\x06object\x12=\n" +
	"\n" +
	"upload_url\x18\x02 \x01(\v2\x1e.paladin.common.v1.PresignedUrlR\tuploadUrl\x12I\n" +
	"\x0fcompletion_mode\x18\x03 \x01(\x0e2 .paladin.common.v1.CompletionModeR\x0ecompletionMode\"\x92\x01\n" +
	"\x15DownloadObjectRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12+\n" +
	"\x03ttl\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x03ttl\x12/\n" +
	"\x13content_disposition\x18\x03 \x01(\tR\x12contentDisposition\"\x8b\x01\n" +
	"\x16DownloadObjectResponse\x12.\n" +
	"\x06object\x18\x01 \x01(\v2\x16.paladin.data.v1.ObjectR\x06object\x12A\n" +
	"\fdownload_url\x18\x02 \x01(\v2\x1e.paladin.common.v1.PresignedUrlR\vdownloadUrl\"/\n" +
	"\x10GetObjectRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\"Q\n" +
	"\x13LookupObjectRequest\x12\x1f\n" +
	"\x06parent\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06parent\x12\x19\n" +
	"\x03key\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x03key\"\xf9\x03\n" +
	"\x13UpdateObjectRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x122\n" +
	"\x10resource_version\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0fresourceVersion\x12C\n" +
	"\vupdate_mask\x18\x03 \x01(\v2\x1a.google.protobuf.FieldMaskB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"updateMask\x12M\n" +
	"\bmetadata\x18\x04 \x03(\v21.paladin.data.v1.UpdateObjectRequest.MetadataEntryR\bmetadata\x12A\n" +
	"\x04tags\x18\x05 \x03(\v2-.paladin.data.v1.UpdateObjectRequest.TagsEntryR\x04tags\x12!\n" +
	"\fcontent_type\x18\x06 \x01(\tR\vcontentType\x12!\n" +
	"\fexternal_ref\x18\a \x01(\tR\vexternalRef\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"o\n" +
	"\x15CompleteObjectRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12\x12\n" +
	"\x04etag\x18\x02 \x01(\tR\x04etag\x12%\n" +
	"\x0echecksum_value\x18\x03 \x01(\tR\rchecksumValue\"\xc4\x01\n" +
	"\x13DeleteObjectRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x122\n" +
	"\x10resource_version\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0fresourceVersion\x12\x1c\n" +
	"\tpermanent\x18\x03 \x01(\bR\tpermanent\x12>\n" +
	"\x1bbypass_governance_retention\x18\x04 \x01(\bR\x19bypassGovernanceRetention\"F\n" +
	"\x14DeleteObjectResponse\x12.\n" +
	"\x06object\x18\x01 \x01(\v2\x16.paladin.data.v1.ObjectR\x06object\"\xf2\x01\n" +
	"\x19SetObjectRetentionRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x121\n" +
	"\x04mode\x18\x02 \x01(\tB\x1d\xbaH\x1ar\x18R\n" +
	"GOVERNANCER\n" +
	"COMPLIANCER\x04mode\x12E\n" +
	"\fretain_until\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\vretainUntil\x12>\n" +
	"\x1bbypass_governance_retention\x18\x04 \x01(\bR\x19bypassGovernanceRetention\"W\n" +
	"\x19SetObjectLegalHoldRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x12\x1d\n" +
	"\n" +
	"legal_hold\x18\x02 \x01(\bR\tlegalHold\"3\n" +
	"\x14GetObjectLockRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\"g\n" +
	"\x14RestoreObjectRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x04name\x122\n" +
	"\x10resource_version\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0fresourceVersion\"\xf3\x02\n" +
	"\x11CopyObjectRequest\x12(\n" +
	"\vsource_name\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"sourceName\x12>\n" +
	"\x16destination_collection\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x15destinationCollection\x120\n" +
	"\x0fdestination_key\x18\x03 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x0edestinationKey\x12R\n" +
	"\x11metadata_override\x18\x04 \x01(\v2 .paladin.data.v1.MetadataOverrideH\x00R\x10metadataOverride\x88\x01\x01\x12F\n" +
	"\rtags_override\x18\x05 \x01(\v2\x1c.paladin.data.v1.TagsOverrideH\x01R\ftagsOverride\x88\x01\x01B\x14\n" +
	"\x12_metadata_overrideB\x10\n" +
	"\x0e_tags_override\"\x9b\x01\n" +
	"\x10MetadataOverride\x12J\n" +
	"\bmetadata\x18\x01 \x03(\v2..paladin.data.v1.MetadataOverride.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x83\x01\n" +
	"\fTagsOverride\x12:\n" +
	"\x04tags\x18\x01 \x03(\v2&.paladin.data.v1.TagsOverride.TagsEntryR\x04tags\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xd7\x01\n" +
	"\x12ListObjectsRequest\x12\x1f\n" +
	"\x06parent\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06parent\x121\n" +
	"\x04page\x18\x02 \x01(\v2\x1d.paladin.common.v1.PageRequestR\x04page\x12\x16\n" +
	"\x06filter\x18\x03 \x01(\tR\x06filter\x12\x19\n" +
	"\border_by\x18\x04 \x01(\tR\aorderBy\x12:\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x0e2\x1b.paladin.common.v1.SortOrderR\tsortOrder\"{\n" +
	"\x13ListObjectsResponse\x120\n" +
	"\aobjects\x18\x01 \x03(\v2\x16.paladin.data.v1.ObjectR\aobjects\x122\n" +
	"\x04page\x18\x02 \x01(\v2\x1e.paladin.common.v1.PageResponseR\x04page\"N\n" +
	"\x13CountObjectsRequest\x12\x1f\n" +
	"\x06parent\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\x06parent\x12\x16\n" +
	"\x06filter\x18\x02 \x01(\tR\x06filter\"Y\n" +
	"\x14CountObjectsResponse\x12+\n" +
	"\x11approximate_count\x18\x01 \x01(\x03R\x10approximateCount\x12\x14\n" +
	"\x05exact\x18\x02 \x01(\bR\x05exact*l\n" +
	"\x10PresignTransport\x12!\n" +
	"\x1dPRESIGN_TRANSPORT_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15PRESIGN_TRANSPORT_PUT\x10\x01\x12\x1a\n" +
	"\x16PRESIGN_TRANSPORT_POST\x10\x022\xa6\f\n" +
	"\rObjectService\x12Y\n" +
	"\fUploadObject\x12#.paladin.data.v1.UploadObjectRequest\x1a$.paladin.data.v1.UploadObjectResponse\x12_\n" +
	"\x0eDownloadObject\x12%.paladin.data.v1.DownloadObjectRequest\x1a&.paladin.data.v1.DownloadObjectResponse\x12J\n" +
	"\tGetObject\x12 .paladin.data.v1.GetObjectRequest\x1a\x16.paladin.data.v1.Object\"\x03\x90\x02\x01\x12P\n" +
	"\fLookupObject\x12#.paladin.data.v1.LookupObjectRequest\x1a\x16.paladin.data.v1.Object\"\x03\x90\x02\x01\x12P\n" +
	"\fUpdateObject\x12#.paladin.data.v1.UpdateObjectRequest\x1a\x16.paladin.data.v1.Object\"\x03\x90\x02\x02\x12O\n" +
	"\x0eCompleteObject\x12%.paladin.data.v1.CompleteObjectRequest\x1a\x16.paladin.data.v1.Object\x12^\n" +
	"\fDeleteObject\x12#.paladin.data.v1.DeleteObjectRequest\x1a$.paladin.data.v1.DeleteObjectResponse\"\x03\x90\x02\x02\x12R\n" +
	"\rRestoreObject\x12$.paladin.data.v1.RestoreObjectRequest\x1a\x16.paladin.data.v1.Object\"\x03\x90\x02\x02\x12G\n" +
	"\n" +
	"CopyObject\x12!.paladin.data.v1.CopyObjectRequest\x1a\x16.paladin.data.v1.Object\x12[\n" +
	"\vListObjects\x12\".paladin.data.v1.ListObjectsRequest\x1a#.paladin.data.v1.ListObjectsResponse\"\x03\x90\x02\x01\x12^\n" +
	"\fCountObjects\x12#.paladin.data.v1.CountObjectsRequest\x1a$.paladin.data.v1.CountObjectsResponse\"\x03\x90\x02\x01\x12p\n" +
	"\x12ListObjectVersions\x12).paladin.data.v1.ListObjectVersionsRequest\x1a*.paladin.data.v1.ListObjectVersionsResponse\"\x03\x90\x02\x01\x12_\n" +
	"\x10GetObjectVersion\x12'.paladin.data.v1.GetObjectVersionRequest\x1a\x1d.paladin.data.v1.ObjectVersion\"\x03\x90\x02\x01\x12`\n" +
	"\x14RestoreObjectVersion\x12+.paladin.data.v1.RestoreObjectVersionRequest\x1a\x16.paladin.data.v1.Object\"\x03\x90\x02\x02\x12e\n" +
	"\x12SetObjectRetention\x12).paladin.data.v1.SetObjectRetentionRequest\x1a\x1f.paladin.data.v1.ObjectLockState\"\x03\x90\x02\x02\x12e\n" +
	"\x12SetObjectLegalHold\x12).paladin.data.v1.SetObjectLegalHoldRequest\x1a\x1f.paladin.data.v1.ObjectLockState\"\x03\x90\x02\x02\x12[\n" +
	"\rGetObjectLock\x12$.paladin.data.v1.GetObjectLockRequest\x1a\x1f.paladin.data.v1.ObjectLockState\"\x03\x90\x02\x01BEZCgithub.com/oleg-tkachuk/paladin/internal/api/pb/data/v1;paladindatav1b\x06proto3"

var (
	file_paladin_data_v1_object_service_proto_rawDescOnce sync.Once
	file_paladin_data_v1_object_service_proto_rawDescData []byte
)

func file_paladin_data_v1_object_service_proto_rawDescGZIP() []byte {
	file_paladin_data_v1_object_service_proto_rawDescOnce.Do(func() {
		file_paladin_data_v1_object_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_paladin_data_v1_object_service_proto_rawDesc), len(file_paladin_data_v1_object_service_proto_rawDesc)))
	})
	return file_paladin_data_v1_object_service_proto_rawDescData
}

var file_paladin_data_v1_object_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_paladin_data_v1_object_service_proto_msgTypes = make([]protoimpl.MessageInfo, 34)
var file_paladin_data_v1_object_service_proto_goTypes = []any{
	(PresignTransport)(0),               // 0: paladin.data.v1.PresignTransport
	(*ObjectVersion)(nil),               // 1: paladin.data.v1.ObjectVersion
	(*ListObjectVersionsRequest)(nil),   // 2: paladin.data.v1.ListObjectVersionsRequest
	(*ListObjectVersionsResponse)(nil),  // 3: paladin.data.v1.ListObjectVersionsResponse
	(*GetObjectVersionRequest)(nil),     // 4: paladin.data.v1.GetObjectVersionRequest
	(*RestoreObjectVersionRequest)(nil), // 5: paladin.data.v1.RestoreObjectVersionRequest
	(*UploadObjectRequest)(nil),         // 6: paladin.data.v1.UploadObjectRequest
	(*UploadObjectResponse)(nil),        // 7: paladin.data.v1.UploadObjectResponse
	(*DownloadObjectRequest)(nil),       // 8: paladin.data.v1.DownloadObjectRequest
	(*DownloadObjectResponse)(nil),      // 9: paladin.data.v1.DownloadObjectResponse
	(*GetObjectRequest)(nil),            // 10: paladin.data.v1.GetObjectRequest
	(*LookupObjectRequest)(nil),         // 11: paladin.data.v1.LookupObjectRequest
	(*UpdateObjectRequest)(nil),         // 12: paladin.data.v1.UpdateObjectRequest
	(*CompleteObjectRequest)(nil),       // 13: paladin.data.v1.CompleteObjectRequest
	(*DeleteObjectRequest)(nil),         // 14: paladin.data.v1.DeleteObjectRequest
	(*DeleteObjectResponse)(nil),        // 15: paladin.data.v1.DeleteObjectResponse
	(*SetObjectRetentionRequest)(nil),   // 16: paladin.data.v1.SetObjectRetentionRequest
	(*SetObjectLegalHoldRequest)(nil),   // 17: paladin.data.v1.SetObjectLegalHoldRequest
	(*GetObjectLockRequest)(nil),        // 18: paladin.data.v1.GetObjectLockRequest
	(*RestoreObjectRequest)(nil),        // 19: paladin.data.v1.RestoreObjectRequest
	(*CopyObjectRequest)(nil),           // 20: paladin.data.v1.CopyObjectRequest
	(*MetadataOverride)(nil),            // 21: paladin.data.v1.MetadataOverride
	(*TagsOverride)(nil),                // 22: paladin.data.v1.TagsOverride
	(*ListObjectsRequest)(nil),          // 23: paladin.data.v1.ListObjectsRequest
	(*ListObjectsResponse)(nil),         // 24: paladin.data.v1.ListObjectsResponse
	(*CountObjectsRequest)(nil),         // 25: paladin.data.v1.CountObjectsRequest
	(*CountObjectsResponse)(nil),        // 26: paladin.data.v1.CountObjectsResponse
	nil,                                 // 27: paladin.data.v1.ObjectVersion.MetadataEntry
	nil,                                 // 28: paladin.data.v1.ObjectVersion.TagsEntry
	nil,                                 // 29: paladin.data.v1.UploadObjectRequest.MetadataEntry
	nil,                                 // 30: paladin.data.v1.UploadObjectRequest.TagsEntry
	nil,                                 // 31: paladin.data.v1.UpdateObjectRequest.MetadataEntry
	nil,                                 // 32: paladin.data.v1.UpdateObjectRequest.TagsEntry
	nil,                                 // 33: paladin.data.v1.MetadataOverride.MetadataEntry
	nil,                                 // 34: paladin.data.v1.TagsOverride.TagsEntry
	(*ChecksumDigest)(nil),              // 35: paladin.data.v1.ChecksumDigest
	(*ObjectLockState)(nil),             // 36: paladin.data.v1.ObjectLockState
	(*timestamppb.Timestamp)(nil),       // 37: google.protobuf.Timestamp
	(*v1.PageRequest)(nil),              // 38: paladin.common.v1.PageRequest
	(*v1.PageResponse)(nil),             // 39: paladin.common.v1.PageResponse
	(v1.ChecksumAlgorithm)(0),           // 40: paladin.common.v1.ChecksumAlgorithm
	(*Object)(nil),                      // 41: paladin.data.v1.Object
	(*v1.PresignedUrl)(nil),             // 42: paladin.common.v1.PresignedUrl
	(v1.CompletionMode)(0),              // 43: paladin.common.v1.CompletionMode
	(*durationpb.Duration)(nil),         // 44: google.protobuf.Duration
	(*fieldmaskpb.FieldMask)(nil),       // 45: google.protobuf.FieldMask
	(v1.SortOrder)(0),                   // 46: paladin.common.v1.SortOrder
}
var file_paladin_data_v1_object_service_proto_depIdxs = []int32{
	35, // 0: paladin.data.v1.ObjectVersion.checksum:type_name -> paladin.data.v1.ChecksumDigest
	27, // 1: paladin.data.v1.ObjectVersion.metadata:type_name -> paladin.data.v1.ObjectVersion.MetadataEntry
	28, // 2: paladin.data.v1.ObjectVersion.tags:type_name -> paladin.data.v1.ObjectVersion.TagsEntry
	36, // 3: paladin.data.v1.ObjectVersion.lock:type_name -> paladin.data.v1.ObjectLockState
	37, // 4: paladin.data.v1.ObjectVersion.created_at:type_name -> google.protobuf.Timestamp
	38, // 5: paladin.data.v1.ListObjectVersionsRequest.page:type_name -> paladin.common.v1.PageRequest
	1,  // 6: paladin.data.v1.ListObjectVersionsResponse.versions:type_name -> paladin.data.v1.ObjectVersion
	39, // 7: paladin.data.v1.ListObjectVersionsResponse.page:type_name -> paladin.common.v1.PageResponse
	40, // 8: paladin.data.v1.UploadObjectRequest.checksum_algorithm:type_name -> paladin.common.v1.ChecksumAlgorithm
	29, // 9: paladin.data.v1.UploadObjectRequest.metadata:type_name -> paladin.data.v1.UploadObjectRequest.MetadataEntry
	30, // 10: paladin.data.v1.UploadObjectRequest.tags:type_name -> paladin.data.v1.UploadObjectRequest.TagsEntry
	0,  // 11: paladin.data.v1.UploadObjectRequest.transport:type_name -> paladin.data.v1.PresignTransport
	41, // 12: paladin.data.v1.UploadObjectResponse.object:type_name -> paladin.data.v1.Object
	42, // 13: paladin.data.v1.UploadObjectResponse.upload_url:type_name -> paladin.common.v1.PresignedUrl
	43, // 14: paladin.data.v1.UploadObjectResponse.completion_mode:type_name -> paladin.common.v1.CompletionMode
	44, // 15: paladin.data.v1.DownloadObjectRequest.ttl:type_name -> google.protobuf.Duration
	41, // 16: paladin.data.v1.DownloadObjectResponse.object:type_name -> paladin.data.v1.Object
	42, // 17: paladin.data.v1.DownloadObjectResponse.download_url:type_name -> paladin.common.v1.PresignedUrl
	45, // 18: paladin.data.v1.UpdateObjectRequest.update_mask:type_name -> google.protobuf.FieldMask
	31, // 19: paladin.data.v1.UpdateObjectRequest.metadata:type_name -> paladin.data.v1.UpdateObjectRequest.MetadataEntry
	32, // 20: paladin.data.v1.UpdateObjectRequest.tags:type_name -> paladin.data.v1.UpdateObjectRequest.TagsEntry
	41, // 21: paladin.data.v1.DeleteObjectResponse.object:type_name -> paladin.data.v1.Object
	37, // 22: paladin.data.v1.SetObjectRetentionRequest.retain_until:type_name -> google.protobuf.Timestamp
	21, // 23: paladin.data.v1.CopyObjectRequest.metadata_override:type_name -> paladin.data.v1.MetadataOverride
	22, // 24: paladin.data.v1.CopyObjectRequest.tags_override:type_name -> paladin.data.v1.TagsOverride
	33, // 25: paladin.data.v1.MetadataOverride.metadata:type_name -> paladin.data.v1.MetadataOverride.MetadataEntry
	34, // 26: paladin.data.v1.TagsOverride.tags:type_name -> paladin.data.v1.TagsOverride.TagsEntry
	38, // 27: paladin.data.v1.ListObjectsRequest.page:type_name -> paladin.common.v1.PageRequest
	46, // 28: paladin.data.v1.ListObjectsRequest.sort_order:type_name -> paladin.common.v1.SortOrder
	41, // 29: paladin.data.v1.ListObjectsResponse.objects:type_name -> paladin.data.v1.Object
	39, // 30: paladin.data.v1.ListObjectsResponse.page:type_name -> paladin.common.v1.PageResponse
	6,  // 31: paladin.data.v1.ObjectService.UploadObject:input_type -> paladin.data.v1.UploadObjectRequest
	8,  // 32: paladin.data.v1.ObjectService.DownloadObject:input_type -> paladin.data.v1.DownloadObjectRequest
	10, // 33: paladin.data.v1.ObjectService.GetObject:input_type -> paladin.data.v1.GetObjectRequest
	11, // 34: paladin.data.v1.ObjectService.LookupObject:input_type -> paladin.data.v1.LookupObjectRequest
	12, // 35: paladin.data.v1.ObjectService.UpdateObject:input_type -> paladin.data.v1.UpdateObjectRequest
	13, // 36: paladin.data.v1.ObjectService.CompleteObject:input_type -> paladin.data.v1.CompleteObjectRequest
	14, // 37: paladin.data.v1.ObjectService.DeleteObject:input_type -> paladin.data.v1.DeleteObjectRequest
	19, // 38: paladin.data.v1.ObjectService.RestoreObject:input_type -> paladin.data.v1.RestoreObjectRequest
	20, // 39: paladin.data.v1.ObjectService.CopyObject:input_type -> paladin.data.v1.CopyObjectRequest
	23, // 40: paladin.data.v1.ObjectService.ListObjects:input_type -> paladin.data.v1.ListObjectsRequest
	25, // 41: paladin.data.v1.ObjectService.CountObjects:input_type -> paladin.data.v1.CountObjectsRequest
	2,  // 42: paladin.data.v1.ObjectService.ListObjectVersions:input_type -> paladin.data.v1.ListObjectVersionsRequest
	4,  // 43: paladin.data.v1.ObjectService.GetObjectVersion:input_type -> paladin.data.v1.GetObjectVersionRequest
	5,  // 44: paladin.data.v1.ObjectService.RestoreObjectVersion:input_type -> paladin.data.v1.RestoreObjectVersionRequest
	16, // 45: paladin.data.v1.ObjectService.SetObjectRetention:input_type -> paladin.data.v1.SetObjectRetentionRequest
	17, // 46: paladin.data.v1.ObjectService.SetObjectLegalHold:input_type -> paladin.data.v1.SetObjectLegalHoldRequest
	18, // 47: paladin.data.v1.ObjectService.GetObjectLock:input_type -> paladin.data.v1.GetObjectLockRequest
	7,  // 48: paladin.data.v1.ObjectService.UploadObject:output_type -> paladin.data.v1.UploadObjectResponse
	9,  // 49: paladin.data.v1.ObjectService.DownloadObject:output_type -> paladin.data.v1.DownloadObjectResponse
	41, // 50: paladin.data.v1.ObjectService.GetObject:output_type -> paladin.data.v1.Object
	41, // 51: paladin.data.v1.ObjectService.LookupObject:output_type -> paladin.data.v1.Object
	41, // 52: paladin.data.v1.ObjectService.UpdateObject:output_type -> paladin.data.v1.Object
	41, // 53: paladin.data.v1.ObjectService.CompleteObject:output_type -> paladin.data.v1.Object
	15, // 54: paladin.data.v1.ObjectService.DeleteObject:output_type -> paladin.data.v1.DeleteObjectResponse
	41, // 55: paladin.data.v1.ObjectService.RestoreObject:output_type -> paladin.data.v1.Object
	41, // 56: paladin.data.v1.ObjectService.CopyObject:output_type -> paladin.data.v1.Object
	24, // 57: paladin.data.v1.ObjectService.ListObjects:output_type -> paladin.data.v1.ListObjectsResponse
	26, // 58: paladin.data.v1.ObjectService.CountObjects:output_type -> paladin.data.v1.CountObjectsResponse
	3,  // 59: paladin.data.v1.ObjectService.ListObjectVersions:output_type -> paladin.data.v1.ListObjectVersionsResponse
	1,  // 60: paladin.data.v1.ObjectService.GetObjectVersion:output_type -> paladin.data.v1.ObjectVersion
	41, // 61: paladin.data.v1.ObjectService.RestoreObjectVersion:output_type -> paladin.data.v1.Object
	36, // 62: paladin.data.v1.ObjectService.SetObjectRetention:output_type -> paladin.data.v1.ObjectLockState
	36, // 63: paladin.data.v1.ObjectService.SetObjectLegalHold:output_type -> paladin.data.v1.ObjectLockState
	36, // 64: paladin.data.v1.ObjectService.GetObjectLock:output_type -> paladin.data.v1.ObjectLockState
	48, // [48:65] is the sub-list for method output_type
	31, // [31:48] is the sub-list for method input_type
	31, // [31:31] is the sub-list for extension type_name
	31, // [31:31] is the sub-list for extension extendee
	0,  // [0:31] is the sub-list for field type_name
}

func init() { file_paladin_data_v1_object_service_proto_init() }
func file_paladin_data_v1_object_service_proto_init() {
	if File_paladin_data_v1_object_service_proto != nil {
		return
	}
	file_paladin_data_v1_types_proto_init()
	file_paladin_data_v1_object_service_proto_msgTypes[19].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_paladin_data_v1_object_service_proto_rawDesc), len(file_paladin_data_v1_object_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   34,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_paladin_data_v1_object_service_proto_goTypes,
		DependencyIndexes: file_paladin_data_v1_object_service_proto_depIdxs,
		EnumInfos:         file_paladin_data_v1_object_service_proto_enumTypes,
		MessageInfos:      file_paladin_data_v1_object_service_proto_msgTypes,
	}.Build()
	File_paladin_data_v1_object_service_proto = out.File
	file_paladin_data_v1_object_service_proto_goTypes = nil
	file_paladin_data_v1_object_service_proto_depIdxs = nil
}
